emission_sectors:

- id: building_heating_emissions
  name: Rakennusten lämmityksen päästöt
  name_en: Building heating emissions
  name_sv: Byggnadsvärmeutsläpp
  part_of: net_emissions
- id: transport_emissions
  name: Liikenteen päästöt
  name_en: Traffic emissions
  name_sv: Trafikutsläpp
  part_of: net_emissions
- id: road_transport_emissions
  name: Tieliikenteen päästöt
  name_en: Road traffic emissions
  name_sv: Vägtrafikens utsläpp
  part_of: transport_emissions

nodes:

- id: industry_machinery_emissions
  name: Teollisuuden ja työkoneiden päästöt
  name_en: Emissions from industry and machinery
  name_sv: Utsläpp från industri och maskiner
  type: finland.hsy.HsyEmissions
  input_dimensions: [ippu, economic_sector]
  output_dimensions: [ippu, economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Teollisuus ja työkoneet|*|_ippu_|_economic_sector_
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: ippu
      flatten: true

- id: agriculture_emissions
  name: Maatalouden päästöt
  name_en: Emissions from agriculture
  name_sv: Utsläpp från jordbruket
  type: finland.hsy.HsyEmissions
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Maatalous|*|_economic_sector_|*
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true

- id: waste_treatment_emissions
  name: Jätteenkäsittelyn päästöt
  name_en: Waste treatment emissions
  name_sv: Avfallsbehandlingsutsläpp
  type: finland.hsy.HsyEmissions
  unit: kt/a
  input_dimensions: [waste_treatment, economic_sector]
  output_dimensions: [waste_treatment, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: waste_treatment
      flatten: true
  params:
    sector: Jätteiden käsittely|*|_waste_treatment_|_economic_sector_

- id: district_heating_emissions
  name: Kaukolämmön päästöt
  name_en: District heat emissions
  name_sv: Fjärrvärmeutsläpp
  output_nodes: [building_heating_emissions]
  input_nodes: [district_heating_emission_factor]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: oil_heating_emissions
  name: Öljylämmityksen päästöt
  name_en: Oil heating emissions
  name_sv: Oljeuppvärmningsutsläpp
  output_nodes: [building_heating_emissions]
  input_nodes: [oil_heating_emission_factor]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: direct_electric_heating_emissions
  name: Sähkölämmityksen päästöt
  name_en: Emissions from electric heating
  name_sv: Utsläpp från elvärme
  output_nodes: [building_heating_emissions]
  input_nodes: [electric_heating_emission_factor]
  type: simple.EmissionFactorActivity
  unit: kt/a
- id: geothermal_heating_emissions
  name: Maalämmön päästöt
  name_en: Geothermal emissions
  name_sv: Geotermiska utsläpp
  output_nodes: [building_heating_emissions]
  input_nodes: [electric_heating_emission_factor]
  type: simple.EmissionFactorActivity
  unit: kt/a

- id: non_heating_electricity_energy
  name: Kulutussähkön sähkönkulutus
  name_en: Consumption electricity consumption
  name_sv: Förbrukning elförbrukning
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|_economic_sector_
  color: '#0047b6'

- id: electricity_emissions
  name: Kulutussähkön päästöt
  name_en: Consumption electricity emissions
  name_sv: Konsumtion elutsläpp
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_nodes:
  - id: electricity_production_emission_factor
    to_dimensions: []
  - id: non_heating_electricity_energy
  # output_nodes: [electricity_emissions]
  type: simple.EmissionFactorActivity
  unit: kt/a

- id: car_emissions
  name: Henkilöautot päästöt
  name_en: Passenger car emissions
  name_sv: Personbilars utsläpp
  output_nodes: [road_transport_emissions]
  params:
    sector: Liikenne|Tieliikenne|Henkilöautot|Asuminen
  input_nodes: [all_hsy_emissions]
  type: finland.hsy.HsyEmissions

- id: non_heating_electricity_emissions_historical
  name: Kulutussähkön historialliset päästöt
  name_en: Historical consumption electricity emissions
  name_sv: Utsläpp av konsumtionsel
  description_fi: Tiedot ovat HSY:n tilastoista. Mallissa ei käytetä tätä tietoa, vaan sitä, joka on laskettu energiankulutuksesta ja päästökertoimesta.
  type: finland.hsy.HsyEmissions
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|_economic_sector_

- id: road_transport_emissions_historical
  name: Tieliikenteen historialliset päästöt
  name_en: Historical road traffic emissions
  name_sv: Historiska vägtrafikutsläpp
  description_fi: Tiedot ovat HSY:n tilastoista. Mallissa ei käytetä tätä tietoa, vaan sitä, joka on laskettu energiankulutuksesta ja päästökertoimesta.
  type: finland.hsy.HsyEmissions
  input_dimensions: [vehicle_type, economic_sector]
  output_dimensions: [vehicle_type, economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Liikenne|Tieliikenne|_vehicle_type_|_economic_sector_

- id: rail_transport_energy
  name: Raideliikenteen sähkönkulutus
  name_en: Electricity consumption of rail transport
  name_sv: Elförbrukning av järnvägtrafik
  type: finland.hsy.HsyEnergyConsumption
  unit: GWh/a
  input_dimensions: [vehicle_type, economic_sector]
  output_dimensions: [vehicle_type, economic_sector]
  params:
    sector: Liikenne|Raideliikenne|_vehicle_type_|_economic_sector_
  input_nodes: [all_hsy_emissions]

- id: rail_transport_emissions
  name: Raideliikenteen päästöt
  name_en: Emissions of rail transport
  name_sv: Utsläpp från järnvägtrafik
  type: simple.EmissionFactorActivity
  unit: kt/a
  input_dimensions: [vehicle_type, economic_sector]
  output_dimensions: [vehicle_type, economic_sector]
  input_nodes:
  - id: electricity_production_emission_factor
    to_dimensions: []
  - id: rail_transport_energy

- id: water_transport_emissions
  name_fi: Laivaliikenteen päästöt
  name_en: Shipping emissions
  name_sv: Fraktutsläpp
  type: finland.hsy.HsyEmissions
  input_dimensions: [vehicle_type, economic_sector]
  output_dimensions: [vehicle_type, economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Liikenne|Laivaliikenne|_vehicle_type_|_economic_sector_
  output_nodes:
  - id: transport_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: vehicle_type
      flatten: true

- id: district_heating_emission_factor
  name: Kaukolämmön päästökerroin
  name_en: District heating emission factor
  name_sv: Fjärrvärmeutsläppskoefficient
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Kaukolämpö|Kaukolämpö|Asuminen
- id: oil_heating_emission_factor
  name: Öljylämmityksen päästökerroin
  name_en: Oil heating emission factor
  name_sv: Emissionsfaktor för oljeuppvärmning
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Öljylämmitys|Öljylämmitys|Asuminen
- id: electricity_production_emission_factor
  name: Kansallisen sähköntuotannon päästökerroin
  name_en: National electricity production emission factor
  name_sv: Emissionskoefficient för nationell elproduktion
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Sähkö|Kulutussähkö|Kulutussähkö|Asuminen
- id: electric_heating_emission_factor
  name: Lämmityssähkön päästökerroin
  name_en: Electric heating emission factor
  name_sv: Emissionskoefficient för värmeel
  type: finland.hsy.HsyEmissionFactor
  unit: g/kWh
  input_nodes: [all_hsy_emissions]
  params:
    sector: Lämmitys|Sähkölämmitys|Sähkölämmitys|Asuminen

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name: HSY:n päästöinventaario
  name_en: HSY emission inventory
  name_sv: HRM:s utsläppsinventering
  input_datasets: ['hsy/pks_khk_paastot']

- id: building_floor_area_existing
  type: finland.aluesarjat.BuildingStock
  name: Nykyisen rakennuskannan kerrosala
  name_en: Floor area of existing building stock
  name_sv: Våningsytan i det nuvarande byggnadsbeståndet

- id: building_floor_area_new
  type: finland.aluesarjat.FutureBuildingStock
  name: Uuden rakennuskannan kerrosala
  name_en: Floor area of new building stock
  name_sv: Våningsytan i det nya byggnadsbeståndet
  input_nodes:
  - id: population
    to_dimensions: []
  - id: building_floor_area_existing
    tags: [existing_floor_area]

- id: building_floor_area_total
  name: Rakennusala kokonaisuudessaan
  type: simple.AdditiveNode
  quantity: floor_area
  unit: m**2
  input_dimensions: [building_use, building_heat_source]
  output_dimensions: [building_use, building_heat_source]
  input_nodes:
  - building_floor_area_existing
  - building_floor_area_new

- id: building_heat_statistics
  type: finland.hsy.HsyBuildingHeatConsumption
  name: Rakennuskannan lämmönkulutustilasto
  name_en: Heat consumption statistics of building stock
  name_sv: Värmeförbrukningenstatistik av byggnadsbeståndet
  tags: [historical_heat]
  input_nodes: [all_hsy_emissions]

- id: building_heat_per_floor_area_new
  name: Ominaislämmönkulutus uudessa rakennuskannassa
  type: simple.AdditiveNode
  quantity: consumption_factor
  unit: kWh/m**2/a
  input_datasets:
  - espoo/new_building_heating_per_area
  output_dimensions: [building_use]
  output_nodes:
  - id: building_heat_consumption_new
    to_dimensions:
    - id: building_use
    - id: building_heat_source
      categories: [district_heat]  # FIXME Should apply to all building_heat_sources but then gives error

- id: building_heat_per_floor_area
  name: Rakennusten lämmitys per ala
  name_en: Building heating per floor area
  name_sv: Värmeförbrukningen per våningsytan
  type: finland.aluesarjat.BuildingHeatPerArea
  quantity: consumption_factor
  unit: kWh/a/m**2
  input_dimensions: [building_use, building_heat_source]
  output_dimensions: [building_use, building_heat_source]
  input_nodes: 
  - building_heat_statistics
  - building_floor_area_existing

- id: building_heat_consumption_existing
  name: Nykyisen rakennuskannan lämmönkulutus
  name_en: Heat consumption of existing buildings
  name_sv: Värmeförbrukning i det nuvarande byggnadsbeståndet
  type: finland.hsy.MultiplicativeWithDataBackup
  quantity: energy
  unit: GWh/a
  input_dimensions: [building_heat_source, building_use]
  output_dimensions: [building_heat_source, building_use]
  input_nodes: 
  - building_heat_per_floor_area
  - building_floor_area_existing
  - id: building_heat_statistics
    tags: [data_node]

- id: building_heat_consumption
  name: Koko rakennuskannan lämmönkulutus
  name_en: Total building heat consumption
  name_sv: Total värmeförbrukning i det byggnadsbeståndet
  type: simple.AdditiveNode
  quantity: energy
  unit: GWh/a
  input_dimensions: [building_heat_source, building_use]
  output_dimensions: [building_heat_source, building_use]
  input_nodes: 
  - building_heat_consumption_existing
  - building_heat_consumption_new
  output_nodes:
  - id: district_heating_emissions
    from_dimensions:
    - id: building_heat_source
      categories: [district_heat]
      flatten: true
    - id: building_use
      flatten: true
  - id: oil_heating_emissions
    from_dimensions:
    - id: building_heat_source
      categories: [oil]
      flatten: true
    - id: building_use
      flatten: true
  - id: geothermal_heating_emissions
    from_dimensions:
    - id: building_heat_source
      categories: [geothermal]
      flatten: true
    - id: building_use
      flatten: true
  - id: direct_electric_heating_emissions
    from_dimensions:
    - id: building_heat_source
      categories: [direct_electric]
      flatten: true
    - id: building_use
      flatten: true
