# Generated by Django 5.0.6 on 2024-07-07 15:43

import django.contrib.postgres.fields
import django.db.models.deletion
import paths.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nodes', '0025_alter_instanceconfig_other_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('identifier', paths.utils.IdentifierField(max_length=50, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('unit', paths.utils.UnitField(blank=True, max_length=50, validators=[paths.utils.validate_unit], verbose_name='unit')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('time_series_max', models.FloatField(blank=True, null=True)),
                ('default_value_source', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('identifier', paths.utils.IdentifierField(max_length=50, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='frameworks.framework')),
            ],
            options={
                'ordering': ['framework', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkDimensionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='frameworks.frameworkdimension')),
            ],
            options={
                'ordering': ['dimension', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FrameworkConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('baseline_year', models.IntegerField()),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='frameworks.framework')),
                ('instance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_configs', to='nodes.instanceconfig')),
                ('categories', models.ManyToManyField(to='frameworks.frameworkdimensioncategory')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', paths.utils.UnitField(blank=True, max_length=50, null=True, validators=[paths.utils.validate_unit], verbose_name='unit')),
                ('internal_notes', models.TextField(blank=True)),
                ('framework_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='frameworks.frameworkconfig')),
                ('measure_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measures', to='frameworks.measuretemplate')),
            ],
        ),
        migrations.CreateModel(
            name='MeasureDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='frameworks.measure')),
            ],
            options={
                'ordering': ['measure', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MeasureTemplateDefaultDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField()),
                ('categories', models.ManyToManyField(to='frameworks.frameworkdimensioncategory')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_data_points', to='frameworks.measuretemplate')),
            ],
            options={
                'ordering': ['template', 'year'],
            },
        ),
        migrations.CreateModel(
            name='MeasureTemplateDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_templates_through', to='frameworks.frameworkdimension')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions_through', to='frameworks.measuretemplate')),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='measuretemplate',
            name='dimensions',
            field=models.ManyToManyField(blank=True, related_name='measure_templates', through='frameworks.MeasureTemplateDimension', to='frameworks.frameworkdimension'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identifier', paths.utils.IdentifierField(blank=True, max_length=50, null=True, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('available_years', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='frameworks.framework')),
            ],
        ),
        migrations.AddField(
            model_name='measuretemplate',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measure_templates', to='frameworks.section'),
        ),
        migrations.AddField(
            model_name='framework',
            name='root_section',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_for_framework', to='frameworks.section'),
        ),
        migrations.AddConstraint(
            model_name='frameworkconfig',
            constraint=models.UniqueConstraint(fields=('framework', 'instance_config'), name='unique_framework_instance'),
        ),
        migrations.AddConstraint(
            model_name='measure',
            constraint=models.UniqueConstraint(fields=('framework_config', 'measure_template'), name='unique_instance_measure'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('framework', 'identifier'), name='section_identifier', nulls_distinct=True),
        ),
    ]
