# Generated by Django 5.0.8 on 2024-09-02 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('frameworks', '0004_frameworkconfig_uuid_alter_framework_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='admin_group',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_for_framework', to='auth.group'),
        ),
        migrations.AddField(
            model_name='measuredatapoint',
            name='default_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='measuredatapoint',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
