# Generated by Django 5.0.8 on 2024-09-16 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0005_frameworks'),
        ('nodes', '0026_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkconfig',
            name='organization_identifier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='frameworkconfig',
            name='organization_slug',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='frameworkconfig',
            name='instance_config',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='framework_config', to='nodes.instanceconfig'),
        ),
        migrations.AlterField(
            model_name='frameworkconfig',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
