# Generated by Django 5.1.4 on 2024-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0009_framework_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretemplate',
            name='year_bound',
            field=models.BooleanField(default=False),
        ),
    ]
