# Generated by Django 5.2 on 2025-06-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0010_measuretemplate_year_bound'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretemplate',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
