# Generated by Django 5.2 on 2025-06-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0011_measuretemplate_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretemplate',
            name='help_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
