# Generated by Django 5.2.4 on 2025-10-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0015_section_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='min_total',
            field=models.FloatField(null=True),
        ),
    ]
