# Generated by Django 6.0.3 on 2026-04-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0019_framework_allow_instance_creation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='measuredatapoint',
            name='probable_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measuredatapoint',
            name='probable_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measuretemplate',
            name='default_value_scaling',
            field=models.CharField(blank=True, choices=[('population', 'Population')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='measuretemplatedefaultdatapoint',
            name='probable_lower_bound',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measuretemplatedefaultdatapoint',
            name='probable_upper_bound',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
