# Generated by Django 6.0.3 on 2026-05-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0021_merge_20260429_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='enable_user_management',
            field=models.BooleanField(default=False, help_text='Whether instance admins under this framework can manage users (add, invite, remove).', verbose_name='Enable user management'),
        ),
    ]
