# Generated by Django 6.1 on 2026-09-22 11:41

import django.contrib.postgres.functions
import django.core.validators
import django.db.models.deletion
import paths.utils
import typing
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('frameworks', '0026_backfill_instance_user_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataQualityScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'uuid',
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        unique=True,
                        verbose_name='UUID',
                    ),
                ),
                (
                    'identifier',
                    paths.utils.IdentifierField(
                        max_length=50, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier'
                    ),
                ),
                ('version', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                (
                    'framework',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='quality_schemes', to='frameworks.framework'
                    ),
                ),
            ],
            options={
                'ordering': ['framework', 'identifier', 'version'],
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.CreateModel(
            name='DataQualityLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'uuid',
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        unique=True,
                        verbose_name='UUID',
                    ),
                ),
                ('identifier', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                (
                    'score',
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal(0)),
                            django.core.validators.MaxValueValidator(Decimal(1)),
                        ],
                    ),
                ),
                (
                    'scheme',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='frameworks.dataqualityscheme'
                    ),
                ),
            ],
            options={
                'ordering': ['scheme', 'order', 'identifier'],
            },
            bases=(models.Model, typing.Generic),
        ),
        migrations.AddConstraint(
            model_name='dataqualityscheme',
            constraint=models.UniqueConstraint(
                fields=('framework', 'identifier', 'version'), name='unique_framework_quality_scheme_version'
            ),
        ),
        migrations.AddConstraint(
            model_name='dataqualitylevel',
            constraint=models.UniqueConstraint(fields=('scheme', 'identifier'), name='unique_quality_level_identifier'),
        ),
        migrations.AddConstraint(
            model_name='dataqualitylevel',
            constraint=models.CheckConstraint(
                condition=models.Q(('score__gte', 0), ('score__lte', 1)), name='quality_level_score_range'
            ),
        ),
    ]
