# Generated by Django 6.1 on 2026-09-22 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0037_source_reference_targets_exactly_one'),
        ('frameworks', '0027_data_quality_schemes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPointEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('kind', models.CharField(blank=True, choices=[('observed', 'Observed'), ('estimated', 'Estimated'), ('explicit_zero', 'Confirmed zero'), ('provider_default', 'Provider default')], max_length=30, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('data_point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='datasets.datapoint')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('quality_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='frameworks.dataqualitylevel')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('kind__isnull', False), ('quality_level__isnull', False), _connector='OR'), name='data_point_evidence_asserts_something')],
            },
        ),
    ]
