# Generated by Django 6.1 on 2026-09-22 22:08

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0028_data_point_evidence'),
        ('nodes', '0076_binding_metric_references'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('kind', models.CharField(choices=[('inventory', 'Inventory')], default='inventory', max_length=30)),
                ('period_start', models.PositiveIntegerField(help_text='First year covered.')),
                ('period_end', models.PositiveIntegerField(help_text='Last year covered; equal to the first for an inventory.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('final', 'Final'), ('superseded', 'Superseded')], default='draft', max_length=20)),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('finalised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('instance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='nodes.instanceconfig')),
                ('instance_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.revision')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='frameworks.submission')),
                ('template_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.revision')),
            ],
            options={
                'ordering': ['instance_config', '-period_start', 'kind', 'created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='submission_period_order'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'inventory'), _negated=True), ('period_end', models.F('period_start')), _connector='OR'), name='submission_inventory_single_year'), models.CheckConstraint(condition=models.Q(models.Q(('finalised_at__isnull', True), ('instance_revision__isnull', True), ('status__in', ('draft', 'in_review'))), models.Q(('finalised_at__isnull', False), ('instance_revision__isnull', False), ('status__in', ('final', 'superseded'))), _connector='OR'), name='submission_pinned_iff_finalised'), models.UniqueConstraint(condition=models.Q(('status__in', ('draft', 'in_review'))), fields=('instance_config', 'kind', 'period_start', 'period_end'), name='unique_open_submission_per_period'), models.UniqueConstraint(condition=models.Q(('status', 'final')), fields=('instance_config', 'kind', 'period_start', 'period_end'), name='unique_final_submission_per_period')],
            },
        ),
    ]
