# Generated by Django 6.1 on 2026-09-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0029_submission'),
        ('orgs', '0010_make_organization_coordinates_authoritative'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='max_user_accounts_per_instance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maximum active municipal accounts and pending invitations for one instance. Null means no limit.', null=True),
        ),
        migrations.CreateModel(
            name='OrganizationAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], max_length=10)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organization_grants', to=settings.AUTH_USER_MODEL)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_grants', to='frameworks.framework')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_organization_grants', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='orgs.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_grants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAccessGrantEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('old_role', models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], max_length=10, null=True)),
                ('new_role', models.CharField(blank=True, choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], max_length=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='frameworks.organizationaccessgrant')),
            ],
        ),
        migrations.CreateModel(
            name='FrameworkOrganizationRoot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_roots', to='frameworks.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='framework_roots', to='orgs.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('framework', 'organization'), name='unique_framework_organization_root')],
            },
        ),
        migrations.AddConstraint(
            model_name='organizationaccessgrant',
            constraint=models.UniqueConstraint(fields=('framework', 'organization', 'user'), name='unique_organization_access_grant'),
        ),
        migrations.AddConstraint(
            model_name='organizationaccessgrant',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retention_until__isnull', True), ('suspended_at__isnull', True)), models.Q(('retention_until__isnull', False), ('suspended_at__isnull', False)), _connector='OR'), name='organization_grant_suspension_has_retention'),
        ),
    ]
