# Generated by Django 6.1 on 2026-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0030_framework_max_user_accounts_per_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaccessgrantevent',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationaccessgrantevent',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
