# Generated by Django 6.1 on 2026-09-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0031_organizationaccessgrantevent_retention_until_and_more'),
        ('orgs', '0010_make_organization_coordinates_authoritative'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationPopulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('value', models.PositiveIntegerField()),
                ('source_dataset', models.CharField(max_length=200)),
                ('source_revision', models.CharField(max_length=100)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_populations', to='frameworks.framework')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='population_observations', to='orgs.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['framework', 'year'], name='framework_population_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('framework', 'organization', 'year'), name='unique_framework_org_population_year')],
            },
        ),
    ]
