# Generated by Django 6.1 on 2026-09-29 14:07

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0032_organizationpopulation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('in_review', 'In review'), ('final', 'Final'), ('superseded', 'Superseded')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('final', 'Final'), ('superseded', 'Superseded')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='frameworks.submission')),
            ],
            options={
                'ordering': ['submission', 'created_at', 'id'],
            },
        ),
    ]
