# Generated by Django 3.2.16 on 2023-03-02 14:39

from django.db import migrations
import users.base


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_uuid_and_ordering'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.base.UserManager()),
            ],
        ),
    ]
