# Generated by Django 5.0.8 on 2024-09-15 20:18

import django.core.serializers.json
import django_pydantic_field.fields
import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=users.models.UserExtra.get_default, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=users.models.UserExtra),
        ),
    ]
