# Generated by Django 5.2 on 2025-07-08 11:16

import django.db.models.deletion
import modelcluster.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0017_datasetsourcereference_uuid'),
        ('nodes', '0030_nodedataset_nodeconfig_datasets'),
        ('users', '0007_user_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='nodes.instanceconfig')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_edges', to='users.usergroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_edges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group member',
                'verbose_name_plural': 'Group members',
            },
        ),
        migrations.AddField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', through='users.UserGroupMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DatasetSchemaUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='datasets.datasetschema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'object')},
            },
        ),
        migrations.CreateModel(
            name='DatasetSchemaGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')])),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='datasets.datasetschema')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usergroup')),
            ],
            options={
                'unique_together': {('group', 'object')},
            },
        ),
        migrations.AddConstraint(
            model_name='usergroup',
            constraint=models.UniqueConstraint(fields=('instance', 'name'), name='unique_user_group_name_per_instance'),
        ),
    ]
