dimensions:
- id: flight_type
  label: Flugtyp
  label_en: Flight type
  categories:
  - id: europe
    label: Europa
    label_en: Europe
  - id: intercontinental
    label: Interkontinental
    label_en: Intercontinental

nodes:
- id: aviation_mileage_per_inhabitant
  name_de: Aviation mileage per inhabitant
  name_en: Aviation mileage per inhabitant
  type: simple.AdditiveNode
  quantity: passenger_mileage
  unit: pkm/cap/a
  input_dimensions: [flight_type]
  output_dimensions: [flight_type]
  input_datasets:
  - id: zuerich/aviation_mileage
    forecast_from: 2024
  input_dataset_processors: [LinearInterpolation]

- id: aviation_mileage
  name_de: Aviation mileage
  name_en: Aviation mileage
  type: simple.MultiplicativeNode
  quantity: passenger_mileage
  input_dimensions: [flight_type]
  output_dimensions: [flight_type]
  unit: pkm/a
  input_nodes:
  - id: population
    tags: [non_additive]
    to_dimensions: []
  - id: aviation_mileage_per_inhabitant
    tags: [non_additive]

- id: aviation_emission_factors
  name_de: Aviation emission factors
  name_en: Aviation emission factors
  type: simple.AdditiveNode
  quantity: emission_factor
  unit: kg/pkm
  input_dimensions: [flight_type]
  output_dimensions: [flight_type]
  input_datasets:
  - id: zuerich/aviation_emission_factors
    forecast_from: 2024
  input_dataset_processors: [LinearInterpolation]

- id: aviation_emissions
  name_de: Treibhausgasemissionen Flugverkehr
  name_en: Aviation emissions
  short_name_de: Flugverkehr
  short_name_en: Aviation
  type: simple.MultiplicativeNode
  quantity: emissions
  input_dimensions: [flight_type, vehicle_type, greenhouse_gases, emission_scope]
  output_dimensions: [flight_type, vehicle_type, greenhouse_gases, emission_scope]
  unit: kt/a
  input_nodes:
  - id: aviation_mileage
    tags: [non_additive]
    to_dimensions:
    - id: flight_type
    - id: vehicle_type
      categories: [aviation]
  - id: aviation_emission_factors
    tags: [non_additive]
    to_dimensions:
    - id: flight_type
    - id: vehicle_type
      categories: [aviation]
    - id: greenhouse_gases
      categories: [co2_eq]
    - id: emission_scope
      categories: [scope3]
  output_nodes:
  - id: transportation_emissions_outside_city
    from_dimensions:
    - id: flight_type
      flatten: true

- id: aviation_fuel_consumption_per_inhabitant
  name_de: Aviation fuel consumption per inhabitant
  name_en: Aviation fuel consumption per inhabitant
  type: simple.AdditiveNode
  quantity: energy
  unit: kWh/cap/a
  input_dimensions: [energy_carrier]
  output_dimensions: [energy_carrier]
  input_datasets:
  - id: zuerich/aviation_fuel_consumption
  input_dataset_processors: [LinearInterpolation]
  minimum_year: 2010

- id: aviation_fuel_consumption
  name_de: Aviation fuel consumption
  name_en: Aviation fuel consumption
  short_name_de: Flugverkehr
  short_name_en: Aviation
  type: simple.MultiplicativeNode
  quantity: energy
  input_dimensions: [energy_carrier]
  output_dimensions: [energy_carrier]
  unit: GWh/a
  input_nodes:
  - id: population
    tags: [non_additive]
    to_dimensions: []
  - id: aviation_fuel_consumption_per_inhabitant
    tags: [non_additive]
