# TODO Check if there is anything to move to forestry-fi.

# impact_overviews:

# - graph_type: value_of_information
#   cost_node: total_forest_cost
#   impact_node: total_forest_cost
#   cost_unit: kEUR
#   impact_unit: kEUR  # FIXME Make it possible to operate without impact node
#   indicator_unit: kEUR
#   # outcome_dimension: iteration
#   label: Value of forest information

# - graph_type: cost_benefit
#   cost_node: total_forest_cost
#   impact_node: total_forest_cost
#   cost_unit: kEUR
#   impact_unit: kEUR  # FIXME Make it possible to operate without impact node
#   indicator_unit: kEUR
#   outcome_dimension: iteration
#   label: Costs and benefits of the forest



nodes:

- id: net_emissions2
  name: Kokonaispäästöt
  name_en: Net emissions
  description: Suomen kasvihuonekaasujen nettokokonaispäästöt, eli scope 1+2 ja hiilinielut.
    <h3>Hypoteesit</h3> <ul><li>Hakkuiden lisääminen lisää kasvihuonekaasupäästöjä.
    (1)</li> <li>Hakkuiden lisääminen ei vaikuta kasvihuonekaasupäästöihin. (2)</li>
    <li>Löysempi kasvihuonekaasupäästötavoite ei aiheuta haittaa. (3)</li> <li>Suomen
    toimien vaikutukset kasvihuonekaasupäästöihin ovat vähäiset. (4)</li></ul> <h3>Viitteet</h3>
    <ul><li>HS.ymp.2 Krist Savo</li> <li>(1) HS.ymp.1 Vihr Uusimaa</li> <li>HS.ymp.2
    Vihr Uusimaa</li> <li>(2) HS.ymp.1 Perus Uusimaa</li> <li>HS.ymp.2 Perus Uusimaa</li>
    <li>(3) HS.ymp.1 Perus Savo</li> <li>HS.ymp.1 Rkp Uusimaa</li> <li>(4) HS.ymp.2
    Rkp Uusimaa</li> <li>HS.ymp.2 Vihr Savo</li> <li>HS.ymp.2 Kok Savo</li> <li>HS.ymp.2
    Vas Savo</li> <li>(4) HS.ymp.1 Liik Savo</li> <li>HS.ymp.1 Liik Uusimaa</li> <li>HS.ymp.2
    Kok Uusimaa</li> <li>HS.ymp.1 Sdp Savo</li> <li>HS.ymp.1 Sdp Uusimaa</li> <li>HS.ymp.2
    Sdp Uusimaa</li> <li>HS.ymp.1 Kesk Savo</li> <li>HS.ymp.2 Kesk Savo</li></ul>
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt/a
  is_outcome: true
  input_dataset_processors: [LinearInterpolation]

- id: forest_amount_historical
  name: Forest amount, historical
  type: gpc.DatasetNode
  quantity: volume
  unit: m**3
  # input_dimensions: [iteration]
  # output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
    sector: Forest amount
  output_nodes:
  - id: forest_amount
- id: forest_growth
  name: Forest growth
  type: gpc.DatasetNode
  quantity: volume
  unit: m**3/a
  # input_dimensions: [iteration]
  # output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
    sector: Forest growth
  output_nodes:
  - id: forest_amount
    tags: [cumulative]
- id: forest_amount
  name: Forest amount
  type: simple.AdditiveNode
  quantity: volume
  unit: m**3
  # input_dimensions: [iteration]
  # output_dimensions: [iteration]
  output_nodes:
  - id: alternative_forest_use_benefit
    to_dimensions: []
- id: alternative_forest_use_unit_price
  name: Alternative forest use unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/m**3/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
  - id: sector
    value: Alternative forest use unit price, sample
  # - id: multiplier
  #   value: 0.3
  #   unit: dimensionless
  output_nodes:
  - id: alternative_forest_use_benefit
- id: wood_unit_price
  name: Wood unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/m**3
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
    sector: Wood unit price, sample
  output_nodes:
  - id: forest_sales_income
- id: alternative_forest_use_benefit
  name: Alternative forest use benefit
  type: simple.MultiplicativeNode
  quantity: currency
  unit: kEUR/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  output_nodes:
  - id: total_forest_cost
    tags: [arithmetic_inverse]
- id: forest_sales_income
  name: Forest sales income
  type: simple.MultiplicativeNode
  quantity: currency
  unit: kEUR/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  output_nodes:
  - id: total_forest_cost
    tags: [arithmetic_inverse]
- id: forest_carbon_emissions
  name: Forest carbon emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  output_nodes:
  - id: carbon_cost
- id: wood_emission_factor
  name: Wood emission factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: t/m**3
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
    sector: Wood emission factor, sample
  output_nodes:
  - id: forest_carbon_emissions
- id: carbon_unit_price
  name: Carbon unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  input_datasets: [gpc/greentransition_sample]
  params:
  - id: sector
    value: Carbon unit price, sample
  # - id: multiplier
  #   value: 0.1
  #   unit: dimensionless
  output_nodes:
  - id: carbon_cost
- id: carbon_cost
  name: Carbon cost
  type: simple.MultiplicativeNode
  quantity: currency
  unit: kEUR/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  output_nodes:
  - id: total_forest_cost
- id: total_forest_cost
  name: Total forest cost
  type: simple.AdditiveNode
  quantity: currency
  unit: kEUR/a
  is_outcome: true
  input_dimensions: [iteration]
  output_dimensions: [iteration]
- id: total_forest_cost_expectation
  name: Total forest cost expectation
  type: simple.AdditiveNode
  quantity: currency
  unit: kEUR/a
  input_dimensions: [iteration]
  output_dimensions: [iteration]
  input_nodes:
  - id: total_forest_cost
    tags: [expectation]

# ------------------ Etelä-Suomen biodiversiteetti --------------

- id: protected_forest_area
  name: Suojellun metsäluonnon pinta-ala Etelä-Suomessa
  type: values.AssociationNode
  quantity: area
  unit: ha
  historical_values: [[2010, 200], [2023, 100]]

- id: rich_forest_biodiversity_area
  name: Rikkaan metsäluonnon pinta-ala Etelä-Suomessa
  type: values.AssociationNode
  quantity: area
  unit: ha
  historical_values: [[2010, 200], [2023, 100]]
  input_nodes: [protected_forest_area]

- id: forest_biodiversity_channels
  name: Rikkaan metsäluonnon yhdyskäytävät Etelä-Suomessa
  type: values.AssociationNode
  quantity: area
  unit: ha
  historical_values: [[2010, 200], [2023, 100]]

- id: forest_grazing
  name: Metsälaidunnus
  type: values.AssociationNode
  quantity: area
  unit: ha
  historical_values: [[2010, 0.20], [2023, 0.50]]

- id: number_of_endangered_species
  name: Uhanalaisten lajien määrä
  description: 'Punaisen kirjan mukainen uhanalaisuusluokitus. Valitettavasti vain
    vuoden 2019 tulokset ovat ladattavissa avoimena datana, joten aikasarjoja ei ole
    mahdollista piirtää suoraan datan perusteella. Kuitenkin yksittäinenkin aikapiste
    kertoo nykytilanteesta. Ehkä hyödyllisin analyysi olisi laskea uhanalaisten lajien
    määrät elinympäristöittäin. Tähän kuvaustekstiin voisi ilmoittaa samat tiedot
    prosenttiosuuksina kaikista elinympäristön lajeista. <h3>Viitteet</h3> Ympäristöministeriö
    & Suomen ympäristökeskus (2019). Suomen lajien uhanalaisuus – Punainen kirja 2019:
    tiedostolataus (versio 2). Ladattu osoitteesta https://punainenkirja.laji.fi/publications
    2024-06-16.'
  type: values.AssociationNode
  quantity: number
  unit: pcs
  historical_values: [[2010, 50], [2023, 150]]
  input_nodes:
  - id: rich_forest_biodiversity_area
  - id: forest_biodiversity_channels
  - id: forest_grazing

- id: forest_protection_unit_cost
  name: Metsien suojelun yksikköhinta
  description: Metsien suojelun kustannuksiin sisältyvät suorat tuet tai lunastushinnat
    maanomistajalle sekä vaihtoehtoiskustannukset eli maankäytön muutoksesta syntyvä
    sadon väheneminen.
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/ha/a
  historical_values: [[2010, 100], [2023, 120]]

- id: forest_protection_cost
  name: Metsien suojelun kustannus
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes:
  - id: protected_forest_area
  - id: forest_protection_unit_cost

# ---------------------------- Suomen metsänielukeskustelu

- id: cumulative_carbon_emissions
  name: Kumulatiivinen hiilipäästö
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt
  input_nodes:
  - id: net_emissions2
    tags: [cumulative]

# - id: carbon_budget
#   name: Suomen hiilibudjetti
#   type: simple.AdditiveNode
#   quantity: emissions
#   unit: Mt
#   input_nodes:
#   - cumulative_carbon_emissions
#   - amount_of_wood_in_forests
#   goals:
#   - label: Hiilibudjetin tavoite
#     default: true
#     values:
#     - year: 2035
#       value: 1000

- id: pulp_production_capacity
  name: Sellun valmistuskapasiteetti Suomessa
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  historical_values: [[2000, 29], [2023, 69.2]]
  input_dataset_processors: [LinearInterpolation]

- id: pulp_production
  name: Sellun valmistusmäärä Suomessa
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  input_dataset_processors: [LinearInterpolation]
  input_nodes: [pulp_production_capacity]
  output_nodes: [forest_cuts_in_finland]

- id: high_price_wood_production
  name: Korkean jalostusasteen puutuotteiden valmistusmäärä Suomessa
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  historical_values: [[2000, 90], [2023, 50]]
  input_dataset_processors: [LinearInterpolation]
  output_nodes: [forest_cuts_in_finland]

- id: forest_cuts_in_finland
  name: Metsänhakkuut Suomessa
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a

- id: pulp_price
  name: Sellun hinta
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2000, 1000], [2023, 900]]
  input_dataset_processors: [LinearInterpolation]

- id: high_price_wood_price
  name: Korkean jalostusasteen puutuotteiden hinta
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2000, 4000], [2023, 4000]]
  input_dataset_processors: [LinearInterpolation]

- id: pulp_sales
  name: Sellun myyntivoitto
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes: [pulp_production, pulp_price]

- id: high_price_wood_sales
  name: Korkean jalostusasteen puutuotteiden myyntivoitto
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes: [high_price_wood_production, high_price_wood_price]

- id: total_forest_sales
  name: Metsäteollisuuden tuotto
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_nodes: [pulp_sales, high_price_wood_sales]

- id: amount_of_wood_in_forests
  name: Suomen metsien hiilivarasto
  type: costs.InternalGrowthNode
  quantity: mass
  unit: Mt
  input_nodes: [forest_cuts_in_finland]
  historical_values: [[2000, -3000], [2023, -3200]]
  input_dataset_processors: [LinearInterpolation]
  params:
  - id: annual_change
    value: 4.1875  # Year 2021: 134 Mt growth, 3200 Mt Wood storage in forests.
    unit: '%'

- id: pulp_industry_emissions
  name: Selluteollisuuden päästöt
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_nodes: [pulp_production]

- id: high_price_wood_industry_emissions
  name: Korkean jalostusasteen puuteollisuuden päästöt
  type: simple.FixedMultiplierNode
  quantity: emissions
  unit: Mt/a
  input_nodes: [high_price_wood_production]
  params:
  - id: multiplier
    value: 0.3

- id: forest_industry_emissions
  name: Metsien päästöt
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_nodes: [pulp_industry_emissions, high_price_wood_industry_emissions, carbon_capture_and_storage]
  # output_nodes: [agriculture_emissions]
  output_nodes: [net_emissions2]

# - id: biodiversity_in_forests
#   name: Suomen metsien biodiversiteetti
#   type: simple.AdditiveNode
#   quantity: mass
#   unit: t
#   input_nodes: [amount_of_wood_in_forests]
#   historical_values: [[2000, 5000], [2023, 4000]]

- id: carbon_capture_and_storage
  name: Hiilidioksidin talteenotto
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  historical_values: [[2000, 0], [2023, 0]]

- id: carbon_capture_price
  name: Hiilidioksidin talteenoton hinta
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2000, 400], [2023, 200]]
  input_dataset_processors: [LinearInterpolation]

- id: carbon_capture_cost
  name: Hiilidioksidin talteenoton kustannus
  type: simple.MultiplicativeNode
  quantity: unit_price
  unit: MEUR/a
  input_nodes: [carbon_capture_and_storage, carbon_capture_price]
  output_nodes: [pulp_sales]

- id: forestry_emissions_utility
  name: Metsäteollisuuden päästöjen utiliteetti
  type: simple.FixedMultiplierNode
  quantity: utility
  unit: Ut/a
#  input_nodes: [agriculture_emissions]
  input_nodes: [forest_industry_emissions]
  output_nodes: [forestry_utility]
  params:
  - id: multiplier
    value: 1
    unit: Ut/kt

- id: forestry_financial_utility
  name: Metsäteollisuuden tuottojen utiliteetti
  type: simple.FixedMultiplierNode
  quantity: utility
  unit: Ut/a
  input_nodes: [total_forest_sales]
  output_nodes: [forestry_utility]
  params:
  - id: multiplier
    value: 1
    unit: Ut/kEUR

# - id: forestry_biodiversity_utility
#   name: Metsäteollisuuden biodiversiteetin utiliteetti
#   type: simple.FixedMultiplierNode
#   quantity: utility
#   unit: Ut/a
#   input_nodes: [biodiversity_in_forests]
#   output_nodes: [forestry_utility]
#   params:
#   - id: multiplier
#     value: 1
#     unit: Ut/a/kt

- id: nature_protection_commitment_utility
  name: Luonnonsuojelusitoumusten toteuttamisen utiliteetti
  type: simple.FixedMultiplierNode
  quantity: utility
  unit: Ut/a
  input_nodes:
  - id: protected_forest_area
    tags: [non_additive]
  output_nodes: [forestry_utility]
  params:
  - id: multiplier
    value: 1
    unit: Ut/a/ha

- id: southern_finland_biodiversity_utility
  name: Etelä-Suomen biodiversiteetin utiliteetti
  type: simple.FixedMultiplierNode
  quantity: utility
  unit: Ut/a
  input_nodes:
  - id: number_of_endangered_species
    tags: [non_additive]
  output_nodes: [forestry_utility]
  params:
  - id: multiplier
    value: 1
    unit: Ut/a/pcs

- id: forestry_utility
  name: Metsien utiliteetti
  type: simple.AdditiveNode
  quantity: utility
  unit: Ut/a

# - id: uncertain_node
#   name: Uncertain node
#   description: An uncertain node that has a non-linear effect on the effects of the
#     test action. This node may get values 0 or -80 EUR/a.
#   type: simple.AdditiveNode
#   quantity: currency
#   unit: EUR/a
#   output_dimensions: [iteration]
#   historical_values: [
#     [2010, '0 - 80'], # uniform
#     [2011, '[1, 2]'], # problist
#     [2012, '1-2'], # uniform
#     [2013, '1-100 (log)'], # loguniform
#     [2014, '0+-2'], # normal +- sd
#     [2015, '3 (2.7-3.3)'], # normal (95 % CI))
#     [2016, '3+-10(log)'], # lognormal (mean +- df)
#     [2017, 'Beta(1,4)'],
#     [2018, 'Poisson(4)'],
#     [2019, 'Exponential(6)']]
#   input_dataset_processors: [LinearInterpolation]

# - id: tech1
#   name: Technical node 1
#   description: This is just a technical node that allows a certain action affect an
#     uncertain node.
#   type: simple.AdditiveNode
#   quantity: currency
#   unit: dimensionless
#   output_dimensions: [iteration]
#   historical_values: [[2010, '[1, 2, 3]']]
#   input_dataset_processors: [LinearInterpolation]

# - id: tech2
#   name: Technical node 2
#   description: This is just a technical node that allows a certain action affect an
#     uncertain node.
#   type: simple.MultiplicativeNode
#   quantity: currency
#   unit: EUR/a
#   input_dimensions: [iteration]
#   output_dimensions: [iteration]
#   input_nodes:
#   - id: tech1
#     tags: [non_additive]
#   - id: uncertain_node
#     tags: [non_additive]

# - id: uncertain_outcome
#   name: Uncertain outcome
#   description: This node takes the absolute value of the technical node 2. This is
#     the reason for non-linearity in the outcome.
#   type: simple.AdditiveNode
#   quantity: currency
#   unit: EUR/a
#   input_dimensions: [iteration]
#   output_dimensions: [iteration]
#   is_outcome: true
#   input_nodes:
#   - id: tech2
#     tags: [absolute]

actions:

# ------------ Finnish environmental policy --------------

# - id: test_action
#   name: Test action for value of information
#   description: This action may improve or worsen situation, depending on uncertain
#     circumstances.
#   type: simple.AdditiveAction
#   quantity: ratio
#   unit: dimensionless
#   group: draft
#   historical_values: [[2010, 0], [2023, 0]]
#   forecast_values: [[2024, 1], [2035, 1]]
#   input_dataset_processors: [LinearInterpolation]
#   output_nodes:
#   - id: tech2
#     tags: [non_additive]
#     to_dimensions: []

- id: sell_forest
  name: Sell forest
  type: gpc.DatasetAction
  quantity: volume
  unit: m**3/a
  group: draft
  # input_dimensions: [iteration]
  # output_dimensions: [iteration]
  input_datasets:
  - id: gpc/greentransition_sample
    forecast_from: 2025
  params:
    sector: Sell forest
  output_nodes:
  - id: forest_amount
    tags: [arithmetic_inverse, cumulative]
    to_dimensions: []
  - id: forest_sales_income
    to_dimensions: []
  - id: forest_carbon_emissions
    to_dimensions: []

- id: forest_grazing_support
  name: Metsälaidunnuksen tuki
  description: Tähän pitäisi kerätä tietoa siitä, kuinka paljon tukea metsälaidunnukselle
    annetaan nykyään, ja mikä on tilanne hallituksen säästötoimien jälkeen. Samoin
    pitäisi kuvata sitä, miten paljon laidunnus lisääntyy tukimäärän suurentuessa
    (€/ha). Yhteys tuskin on lineaarinen, vaan jokin määrä laidunnusta tapahtuu ilman
    tukiakin, mutta liian pieni hehtaarituki ei lisää laidunnusta lainkaan.
  type: simple.CumulativeAdditiveAction
  quantity: area
  unit: ha
  group: forestry
  forecast_values: [[2024, 0], [2025, 100]]
  output_nodes: [forest_grazing]

- id: ambition_of_forest_protection
  name: Metsiensuojelun kunnianhimon määrä
  description: Kunnianhimon määrää mitataan tässä suojeltujen hehtaarien määrällä.
    Osa suojelusta tapahtuu ilman valtion toimiakin, ja se ei näy tässä toimenpiteessä
    vaan trendinä solmussa Suojellun metsäluonnon pinta-ala Etelä-Suomessa. Tähän
    tarvittaisiin tieto kustannustehokkuudesta eli paljonko hehtaarin suojelu maksaa.
  type: simple.CumulativeAdditiveAction
  quantity: area
  unit: ha
  group: forestry
  forecast_values: [[2024, 0], [2026, 100]]
  output_nodes: [protected_forest_area]

- id: block_the_pipes
  name: Tulpataan teollisuuden piiput
  type: simple.CumulativeAdditiveAction
  quantity: mass
  unit: kt/a
  group: forestry
  forecast_values: [[2024, 0], [2028, -70], [2031, -700]] # Government spends 140 M€, cost 200 EUR/t
  output_nodes: [carbon_capture_and_storage]

- id: kajaani_pulp_mill  # 600 kt/a pulp https://www.hs.fi/talous/art-2000010325037.html
  name: Rakennetaan Kajaanin sellutehdas
  type: simple.CumulativeAdditiveAction
  quantity: unit_price
  unit: kt/a
  group: forestry
  forecast_values: [[2024, 0], [2028, 0], [2029, 1760]]  # 50 % yield C6H12O6 180 g/mol in wood results in 6 CO2 264 g/mol --> 600 kt / 50 % * 264 / 180 = 1760 kt
  input_dataset_processors: [LinearInterpolation]
  output_nodes: [pulp_production_capacity]
