# Data: https://docs.google.com/spreadsheets/d/12_McEL0wQWS0G-0zBYEfnPOBdkdpRd31__qwpqYZ0ZE/edit?gid=0#gid=0
dimensions:

- id: stakeholder
  label_fi: Sidosryhmä
  label: Stakeholder
  categories:
  - id: true_finns
    label: True Finns
  - id: the_greens
    label: The Greens

- id: node
  label_en: Node
  categories:
  - id: car_traffic_emissions
    label_en: Car traffic emissions
  - id: purchase_power_of_the_poor
    label_en: Purchase power of the poor
  - id: congestion_charge_with_redistribution
    label_en: Congestion charge with redistribution

nodes:

- id: car_traffic_emissions
  name: Car traffic emissions (fact)
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_datasets:
  - id: sunnydale/congestion_charge
    tags: [baseline]
    column: car_traffic_emissions_emissions

- id: purchase_power_of_the_poor
  name: Purchase power of the poor (fact)
  type: generic.GenericNode
  quantity: currency
  unit: EUR/month
  input_datasets:
  - id: sunnydale/congestion_charge
    tags: [baseline]
    column: purchase_power_of_the_poor_currency

- id: total_congestion_charge_utility
  name: Total congestion charge utility
  type: simple.AdditiveNode
  quantity: utility
  unit: dimensionless
  is_outcome: true
  input_dimensions: [stakeholder]
  output_dimensions: [stakeholder]

- id: congestion_charge_emissions_utility
  name: Congestion charge emissions utility (value)
  type: generic.WeightedSumNode
  quantity: utility
  unit: dimensionless
  input_dimensions: [stakeholder]
  output_dimensions: [stakeholder]
  input_datasets:
  - id: sunnydale/congestion_charge_utility
    tags: [input_node_weights]
  input_nodes:
  - id: car_traffic_emissions
    tags: [additive]
    to_dimensions: []
  output_nodes:
  - total_congestion_charge_utility
  params:
  - id: operations
    value: multiply,add_with_weights,select_variant
  - id: categories
    value: stakeholder:true_finns,the_greens
  - id: selected_number
    ref: selected_number

- id: congestion_charge_equity_utility
  name: Congestion charge equity utility (value)
  type: generic.WeightedSumNode
  quantity: utility
  unit: dimensionless
  input_dimensions: [stakeholder]
  output_dimensions: [stakeholder]
  input_datasets:
  - id: sunnydale/congestion_charge_utility
    tags: [input_node_weights]
  input_nodes:
  - id: purchase_power_of_the_poor
    tags: [additive]
    to_dimensions: []
  output_nodes:
  - total_congestion_charge_utility
  params:
  - id: operations
    value: multiply,add_with_weights,select_variant
  - id: categories
    value: stakeholder:true_finns,the_greens
  - id: selected_number
    ref: selected_number

- id: inherent_action_utility
  name: Inherent action utility (team)
  type: generic.WeightedSumNode
  quantity: utility
  unit: dimensionless
  input_dimensions: [stakeholder]
  output_dimensions: [stakeholder]
  input_datasets:
  - id: sunnydale/congestion_charge
    column: inherent_action_utility_unit_price
    tags: [input_node_weights]
  output_nodes:
  - total_congestion_charge_utility
  params:
  - id: operations
    value: multiply,add_with_weights,select_variant
  - id: categories
    value: stakeholder:true_finns,the_greens
  - id: selected_number
    ref: selected_number

actions:

- id: congestion_charge_with_redistribution
  name_en: Congestion charge with redistribution
  description_en: This policy is about setting a congestion charge in the city center
    to reduce car driving. This policy has been extensively studied and it is known
    to be effective with fairly small social costs. However, it does affect disproportionally
    those poor people who have to move with an own car. Therefore, this policy includes
    the redistribution of the tax money back to citizens with an equal per-capitta
    amount. This overcompensates losses to poor people, because they typically spend
    less money on driving in absolute terms.
  type: simple.AdditiveAction
  group: congestion_charge
  input_dataset_processors: [LinearInterpolation]
  input_datasets:
  - id: sunnydale/congestion_charge_action
    tags: [baseline]
    forecast_from: 2025
  output_metrics:
  - id: unit_price
    quantity: unit_price
    unit: EUR/vkm
  - id: emissions
    quantity: emissions
    unit: kt/a
  - id: currency
    quantity: currency
    unit: EUR/month
  output_nodes:
  - id: car_traffic_emissions
    metrics: [emissions]
  - id: purchase_power_of_the_poor
    metrics: [currency]
  - id: inherent_action_utility
    metrics: [unit_price]
    tags: [additive]
    to_dimensions: []
