from typing import TypeVar

from django.db.models import Manager, QuerySet, Model


class MultilingualQuerySet(QuerySet):
    def annotate(self, *args, **kwargs): ...
    def create(self, **kwargs): ...
    def order_by(self, *field_names): ...
    def __reduce__(self): ...


T = TypeVar('T', bound=Model)

class MultilingualManager(Manager[T]): ...
