# Generated by Django 3.1.8 on 2021-05-25 10:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.core.fields.RichTextField()),
                ('node', models.CharField(choices=[('net_emissions', 'Kokonaispäästöt (scope 2)'), ('transportation_emissions', 'Liikenteen päästöt'), ('car_emissions', 'Henkilöautot'), ('van_emissions', 'Pakettiautot'), ('bus_emissions', 'Linja-autot'), ('truck_emissions', 'Kuorma-autot'), ('motorbike_emissions', 'Moottoripyörät yms.'), ('local_train_emissions', 'Lähijunat'), ('tram_emissions', 'Raitiotiet'), ('building_heating_emissions', 'Rakennusten lämmityksen päästöt'), ('separate_heating_emissions', 'Erillislämmitys'), ('oil_heating_emissions', 'Öljylämmitys'), ('gas_heating_emissions', 'Kaasulämmitys'), ('electric_heating_emissions', 'Sähkölämmitys'), ('geothermal_heating_emissions', 'Maalämpö'), ('direct_electric_heating_emissions', 'Suorasähkö'), ('industry_emissions', 'Teollisuuden ja työkoneiden päästöt'), ('waste_treatment_emissions', 'Jätehuollon päästöt'), ('solid_waste_treatment_emissions', 'Kiinteän jätteen käsittelyn päästöt'), ('waste_water_treatment_emissions', 'Jäteveden puhdistuksen päästöt'), ('agriculture_emissions', 'Maatalouden päästöt'), ('cattle_digestion_emissions', 'Eläinten ruoansulatus'), ('manure_treatment_emissions', 'Lannankäsittely'), ('field_crops_emissions', 'Peltoviljelyn päästöt'), ('population', 'Väestö'), ('district_heating_emissions', 'Kaukolämpö'), ('district_heating_consumption', 'Kaukolämmön kulutus'), ('district_heating_emission_factor', 'Kaukolämmön päästökerroin'), ('electricity_consumption_per_capita', 'Sähkönkulutus asukasta kohti'), ('electricity_consumption_other', 'Muu sähkönkulutus'), ('electricity_consumption', 'Sähkönkulutus'), ('electricity_production_emission_factor', 'Sähköntuotannon päästökerroin'), ('electricity_consumption_emissions', 'Sähkön kulutuksen päästöt'), ('naistenlahti3', 'Naistenlahti 3 -biovoimalaitos'), ('other_renewable_district_heating', 'Kaukolämmön tuotannossa lisätään uusiutuvaa energiaa')], max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
