# Generated by Django 3.2.4 on 2021-06-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_add_content_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodecontent',
            name='instance',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='pages.instancecontent'),
        ),
    ]
