# Generated by Django 3.1.8 on 2021-06-28 17:31

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_nodecontent_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancecontent',
            name='lead_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Lead paragraph'),
        ),
        migrations.AddField(
            model_name='instancecontent',
            name='lead_title',
            field=models.CharField(default='', blank=True, max_length=100, verbose_name='Lead title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='instancecontent',
            name='identifier',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Instance identifier'),
        ),
    ]
