# Generated by Django 3.2.13 on 2022-05-31 20:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_add_remove_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlistpage',
            name='lead_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Lead paragraph'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outcomepage',
            name='lead_paragraph',
            field=wagtail.core.fields.RichTextField(blank=True, default='', verbose_name='Lead paragraph'),
            preserve_default=False,
        ),
    ]
