# Generated by Django 4.1.12 on 2023-10-16 14:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('pages', '0007_make_fields_non_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceRootPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('i18n', models.JSONField(blank=True, null=True)),
                ('show_in_footer', models.BooleanField(default=False, help_text='Should the page be shown in the footer?', verbose_name='show in footer')),
                ('body', wagtail.fields.StreamField([('outcome', wagtail.blocks.StructBlock([('outcome_node', wagtail.blocks.ChooserBlock())]))], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('i18n', models.JSONField(blank=True, null=True)),
                ('show_in_footer', models.BooleanField(default=False, help_text='Should the page be shown in the footer?', verbose_name='show in footer')),
                ('body', wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraph'))], blank=True, null=True, use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='actionlistpage',
            name='default_sort_order',
            field=models.CharField(choices=[('standard', 'Standard'), ('impact', 'Impact'), ('cum_impact', 'Cumulative impact')], default='standard', max_length=40),
        ),
        migrations.AddField(
            model_name='actionlistpage',
            name='show_cumulative_impact',
            field=models.BooleanField(default=True, verbose_name='Show cumulative impact'),
        ),
    ]
