# Generated by Django 4.1.12 on 2023-10-17 11:04

from django.db import migrations, models
import nodes.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_implement_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlistpage',
            name='show_action_comparison',
            field=models.BooleanField(default=True, verbose_name='Show action comparison'),
        ),
        migrations.AddField(
            model_name='actionlistpage',
            name='show_only_municipal_actions',
            field=models.BooleanField(default=False, verbose_name='Show action comparison'),
        ),
        migrations.AlterField(
            model_name='instancerootpage',
            name='body',
            field=wagtail.fields.StreamField([('outcome', wagtail.blocks.StructBlock([('outcome_node', nodes.blocks.NodeChooserBlock(label='Outcome node'))]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock(label='Paragraph')), ('outcome', wagtail.blocks.StructBlock([('outcome_node', nodes.blocks.NodeChooserBlock(label='Outcome node'))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.DeleteModel(
            name='NodePage',
        ),
    ]
