# Generated by Django 4.2.7 on 2024-04-24 16:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


def create_instance_site_content(apps, schema_editor):
    InstanceConfig = apps.get_model('nodes', 'InstanceConfig')
    InstanceSiteContent = apps.get_model('pages', 'InstanceSiteContent')

    for instance in InstanceConfig.objects.all():
        InstanceSiteContent.objects.create(instance=instance)


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0024_add_node_is_visible'),
        ('pages', '0009_new_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlistpage',
            name='show_only_municipal_actions',
            field=models.BooleanField(default=False, verbose_name='Show only municipal actions'),
        ),
        migrations.CreateModel(
            name='InstanceSiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_content', wagtail.fields.StreamField([('title', wagtail.blocks.RichTextBlock(label='Title')), ('paragraph', wagtail.blocks.RichTextBlock(label='Introductory content to show in the UI'))], blank=True, use_json_field=True, verbose_name='Introductory content')),
                ('instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='site_content', to='nodes.instanceconfig')),
            ],
            options={
                'verbose_name': 'Site content',
                'verbose_name_plural': 'Site contents',
            },
        ),
        migrations.RunPython(create_instance_site_content),
    ]
