# Generated by Django 5.2.4 on 2025-08-28 07:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_dashboardpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='dashboard_cards',
            field=wagtail.fields.StreamField([('card', 17)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('nodes.blocks.NodeChooserBlock', (), {'required': True}), 4: ('wagtail.blocks.IntegerBlock', (), {'min_value': 0, 'required': False}), 5: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 5)]], {}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 5), ('scenario_id', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Break down the given dimension into its categories. If empty, break down into input nodes.', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('dimension_id', 9)]], {'help_text': 'Break down the value into its components', 'label': 'Category breakdown'}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('scenario_id', 7)]], {'help_text': 'Visualize the impact of actions in a scenario', 'label': 'Action impact'}), 12: ('wagtail.blocks.StreamBlock', [[('goal_progress_bar', 6), ('reference_progress_bar', 6), ('current_progress_bar', 6), ('scenario_progress_bar', 8), ('category_breakdown', 10), ('action_impact', 11)]], {}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 14: ('wagtail.blocks.CharBlock', (), {'label': 'Content', 'required': False}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL'}), 16: ('wagtail.blocks.StructBlock', [[('title', 13), ('content', 14), ('link_url', 15)]], {}), 17: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('node_config', 3), ('goal_index', 4), ('visualizations', 12), ('call_to_action', 16)]], {})}),
        ),
    ]
