# Generated by Django 5.2.4 on 2025-09-10 08:32

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_dashboardpage_dashboard_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='lead_paragraph',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Lead paragraph'),
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='lead_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lead title'),
        ),
    ]
