# Generated by Django 5.2.4 on 2025-10-14 14:31

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_dashboardpage_lead_paragraph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlistpage',
            name='show_in_additional_links',
            field=models.BooleanField(default=False, help_text='Should the page be shown in the additional links?', verbose_name='show in additional links'),
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='show_in_additional_links',
            field=models.BooleanField(default=False, help_text='Should the page be shown in the additional links?', verbose_name='show in additional links'),
        ),
        migrations.AddField(
            model_name='instancerootpage',
            name='show_in_additional_links',
            field=models.BooleanField(default=False, help_text='Should the page be shown in the additional links?', verbose_name='show in additional links'),
        ),
        migrations.AddField(
            model_name='outcomepage',
            name='show_in_additional_links',
            field=models.BooleanField(default=False, help_text='Should the page be shown in the additional links?', verbose_name='show in additional links'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='show_in_additional_links',
            field=models.BooleanField(default=False, help_text='Should the page be shown in the additional links?', verbose_name='show in additional links'),
        ),
        migrations.AlterField(
            model_name='instancerootpage',
            name='body',
            field=wagtail.fields.StreamField([('outcome', 1), ('dashboard', 19)], block_lookup={0: ('nodes.blocks.NodeChooserBlock', (), {'label': 'Outcome node'}), 1: ('wagtail.blocks.StructBlock', [[('outcome_node', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('nodes.blocks.NodeChooserBlock', (), {'required': True}), 6: ('wagtail.blocks.IntegerBlock', (), {'min_value': 0, 'required': False}), 7: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3), ('chart_label', 2), ('color', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': True}), 10: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3), ('chart_label', 2), ('color', 7), ('scenario_id', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Break down the given dimension into its categories. If empty, break down into input nodes.', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('title', 2), ('dimension_id', 11)]], {'help_text': 'Break down the value into its components', 'label': 'Category breakdown'}), 13: ('wagtail.blocks.StructBlock', [[('title', 2), ('scenario_id', 9)]], {'help_text': 'Visualize the impact of actions in a scenario', 'label': 'Action impact'}), 14: ('wagtail.blocks.StreamBlock', [[('goal_progress_bar', 8), ('reference_progress_bar', 8), ('current_progress_bar', 8), ('scenario_progress_bar', 10), ('category_breakdown', 12), ('action_impact', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 16: ('wagtail.blocks.CharBlock', (), {'label': 'Content', 'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL'}), 18: ('wagtail.blocks.StructBlock', [[('title', 15), ('content', 16), ('link_url', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3), ('image', 4), ('node_config', 5), ('goal_index', 6), ('visualizations', 14), ('call_to_action', 18)]], {})}),
        ),
    ]
