# Generated by Django 5.2.4 on 2025-10-21 08:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_actionlistpage_show_in_additional_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancerootpage',
            name='body',
            field=wagtail.fields.StreamField([('outcome', 1)], block_lookup={0: ('nodes.blocks.NodeChooserBlock', (), {'label': 'Outcome node'}), 1: ('wagtail.blocks.StructBlock', [[('outcome_node', 0)]], {})}),
        ),
    ]
