# Generated by Django 6.0.3 on 2026-04-16 10:35

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_instancerootpage_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancesitecontent',
            options={'ordering': ['instance', 'id'], 'verbose_name': 'Site content', 'verbose_name_plural': 'Site contents'},
        ),
        migrations.AlterField(
            model_name='instancerootpage',
            name='body',
            field=wagtail.fields.StreamField([('outcome', 1), ('framework_landing', 6)], block_lookup={0: ('nodes.blocks.NodeChooserBlock', (), {'label': 'Outcome node'}), 1: ('wagtail.blocks.StructBlock', [[('outcome_node', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Heading'}), 3: ('wagtail.blocks.RichTextBlock', (), {'label': 'Body', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Call-to-action button label', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'label': 'Call-to-action button URL', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('heading', 2), ('body', 3), ('cta_label', 4), ('cta_url', 5)]], {})}),
        ),
    ]
