# Generated by Django 6.0.3 on 2026-04-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_alter_instancerootpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlistpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional override for how this page appears in the menu. Defaults to the page title.', max_length=100, verbose_name='menu label'),
        ),
        migrations.AddField(
            model_name='dashboardpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional override for how this page appears in the menu. Defaults to the page title.', max_length=100, verbose_name='menu label'),
        ),
        migrations.AddField(
            model_name='instancerootpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional override for how this page appears in the menu. Defaults to the page title.', max_length=100, verbose_name='menu label'),
        ),
        migrations.AddField(
            model_name='outcomepage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional override for how this page appears in the menu. Defaults to the page title.', max_length=100, verbose_name='menu label'),
        ),
        migrations.AddField(
            model_name='staticpage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='Optional override for how this page appears in the menu. Defaults to the page title.', max_length=100, verbose_name='menu label'),
        ),
    ]
