# Generated by Django 5.2 on 2025-06-17 13:32

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import modelcluster.fields
import modeltrans.fields
import uuid
import wagtail.fields
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('user_editable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Namespace',
                'verbose_name_plural': 'Namespaces',
            },
        ),
        migrations.CreateModel(
            name='OrganizationClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(editable=False, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('last_modified_time', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
            ],
            options={
                'verbose_name': 'Organization class',
                'verbose_name_plural': 'Organization classes',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='A primary name, e.g. a legally recognized name', max_length=255)),
                ('abbreviation', models.CharField(blank=True, help_text='A simplified short version of name for the general public', max_length=50, verbose_name='Short name')),
                ('internal_abbreviation', models.CharField(blank=True, help_text='An internally used abbreviation', max_length=50, verbose_name='Internal abbreviation')),
                ('distinct_name', models.CharField(editable=False, help_text='A distinct name for this organization (generated automatically)', max_length=400, null=True)),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='description')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('founding_date', models.DateField(blank=True, help_text='A date of founding', null=True)),
                ('dissolution_date', models.DateField(blank=True, help_text='A date of dissolution', null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='The time at which the resource was created')),
                ('last_modified_time', models.DateTimeField(auto_now=True, help_text='The time at which the resource was updated')),
                ('primary_language', models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('cs', 'Czech'), ('da', 'Danish'), ('pl', 'Polish'), ('lv', 'Latvian'), ('es-US', 'Spanish (United States)'), ('el', 'Greek')], max_length=8, verbose_name='primary language')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('i18n', modeltrans.fields.TranslationField(fields=('name', 'abbreviation'), required_languages=(), virtual_fields=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_organizations', to=settings.AUTH_USER_MODEL)),
                ('classification', models.ForeignKey(blank=True, help_text='An organization category, e.g. committee', null=True, on_delete=django.db.models.deletion.PROTECT, to='orgs.organizationclass', verbose_name='Classification')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='OrganizationIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orgs.namespace')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='orgs.organization')),
            ],
            options={
                'verbose_name': 'Organization identifier',
                'verbose_name_plural': 'Organization identifiers',
            },
        ),
    ]
