# Generated by Django 5.2 on 2025-06-17 13:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMetadataAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_metadata_admins', to='orgs.organization', verbose_name='organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'Organization metadata admin',
                'verbose_name_plural': 'Organization metadata admins',
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='metadata_admins',
            field=models.ManyToManyField(blank=True, related_name='metadata_adminable_organizations', through='orgs.OrganizationMetadataAdmin', to='people.person'),
        ),
    ]
