# Generated by Django 5.2 on 2025-07-04 11:19

import kausal_common.i18n.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_organizationmetadataadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='primary_language_lowercase',
            field=models.CharField(default=kausal_common.i18n.helpers.get_default_language_lowercase, max_length=8),
        ),
        migrations.AlterField(
            model_name='organization',
            name='primary_language',
            field=models.CharField(choices=kausal_common.i18n.helpers.get_supported_languages, max_length=8, verbose_name='primary language'),
        ),
    ]
