# Generated by Django 5.2.4 on 2025-09-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_alter_organization_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='internal_abbreviation',
        ),
    ]
