# Generated by Django 6.0.2 on 2026-04-02 14:27

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0006_remove_organization_internal_abbreviation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="Short version or abbreviation of the organization name to be displayed when it is not necessary to show the full name",
                max_length=50,
                null=True,
                verbose_name="short name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                help_text="An organization category (e.g., committee)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orgs.organizationclass",
                verbose_name="Classification",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="The time at which the object for this organization was created",
                verbose_name="created at",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dissolution_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="dissolution date"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="distinct_name",
            field=models.CharField(
                editable=False,
                help_text="A distinct name for this organization (generated automatically)",
                max_length=400,
                null=True,
                verbose_name="distinct name",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="founding_date",
            field=models.DateField(blank=True, null=True, verbose_name="founding date"),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_modified_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_organizations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="updated by",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="last_modified_time",
            field=models.DateTimeField(
                auto_now=True,
                help_text="The time at which the object for this organization was last updated",
                verbose_name="updated at",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="location"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name",
            field=models.CharField(
                help_text="Full name of the organization",
                max_length=255,
                verbose_name="name",
            ),
        ),
    ]
