# Generated by Django 5.0.7 on 2024-07-19 12:48

import frameworks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='public_base_fqdn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frameworkconfig',
            name='token',
            field=models.CharField(default=frameworks.models.create_random_token, max_length=50),
        ),
        migrations.AlterField(
            model_name='framework',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='frameworkdimension',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='frameworkdimensioncategory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='measuretemplate',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AddConstraint(
            model_name='measuredatapoint',
            constraint=models.UniqueConstraint(fields=('measure', 'year'), name='unique_measure_year_datapoints'),
        ),
    ]
