# Generated by Django 5.0.7 on 2024-07-23 12:44

import django.contrib.postgres.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frameworks", "0003_framework_result_excel_node_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="frameworkconfig",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="framework",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="frameworkdimension",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="frameworkdimensioncategory",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="measuretemplate",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="uuid",
            field=models.UUIDField(
                db_default=django.contrib.postgres.functions.RandomUUID(),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
