# Generated by Django 5.1.3 on 2024-11-25 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("frameworks", "0006_frameworkconfig_organization_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="framework",
            name="viewer_group",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viewer_for_framework",
                to="auth.group",
            ),
        ),
    ]
