# Generated by Django 5.1.4 on 2024-12-13 10:04

import django.core.serializers.json
import django_pydantic_field.fields
import frameworks.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0008_frameworkconfig_target_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='defaults',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=frameworks.models.FrameworkDefaults, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=frameworks.models.FrameworkDefaults),
        ),
    ]
