# Generated by Django 5.2 on 2025-06-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0012_measuretemplate_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='max_total',
            field=models.FloatField(null=True),
        ),
    ]
