# Generated by Django 5.2 on 2025-06-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0013_section_max_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuretemplate',
            name='include_in_progress_tracker',
            field=models.BooleanField(default=False),
        ),
    ]
