# Generated by Django 5.2.4 on 2025-10-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0016_section_min_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='influencing_measure_templates',
            field=models.ManyToManyField(related_name='influenced_sections', to='frameworks.measuretemplate'),
        ),
    ]
