# Generated by Django 6.0.3 on 2026-04-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0017_section_influencing_measure_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='frameworkconfig',
            options={'ordering': ['framework', 'instance_config']},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ['framework_config', 'measure_template']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['path']},
        ),
        migrations.AddField(
            model_name='framework',
            name='accept_invitation_url',
            field=models.URLField(blank=True, help_text='URL template for the invitation acceptance page. Use {code} as a placeholder for the invitation code.', max_length=500, null=True, verbose_name='Accept invitation URL'),
        ),
    ]
