# Generated by Django 6.0.3 on 2026-04-16 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0018_alter_framework_options_and_more'),
        ('nodes', '0040_trailhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='allow_instance_creation',
            field=models.BooleanField(default=False, help_text='Whether authenticated users can create new model instances under this framework.', verbose_name='Allow instance creation'),
        ),
        migrations.AddField(
            model_name='framework',
            name='allow_user_registration',
            field=models.BooleanField(default=False, help_text='Whether new users can self-register under this framework.', verbose_name='Allow user registration'),
        ),
        migrations.AddField(
            model_name='framework',
            name='template_instance',
            field=models.ForeignKey(blank=True, help_text='Instance to clone when creating new instances under this framework.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nodes.instanceconfig', verbose_name='Template instance'),
        ),
    ]
