# Generated by Django 6.0.3 on 2026-04-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0020_frameworkconfig_extra_and_more'),
        ('frameworks', '0020_show_nzc_actions_pages'),
    ]

    operations = [
    ]
