# Generated by Django 6.0.3 on 2026-06-01 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0022_framework_enable_user_management'),
        ('nodes', '0046_instanceconfig_yaml_mtime_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='root_instance',
            field=models.ForeignKey(blank=True, help_text='Instance that serves framework-level content and anchors path-based instance URLs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='nodes.instanceconfig', verbose_name='Root instance'),
        ),
        migrations.AddField(
            model_name='framework',
            name='use_instance_subdomains',
            field=models.BooleanField(default=True, help_text='Whether public instance URLs should use instance identifiers as subdomains instead of UUID paths.', verbose_name='Use instance subdomains'),
        ),
    ]
