nodes:

- id: air_pollution_unit_price
  name_en: Air pollution unit price
  name_fi: Ilmansaasteiden yksikköhinta
  description_en: 'Unit prices for air pollutants, noise, accidents, and CO2 come from a single source
    (Essen et al., 2019). Datasets can be created from 1.1 Reduce transport need G129:G134 (CO2 and air pollutants),
    G169:G179 (noise), G204:G209 (accidents). The values are constant across time.
    <h2>References</h2><ul><li>Essen et. al. (2019). Handbook on the external costs of transport.
    For European Commission Directorate-General for Mobility and Transport</li></ul>'
  description_fi: 'Yksikköhinnat ilmansaasteille, melulle, onnettomuuksille ja CO2:lle tulevat yhdestä lähteestä
    (Essen et al., 2019). Datasetin voi luoda kohdista 1.1 Liikennetarpeen vähentäminen G129:G134 (CO2 ja ilmansaasteet),
    G169:G179 (melu), G204:G209 (onnettomuudet). Arvot ovat vakioita ajan suhteen.
    <h2>Lähteet</h2><ul><li>Essen et. al. (2019). Handbook on the external costs of transport.
    Euroopan komission liikenne- ja liikkuvuusasioiden pääosastolle</li></ul>'
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [pollutant, cost_type, area_distance]
  output_dimensions: [pollutant, cost_type, area_distance]
  input_datasets: [nzc/defaults]
  params:
    sector: Air pollution unit price

- id: transport_air_pollution_costs
  name_en: Transport air pollution costs
  name_fi: Liikenteen ilmansaastekustannukset
  description_en: TODO Air pollution costs also include CO2 even if it is calculated elsewhere. This results in double counting. CO2 should be removed from here.
  description_fi: TODO Ilmansaastekustannuksiin sisältyy myös CO2, vaikka se lasketaan muualla. Tämä johtaa kaksinkertaiseen laskentaan. CO2 pitäisi poistaa täältä.
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [stakeholder, pollutant, transport_mode, cost_type]
  output_dimensions: [stakeholder, pollutant, transport_mode, cost_type]
  input_nodes:
  - id: air_pollution_unit_price
    from_dimensions:
    - id: area_distance
      categories: [inside]
      flatten: true
    to_dimensions:
    - id: cost_type
    - id: pollutant
  - id: transport_air_pollution_emissions
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: transport_mode
    - id: pollutant
  - id: co_benefit_cost_shares
    to_dimensions:
    - id: cost_type
    - id: stakeholder
  output_nodes:
  - id: transport_cost
    from_dimensions:
    - id: pollutant
      flatten: true
    to_dimensions:
    - id: cost_type
    - id: stakeholder
    - id: transport_mode

- id: transport_noise_unit_price
  name_en: Transport noise unit price
  name_fi: Liikenteen melun yksikköhinta
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/pkm
  input_dimensions: [transport_mode, cost_type]
  output_dimensions: [transport_mode, cost_type]
  input_datasets: [nzc/defaults]
  params:
    sector: Noise

- id: transport_noise_unit_price_per_vkm
  name_en: Transport noise unit price per vehicle km
  name_fi: Liikenteen melun yksikköhinta ajoneuvokilometriä kohti
  type: simple.MultiplicativeNode
  quantity: unit_price
  unit: EUR/vkm
  input_dimensions: [transport_mode, cost_type]
  output_dimensions: [transport_mode, cost_type]
  input_nodes:
  - id: transport_noise_unit_price
  - id: transport_efficiency
    tags: [inventory_only, extend_values]
    to_dimensions:
    - id: transport_mode

- id: co_benefit_cost_shares
  name_en: Co-benefit cost shares
  name_fi: Rinnakkaishyötyjen kustannusosuudet
  type: gpc.DatasetNode
  quantity: fraction
  unit: dimensionless
  input_dimensions: [stakeholder, cost_type]
  output_dimensions: [stakeholder, cost_type]
  input_datasets: [nzc/defaults]
  params:
    sector: distribution of co-benefits

- id: transport_noise_cost
  name_en: Transport noise cost
  name_fi: Liikenteen melukustannukset
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [stakeholder, transport_mode, cost_type]
  output_dimensions: [stakeholder, transport_mode, cost_type]
  input_nodes:
  - id: transport_noise_unit_price_per_vkm
    to_dimensions:
    - id: cost_type
    - id: transport_mode
  - id: vehicle_kilometres
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: transport_mode
  - id: co_benefit_cost_shares
    to_dimensions:
    - id: stakeholder
    - id: cost_type
  output_nodes:
  - id: transport_cost
    to_dimensions:
    - id: transport_mode
    - id: stakeholder
    - id: cost_type

- id: transport_accident_unit_price
  name_en: Transport accident unit price
  name_fi: Liikenteen onnettomuuksien yksikköhinta
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/pkm
  input_dimensions: [transport_mode, cost_type]
  output_dimensions: [transport_mode, cost_type]
  input_datasets: [nzc/defaults]
  params:
    sector: Traffic accidents

- id: transport_accident_unit_price_per_vkm
  name_en: Transport accident unit price per vehicle km
  name_fi: Liikenteen onnettomuuksien yksikköhinta ajoneuvokilometriä kohti
  type: simple.MultiplicativeNode
  quantity: unit_price
  unit: EUR/vkm
  input_dimensions: [transport_mode, cost_type]
  output_dimensions: [transport_mode, cost_type]
  input_nodes:
  - id: transport_accident_unit_price
  - id: transport_efficiency
    tags: [inventory_only, extend_values]
    to_dimensions:
    - id: transport_mode

- id: transport_accident_cost
  name_en: Transport accident cost
  name_fi: Liikenteen onnettomuuskustannukset
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [stakeholder, transport_mode, cost_type]
  output_dimensions: [stakeholder, transport_mode, cost_type]
  input_nodes:
  - id: transport_accident_unit_price_per_vkm
    to_dimensions:
    - id: transport_mode
    - id: cost_type
  - id: vehicle_kilometres
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: transport_mode
  - id: co_benefit_cost_shares
    to_dimensions:
    - id: stakeholder
    - id: cost_type
  output_nodes:
  - id: transport_cost
    to_dimensions:
    - id: stakeholder
    - id: transport_mode
    - id: cost_type
