# Generated by Django 3.2.16 on 2023-02-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
