# Generated by Django 5.2.4 on 2025-10-27 06:14

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_extra"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cached_adminable_instances",
            field=models.CharField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\d+(?:,\\d+)*\\Z"),
                        code="invalid",
                        message="Enter only digits separated by commas.",
                    )
                ],
                verbose_name="adminable instances",
            ),
        ),
    ]
