# Generated by Django 5.2 on 2025-07-28 14:02

import django.db.models.deletion
import wagtail.fields
import wagtail_color_panel.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_instance_site_content'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('i18n', models.JSONField(blank=True, null=True)),
                ('show_in_footer', models.BooleanField(default=False, help_text='Should the page be shown in the footer?', verbose_name='show in footer')),
                ('background_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, verbose_name='Background color')),
                ('dashboard_cards', wagtail.fields.StreamField([('card', 15)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}), 4: ('nodes.blocks.NodeChooserBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 3), ('node_config', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'required': True}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 3), ('node_config', 4), ('scenario_identifier', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('goal_progress_bar', 5), ('reference_progress_bar', 5), ('current_progress_bar', 5), ('scenario_progress_bar', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('progress_bars', 8)]], {}), 10: ('wagtail.blocks.StreamBlock', [[('progress', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 12: ('wagtail.blocks.CharBlock', (), {'label': 'Content', 'required': False}), 13: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL'}), 14: ('wagtail.blocks.StructBlock', [[('title', 11), ('content', 12), ('link_url', 13)]], {}), 15: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('image', 2), ('visualization', 10), ('call_to_action', 14)]], {})})),
            ],
            options={
                'verbose_name': 'Dashboard page',
                'verbose_name_plural': 'Dashboard pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
