# Generated by Django 6.1 on 2026-10-02 04:21

import pages.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0018_add_menu_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='dashboard_cards',
            field=wagtail.fields.StreamField(
                [('card', 18)],
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}),
                    3: ('nodes.blocks.NodeChooserBlock', (), {'required': True}),
                    4: ('wagtail.blocks.IntegerBlock', (), {'min_value': 0, 'required': False}),
                    5: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}),
                    6: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 5)]], {}),
                    7: ('wagtail.blocks.CharBlock', (), {'required': True}),
                    8: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 5), ('scenario_id', 7)]],
                        {},
                    ),
                    9: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {
                            'help_text': 'Break down the given dimension into its categories. If empty, break down into input nodes.',
                            'required': False,
                        },
                    ),
                    10: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('dimension_id', 9)]],
                        {'help_text': 'Break down the value into its components', 'label': 'Category breakdown'},
                    ),
                    11: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': pages.blocks.admin_instance_scenario_choices,
                            'help_text': 'Show the impact of each action as computed in this scenario, whichever scenario the visitor has selected.',
                            'label': 'Scenario',
                        },
                    ),
                    12: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('scenario_id', 11)]],
                        {'help_text': 'Visualize the impact of actions in a scenario', 'label': 'Action impact'},
                    ),
                    13: (
                        'wagtail.blocks.StreamBlock',
                        [
                            [
                                ('goal_progress_bar', 6),
                                ('reference_progress_bar', 6),
                                ('current_progress_bar', 6),
                                ('scenario_progress_bar', 8),
                                ('category_breakdown', 10),
                                ('action_impact', 12),
                            ]
                        ],
                        {},
                    ),
                    14: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}),
                    15: ('wagtail.blocks.CharBlock', (), {'label': 'Content', 'required': False}),
                    16: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL'}),
                    17: ('wagtail.blocks.StructBlock', [[('title', 14), ('content', 15), ('link_url', 16)]], {}),
                    18: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('title', 0),
                                ('description', 1),
                                ('image', 2),
                                ('node_config', 3),
                                ('goal_index', 4),
                                ('visualizations', 13),
                                ('call_to_action', 17),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
