# Generated by Django 6.1 on 2026-10-06 08:58

import pages.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0019_action_impact_block_scenario_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardpage',
            name='dashboard_cards',
            field=wagtail.fields.StreamField(
                [('card', 19)],
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {}),
                    1: ('wagtail.blocks.CharBlock', (), {'required': False}),
                    2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}),
                    3: ('nodes.blocks.NodeChooserBlock', (), {'required': True}),
                    4: ('wagtail.blocks.IntegerBlock', (), {'min_value': 0, 'required': False}),
                    5: (
                        'wagtail.blocks.IntegerBlock',
                        (),
                        {
                            'help_text': "The year whose values the card shows. Leave empty for the instance's target year. Use it for a quantity whose year of interest is another one, such as a budget used up by the end of the model.",
                            'label': 'Year',
                            'required': False,
                        },
                    ),
                    6: ('wagtail_color_panel.blocks.NativeColorBlock', (), {'required': False}),
                    7: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 6)]], {}),
                    8: ('wagtail.blocks.CharBlock', (), {'required': True}),
                    9: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('description', 1), ('chart_label', 0), ('color', 6), ('scenario_id', 8)]],
                        {},
                    ),
                    10: (
                        'wagtail.blocks.CharBlock',
                        (),
                        {
                            'help_text': 'Break down the given dimension into its categories. If empty, break down into input nodes.',
                            'required': False,
                        },
                    ),
                    11: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('dimension_id', 10)]],
                        {'help_text': 'Break down the value into its components', 'label': 'Category breakdown'},
                    ),
                    12: (
                        'wagtail.blocks.ChoiceBlock',
                        [],
                        {
                            'choices': pages.blocks.admin_instance_scenario_choices,
                            'help_text': 'Show the impact of each action as computed in this scenario, whichever scenario the visitor has selected.',
                            'label': 'Scenario',
                        },
                    ),
                    13: (
                        'wagtail.blocks.StructBlock',
                        [[('title', 0), ('scenario_id', 12)]],
                        {'help_text': 'Visualize the impact of actions in a scenario', 'label': 'Action impact'},
                    ),
                    14: (
                        'wagtail.blocks.StreamBlock',
                        [
                            [
                                ('goal_progress_bar', 7),
                                ('reference_progress_bar', 7),
                                ('current_progress_bar', 7),
                                ('scenario_progress_bar', 9),
                                ('category_breakdown', 11),
                                ('action_impact', 13),
                            ]
                        ],
                        {},
                    ),
                    15: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}),
                    16: ('wagtail.blocks.CharBlock', (), {'label': 'Content', 'required': False}),
                    17: ('wagtail.blocks.CharBlock', (), {'label': 'Link URL'}),
                    18: ('wagtail.blocks.StructBlock', [[('title', 15), ('content', 16), ('link_url', 17)]], {}),
                    19: (
                        'wagtail.blocks.StructBlock',
                        [
                            [
                                ('title', 0),
                                ('description', 1),
                                ('image', 2),
                                ('node_config', 3),
                                ('goal_index', 4),
                                ('year', 5),
                                ('visualizations', 14),
                                ('call_to_action', 18),
                            ]
                        ],
                        {},
                    ),
                },
            ),
        ),
    ]
