library(GGally)
library(tidyverse)
library(googlesheets4)

file <- "/Users/jouni/Downloads/Database_for_delivery_2025_May.xlsx"
df <- readxl::read_xlsx(file, sheet = "Database")
df <- df[!colnames(df) %in% c("0...121", "0...161")]
df$Var <- ifelse(is.na(df$Placeholder_name), df$Database_name, df$Placeholder_name)
df <- df[c("Var", colnames(df)[1:(ncol(df)-1)])]

df$Var <- ifelse(df$Var == "Converted", df$Database_name, df$Var)
typo <- c(
  "F131/Share of district heating as Electric heat pumps / geothermal",
  "Share of district heating as Bio (biogas, biomass)"
)
df$Var <- ifelse(
  df$Placeholder_name == typo[1] & df$Database_name == typo[2],
  df$Database_name, df$Var
)
df <- df[!duplicated(df[c("Var", "Year")]) , ] # Fuel consumption of electric vehicles

index_cols <- c("Var", "Placeholder_name", "Database_name", "Year", "unit", "Sheet reference",
                "Cell reference", "Data source (s)", "Notes")
countries <- as.data.frame(t(df[1, ]))
countries$City <- rownames(countries)
colnames(countries)[colnames(countries) == "V1"] <- "Country"
drops <- c(vars, 0, "Demographic data", "country")
countries <- countries[!countries$Country %in% drops , ]

df <- df[2:nrow(df) , ]
for(col in colnames(df)[!colnames(df) %in% index_cols]) {
  df[[col]] <- as.numeric(df[[col]])
}

# Named list for variable name replacement
name_mapping <- list(
  "015/Population" = "015 Population",
  "016/Expected annual population growth (up until 2030)" = "016 Pop Growth to 2030",
  "017/City Area" = "017 City Area",
  "022/Total transportation need - passenger transport: Transport need - passenger cars + motorcycles" = "022 Pass Cars+Motorbikes Need",
  "023/Total transportation need - passenger transport: Transport need - buses" = "023 Bus Transport Need",
  "024/Total transportation need - passenger transport: Transport need - trains/metro" = "024 Train/Metro Need",
  "Train connection" = "Train Connection",
  "025/Total transportation need - passenger transport: Transport need - walking/cycling" = "025 Walk/Cycle Need",
  "028/Number of passengers per vehicle: Average passengers per car + motorcycle" = "028 Avg Pass per Car+Motorbike",
  "029/Number of passengers per vehicle: Average passengers per bus" = "029 Avg Pass per Bus",
  "030/Number of passengers per vehicle: Average passengers per metro train" = "030 Avg Pass per Metro",
  "046/Passenger cars other data: Total number of cars motorcycles in city" = "046 Cars+Motorbikes in City",
  "047/Passenger cars other data: Share of fleet that is less than 2 years old" = "047 Fleet <2yr Share",
  "048/Passenger cars other data: Share of fleet fully electric (not including hybrids)" = "048 Fleet Elec Share",
  "051/Buses - other data: Number of buses in city bus fleet" = "051 City Bus Fleet Size",
  "052/Buses - other data: Share of bus fleet as fully electric buses (not including hybrids)" = "052 Bus Fleet Elec Share",
  "053/Buses - other data: Share of bus fleet - biobased" = "053 Bus Fleet Bio Share",
  "058/Light duty trucks <3.5 tonnes" = "058 Light Trucks <3.5t",
  "059/Heavy duty trucks >3.5 tonnes" = "059 Heavy Trucks >3.5t",
  "063/Average utilisation: Light duty trucks <3.5 tonnes" = "063 Light Trucks Utilization",
  "064/Average utilisation: Heavy duty trucks >3.5 tonnes" = "064 Heavy Trucks Utilization",
  "081/Number of trucks registered within city: Light duty trucks <3.5 tonnes" = "081 Light Trucks Registered",
  "082/Number of trucks registered within city: Of which less than 2 years old" = "082 Trucks <2yr Registered",
  "083/Number of trucks registered within city: Heavy duty trucks >3.5 tonnes" = "083 Heavy Trucks Registered",
  "084/Number of trucks registered within city: Of which less than 2 years old" = "084 Heavy Trucks <2yr Reg",
  "090/Existing building stock: Total floor area (residental & non-residential)" = "090 Total Floor Area",
  "097/Share of building stock renovated each year" = "097 Bldg Renovation Rate",
  "122/Total heating demand (space heating + domestic hot water)" = "122 Total Heating Demand",
  "162/Total electricity demand within city boundaries" = "162 City Electricity Demand",
  "177/Spot price electricity" = "177 Electricity Spot Price",
  "180/Solar electricity produced by solar PVs" = "180 Solar PV Production",
  "181/Yearly average of solar electricity generated by 1 m2 solar PV" = "181 Solar PV per m2",
  "F034/Emission factors of Passenger car motorcycle fleet (current average fleet): CO2 emissions" = "F034 Pass Car EF CO2",
  "F035/Emission factors of Passenger car motorcycle fleet (current average fleet): NOx emissions" = "F035 Pass Car EF NOx",
  "F036/Emission factors of Passenger car motorcycle fleet (current average fleet): PM 2.5 emissions" = "F036 Pass Car EF PM2.5",
  "F037/Emission factors of Passenger car motorcycle fleet (current average fleet): PM 10 emissions" = "F037 Pass Car EF PM10",
  "F040/Buses (average fleet): CO2 emissions" = "F040 Bus EF CO2",
  "F041/Buses (average fleet): NOx emissions" = "F041 Bus EF NOx",
  "F042/Buses (average fleet): PM 2.5 emissions" = "F042 Bus EF PM2.5",
  "F043/Buses (average fleet): PM 10 emissions" = "F043 Bus EF PM10",
  "F068/Emission factors from transportation for Light duty trucks <3.5 tonnes: CO2 emissions" = "F068 Light Truck EF CO2",
  "F069/Emission factors from transportation for Light duty trucks <3.5 tonnes: NOx emissions" = "F069 Light Truck EF NOx",
  "F070/Emission factors from transportation for Light duty trucks <3.5 tonnes: PM 2.5 emissions" = "F070 Light Truck EF PM2.5",
  "F071/Emission factors from transportation for Light duty trucks <3.5 tonnes: PM 10 emissions" = "F071 Light Truck EF PM10",
  "F074/Emission factors from transportation for Heavy duty trucks >3.5 tonnes: CO2 emissions" = "F074 Heavy Truck EF CO2",
  "F075/Emission factors from transportation for Heavy duty trucks >3.5 tonnes: NOx emissions" = "F075 Heavy Truck EF NOx",
  "F076/Emission factors from transportation for Heavy duty trucks >3.5 tonnes: PM 2.5 emissions" = "F076 Heavy Truck EF PM2.5",
  "F077/Emission factors from transportation for Heavy duty trucks >3.5 tonnes: PM 10 emissions" = "F077 Heavy Truck EF PM10",
  "F093/Energy use in existing buildings: Average heat use in existing buildings (space heating + domestic hot water)" = "F093 Existing Bldg Heat Use",
  "F094/Energy use in existing buildings: Average electricity use for lighting & appliances" = "F094 Existing Bldg Elec Use",
  "F110/Building standards for new buildings: Minimum building standard (heat use)" = "F110 Min Bldg Standard Heat",
  "F111/Building standards for new buildings: Top performing building standard (heat use)" = "F111 Top Bldg Standard Heat",
  "F113/Share of new buildings built with minimum standard (today)" = "F113 New Bldg Min Standard",
  "F114/Share of new buildings built with \"better than minimum\" standard (today)" = "F114 New Bldg Better Standard",
  "F125/Heating technologies: Share of heating as district heating" = "F125 DH Share",
  "F126/Heating technologies: Share of heating as local heating" = "F126 LH Share",
  "F130/Share of district heating as Fossil (oil, coal, gas) + inefficient electric heating (not heat pumps)" = "F130 DH Fossil Share",
  "F131/Share of district heating as Electric heat pumps / geothermal" = "F131 DH Heat Pump Share",
  "Share of district heating as Bio (biogas, biomass)" = "DH Bio Share",
  "F132/Share of district heating as Bio (biogas, biomass)" = "F132 DH Bio Share",
  "F133/Share of district heating as Waste (fossil & non-fossil waste)" = "F133 DH Waste Share",
  "F137/Share of waste used in district heating that is fossil / non-fossil: Fossil share" = "F137 DH Waste Fossil Share",
  "F138/Share of waste used in district heating that is fossil / non-fossil: Non-fossil share" = "F138 DH Waste Non-fossil Share",
  "F141/Share of local heating as Fossil (oil, gas, coal) + inefficient electric heating (not heat pumps)" = "F141 LH Fossil Share",
  "F142/Share of local heating as Electric (heat pumps)" = "F142 LH Heat Pump Share",
  "F143/Share of local heating as Biobased" = "F143 LH Bio Share",
  "F148/Emission factors from heat production of District heating: CO2 emissions" = "F148 DH EF CO2",
  "F149/Emission factors from heat production of District heating: NOx emissions" = "F149 DH EF NOx",
  "F150/Emission factors from heat production of District heating: PM 2.5 emissions" = "F150 DH EF PM2.5",
  "F151/Emission factors from heat production of District heating: PM 10 emissions" = "F151 DH EF PM10",
  "F154/Emission factors from heat production of Local heating: CO2 emissions" = "F154 LH EF CO2",
  "F155/Emission factors from heat production of Local heating: NOx emissions" = "F155 LH EF NOx",
  "F156/Emission factors from heat production of Local heating: PM 2.5 emissions" = "F156 LH EF PM2.5",
  "F157/Emission factors from heat production of Local heating: PM 10 emissions" = "F157 LH EF PM10",
  "F165/Share of total electricity demand produced by fossil/renewables for Renewable sources" = "F165 Elec Renew Share",
  "F166/Share of total electricity demand produced by fossil/renewables for Fossil sources" = "F166 Elec Fossil Share",
  "F167/Share of total electricity demand produced by fossil/renewables for Other (e.g. nuclear)" = "F167 Elec Other Share",
  "F171/Emission factors from electricity generation: CO2 emissions" = "F171 Elec Gen EF CO2",
  "F172/Emission factors from electricity generation: NOx emissions" = "F172 Elec Gen EF NOx",
  "F173/Emission factors from electricity generation: PM 2.5 emissions" = "F173 Elec Gen EF PM2.5",
  "F174/Emission factors from electricity generation: PM 10 emissions" = "F174 Elec Gen EF PM10",
  "Fuel consumption electric vehicles" = "EV Fuel Consumption",
  "Nox, within city (e.g. transport)" = "NOx City Transport",
  "Nox, outside city (e.g. electricity production)" = "NOx Outside City",
  "PM2.5 in main metropolitan area" = "PM2.5 Metro Area",
  "PM2.5 within city" = "PM2.5 City",
  "PM2.5, outside city" = "PM2.5 Outside City",
  "PM10, average" = "PM10 Average",
  "Passenger car noise" = "Pass Car Noise",
  "Bus noise" = "Bus Noise",
  "Passenger train noise" = "Train Noise",
  "light duty trucks (< 3.5 tonnes) noise" = "Light Truck Noise",
  "Heavy duty trucks (> 3.5 tonnes) noise" = "Heavy Truck Noise",
  "Average value of increased walking/cycling" = "Walk/Cycle Value",
  "Value of CO2 reduction" = "CO2 Reduction Value",
  "Operating costs (excluding fuel) for fuel ?" = "OpCost Fuel",
  "Operating costs (excluding fuel) for maintanence" = "OpCost Maintenance",
  "Operating costs (excluding fuel) for tyres" = "OpCost Tyres",
  "Operating costs (excluding fuel) for depreciation" = "OpCost Depreciation",
  "EV home charging infrastructure" = "EV Home Charge Infra",
  "EV public and workplace infrastructure" = "EV Public Charge Infra",
  "Ev home-charging infrastructure cost reduction per year" = "EV Home Infra Cost Reduc/yr",
  "EV public and workplace infrastructure cost reduction per year" = "EV Public Infra Cost Reduc/yr",
  "Additional costs for electric vehicles" = "EV Additional Costs",
  "Buses total cost of ownership" = "Bus TCO",
  "buses total cost of ownership of which CAPEX" = "Bus TCO CAPEX",
  "buses total cost of ownership of which OPEX" = "Bus TCO OPEX",
  "Electricity consumption for electric buses" = "Elec Bus Consumption",
  "Additional cost for electric buses" = "Elec Bus Additional Cost",
  "% reduction in additional costs for buses per year" = "Bus Cost Reduc %/yr",
  "Charging infrastructure costs for buses" = "Bus Charge Infra Cost",
  "% reduction in additional costs for buses infrastructure per year" = "Bus Infra Cost Reduc %/yr",
  "Total cost of ownership for metro/tram" = "Metro/Tram TCO",
  "Total cost of ownership for metro/tram of which CAPEX" = "Metro/Tram TCO CAPEX",
  "Total cost of ownership for metro/tram of which OPEX" = "Metro/Tram TCO OPEX",
  "Electricity consumption for metro/tram" = "Metro/Tram Elec Consumption",
  "Average CAPEX of walking / cycling" = "Walk/Cycle CAPEX",
  "Total cost of ownership for light duty trucks < 3.5 tonnes" = "Light Truck TCO",
  "Total cost of ownership for heavy duty trucks > 3.5 tonnes" = "Heavy Truck TCO",
  "Additional cost for light duty truck" = "Light Truck Add Cost",
  "Additional cost for light trucks in 2030" = "Light Truck Add Cost 2030",
  "Additional cost for heavy duty truck" = "Heavy Truck Add Cost",
  "% reduction in cost per year for heavy duty trucks" = "Heavy Truck Cost Reduc %/yr",
  "Light duty trucks - charging infrastructure cost, additional cost" = "Light Truck Charge Infra Cost",
  "% reduction in cost per year for charging infrastructure" = "Charge Infra Cost Reduc %/yr",
  "Heavy duty trucks - charging infrastructure cost, additional cost" = "Heavy Truck Charge Infra Cost",
  "% reduction in cost per year for heavy duty trucks infrastructure" = "Heavy Truck Infra Reduc %/yr",
  "Electricity consumption in light duty trucks < 3.5 tonnes" = "Light Truck Elec Consumption",
  "Electricity consumption in light duty trucks > 3.5 tonnes" = "Heavy Truck Elec Consumption",
  "Discount on electricity cost (household price) for fleet operators" = "Fleet Elec Price Discount",
  "Buildings demolition rate" = "Bldg Demolition Rate",
  "117/Building costs - new buildings: Minimum building standard" = "117 New Bldg Min Standard Cost",
  "118/Building costs - new buildings: Top performing building standard" = "118 New Bldg Top Standard Cost",
  "Cost improvements % reduction in cost per year for minimum building standard" = "Min Bldg Standard Cost Reduc %",
  "Cost improvements % reduction in cost per year for better than minimum building standard" = "Better Bldg Standard Cost Reduc",
  "100/Energy efficiency improvements from building renovations: Minor heating renovations (0-30% improvement)" = "100 Minor Heat Renovation Eff",
  "101/Energy efficiency improvements from building renovations: Extensive heating renovations (30-60% improvement)" = "101 Extensive Heat Renov Eff",
  "104/Cost of energy renovations: Minor heating renovations (0-30% improvement)" = "104 Minor Heat Renov Cost",
  "105/Cost of energy renovations: Extensive heating renovations (30-60% improvement)" = "105 Extensive Heat Renov Cost",
  "Reduced electricity need with minor efficiency improvements for lighting and appliances" = "Minor Elec Eff Lighting",
  "Reduced electricity need with aggressive efficiency improvements for lighting and applicances" = "Aggressive Elec Eff Lighting",
  "Cost of efficiency programme per m2 for minor efficiency improvements for lighting and applicances" = "Minor Eff Program Cost/m2",
  "Cost of efficiency programme per m2 for aggressive efficiency improvements for lighting and applicances" = "Aggressive Eff Program Cost/m2",
  "Cost improvements of efficiency programme for minor efficiency improvements for lighting and appliances" = "Minor Eff Program Improv",
  "Cost improvements of efficiency programme for aggressive efficiency improvements for lighting and appliances" = "Aggressive Eff Program Improv",
  "OPEX costs for district heating from fossil fuels ((oil, coal, gas)" = "DH Fossil OPEX",
  "OPEX costs for district heating from Electric heat pumps / geothermal" = "DH Heat Pump OPEX",
  "OPEX costs for district heating from bio (biogas, biomass)" = "DH Bio OPEX",
  "OPEX costs for district heating from waste (fossil & non-fossil waste)" = "DH Waste OPEX",
  "OPEX costs for local heating from fossil" = "LH Fossil OPEX",
  "OPEX costs for local heating from electric heat pumps / geothermal" = "LH Heat Pump OPEX",
  "OPEX costs for local heating from biomass" = "LH Biomass OPEX",
  "CAPEX costs for district heating from fossil (oil, coal, gas)" = "DH Fossil CAPEX",
  "CAPEX costs for electric heat pumps / geothermal" = "Heat Pump CAPEX",
  "CAPEX costs for bio (biogas / biomass)" = "Bio CAPEX",
  "CAPEX costs for waste (fossil and non-fossil waste)" = "Waste CAPEX",
  "CAPEX costs for network infrastructure" = "Network Infra CAPEX",
  "CAPEX costs for local heating from fossil" = "LH Fossil CAPEX",
  "CAPEX costs for local heating from electric heat pumps / geothermal" = "LH Heat Pump CAPEX",
  "CAPEX costs for local heating from biomass" = "LH Biomass CAPEX",
  "Average heating costs for a residential consumer" = "Residential Heat Cost",
  "Efficiency of heat pumps" = "Heat Pump Efficiency",
  "244/Retail price of electricity" = "244 Elec Retail Price",
  "245/Retail price of heating" = "245 Heat Retail Price",
  "CAPEX for solar PV rooftop residential" = "Solar PV Residential CAPEX",
  "CAPEX for centralised solar / wind parks" = "Solar/Wind Parks CAPEX",
  "CAPEX reduction per year for solar PV" = "Solar PV CAPEX Reduc/yr",
  "CAPEX reduction per year for wind" = "Wind CAPEX Reduc/yr",
  "CAPEX reduction per year for other costs (e.g. flexibility costs)" = "Other CAPEX Reduc/yr",
  "OPEX for solar PV -  rooftop residential" = "Solar PV Residential OPEX",
  "OPEX for centralised solar / wind parks" = "Solar/Wind Parks OPEX",
  "other costs for renewable energy (e.g. flexibility cost)" = "Renew Energy Other Costs",
  "Waste/Total collected waste within city boundaries/Paper and cardboard" = "Waste Paper/Cardboard City",
  "Waste/Total collected waste within city boundaries/Metal" = "Waste Metal City",
  "Waste/Total collected waste within city boundaries/Plastics" = "Waste Plastics City",
  "Waste/Total collected waste within city boundaries/Glass" = "Waste Glass City",
  "199/Share of paper waste - other (e.g. landfilled)" = "199 Paper Waste Other Share",
  "200/Share of paper waste - incinerated (e.g. energy recovery)" = "200 Paper Waste Incinerated",
  "201/Share of paper waste - recycled" = "201 Paper Waste Recycled",
  "205/Share of metal waste - landfilled" = "205 Metal Waste Landfilled",
  "206/Share of metal waste - incinerated (e.g. energy recovery)" = "206 Metal Waste Incinerated",
  "207/Share of metal waste - recycled" = "207 Metal Waste Recycled",
  "211/Share of plastic waste - landfilled" = "211 Plastic Waste Landfilled",
  "212/Share of plastic waste - incinerated (e.g. energy recovery)" = "212 Plastic Waste Incinerated",
  "213/Share of plastic waste - recycled" = "213 Plastic Waste Recycled",
  "217/Share of glass waste - landfilled" = "217 Glass Waste Landfilled",
  "219/Share of glass waste - recycled" = "219 Glass Waste Recycled",
  "Waste data/Waste incineration/Energy recovered from incineration" = "Incineration Energy Recovery",
  "Waste data/Waste incineration/Price of energy recovered from incineration" = "Incineration Energy Price",
  "Prices of sorted waste/Paper" = "Sorted Paper Price",
  "Prices of sorted waste/Metal" = "Sorted Metal Price",
  "Prices of sorted waste/Plastics" = "Sorted Plastics Price",
  "Prices of sorted waste/Glass" = "Sorted Glass Price",
  "Prices of sorted waste/Organic" = "Sorted Organic Price",
  "Waste management costs/Landfill/CAPEX" = "WM Landfill CAPEX",
  "Waste management costs/Landfill/OPEX" = "WM Landfill OPEX",
  "Waste management costs/Incineration/CAPEX" = "WM Incineration CAPEX",
  "Waste management costs/Incineration/OPEX" = "WM Incineration OPEX",
  "Waste management costs/Composting/CAPEX" = "WM Composting CAPEX",
  "Waste management costs/Composting/OPEX" = "WM Composting OPEX",
  "Waste management costs/Sorting/CAPEX" = "WM Sorting CAPEX",
  "Waste management costs/Sorting/OPEX" = "WM Sorting OPEX",
  "Waste management costs/Sorting for plastics/CAPEX" = "WM Plastic Sorting CAPEX",
  "Waste management costs/Sorting for plastics/OPEX" = "WM Plastic Sorting OPEX",
  "189/Total collected waste within city boundaries: Paper and cardboard" = "189 Paper/Cardboard Collected",
  "190/Total collected waste within city boundaries: Metal" = "190 Metal Collected",
  "191/Total collected waste within city boundaries: Plastics" = "191 Plastics Collected",
  "192/Total collected waste within city boundaries: Glass" = "192 Glass Collected"
)

# Emission Factor = EF
# Passenger = Pass
# Electric = Elec
# Buildings = Bldg
# Infrastructure = Infra
# Total Cost of Ownership = TCO
# District Heating = DH
# Local Heating = LH
# Average = Avg
# Within city boundaries = City
# Efficiency = Eff
# Improvement = Improv
# Reduction = Reduc

df$Var[df$Var %in% names(name_mapping)] <- unlist(name_mapping[df$Var[df$Var %in% names(name_mapping)]])

vars <- unique(df$Var)
meta <- df[index_cols]

df <- df[!colnames(df) %in% index_cols[!index_cols %in% c("Var", "Year")]]

df <- pivot_longer(df, cols = -c("Var", "Year"), names_to = "City", values_to = "Value")
cities <- unique(df$City)

# Fill year=0 values forward to all years within each group
df <- df %>%
  # First, identify combinations with year=0
  group_by(Var, City) %>%
  filter(any(Year == 0)) %>%  # Only keep groups that have year=0
  # Then expand only those groups
  complete(Year = unique(df$Year)) %>%  # or specify: Year = c(0, 2020, 2021, 2022, etc.)
  fill(Value, .direction = "downup") %>%
  ungroup() %>%
  # Combine with original data that doesn't have year=0
  bind_rows(
    df %>% 
      group_by(Var, City) %>%
      filter(!any(Year == 0)) %>%  # Keep groups without year=0 unchanged
      ungroup()
  ) %>%
  arrange(Var, City, Year)

df <- df[df$Year != 0 , ]

dfw <- pivot_wider(df, id_cols = c("City", "Year"), names_from = "Var", values_from = "Value")
blocks <- list(1:25, 26:50, 51:75, 76:100, 101:125, 126:150, 151:175, 176:200, 201:208)

dfw$`Pop density` <- dfw$`015 Population` / dfw$`017 City Area`
dfw$`Pop density` <- ifelse(dfw$`Pop density` == Inf, NA, dfw$`Pop density`)

for(i in blocks) {
  print(i)
  g <- ggplot(df[df$Var %in% vars[i] , ], aes(x = Value))+geom_histogram()+
    facet_wrap(~Var, scales = "free")+
    scale_x_log10()+
    labs(
      title = paste("Histograms of variables")
    )
  print(g)
}

# Classify variables

# Start with your summary
s <- summary(dfw)

# Initialize lists to store variable names for each category
var_bins <- list(
  negative_vars = character(),
  no_variation = character(),
  small_variance = character(),
  large_variance = character()
)

# Function to classify variables
classify_variables <- function(df) {
  results <- list()
  
  for(col in names(df)) {
    if(is.numeric(df[[col]])) {
      col_data <- df[[col]][!is.na(df[[col]])]  # Remove NAs
      
      # Check if empty after removing NAs
      if(length(col_data) == 0) {
        results[[col]] <- "no_data"
        next
      }
      
      # 1. Check for negative values
      has_negative <- any(col_data < 0, na.rm = TRUE)
      
      # 2. Check for no variation (constant values)
      variance <- var(col_data, na.rm = TRUE)
      
      if(is.na(variance) || variance == 0) {
        results[[col]] <- "no_variation"
      } else if(has_negative) {
        results[[col]] <- "negative_values"
      } else {
        # 3 & 4. Classify by variance size
        # You can adjust these thresholds based on your data
        cv <- sd(col_data, na.rm = TRUE) / mean(col_data, na.rm = TRUE)  # Coefficient of variation
        
        if(cv < 0.5) {  # Small relative variation
          results[[col]] <- "small_variance" 
        } else {
          results[[col]] <- "large_variance"
        }
      }
    } else {
      results[[col]] <- "non_numeric"
    }
  }
  
  return(results)
}

# Classify your variables
classification <- classify_variables(dfw)

# Organize into bins
for(var in names(classification)) {
  category <- classification[[var]]
  if(category == "negative_values") {
    var_bins$negative_vars <- c(var_bins$negative_vars, var)
  } else if(category == "no_variation") {
    var_bins$no_variation <- c(var_bins$no_variation, var)
  } else if(category == "small_variance") {
    var_bins$small_variance <- c(var_bins$small_variance, var)
  } else if(category == "large_variance") {
    var_bins$large_variance <- c(var_bins$large_variance, var)
  }
}

# View results
lapply(var_bins, length)  # Number of variables in each category
var_bins  # See the actual variable names

ggplot(df[df$Var %in% var_bins$negative_vars , ], aes(x = Value))+geom_histogram()+
  facet_wrap(~Var, scales = "free")+
  labs(
    title = paste("Histograms of variables with negative values")
  )

ggplot(df[df$Var %in% var_bins$no_variation , ], aes(x = Value))+geom_histogram()+
  facet_wrap(~Var, scales = "free")+
  labs(
    title = paste("Histograms of variables with no variation")
  )

library(corrplot)
library(ggcorrplot)

# Function to analyze dependencies
analyze_dependencies <- function(df, outcome_vars, determinant_vars) {
  
  # Create correlation matrix
  cor_data <- df[, c(outcome_vars, determinant_vars)]
  cor_matrix <- cor(cor_data, use = "pairwise.complete.obs")

  # Visualize
  ggcorrplot(cor_matrix,
             hc.order = FALSE,
             type = "full",
             lab = TRUE,
             lab_size = 3,
             title = "Outcome-Determinant Correlations")

  cor_long <- melt( # nolint
    cor_matrix,
    varnames = c("var1", "var2"),
    value.name = "correlation")
  cor_long <- cor_long %>%
    filter(var1 != var2) %>% # Remove self-correlations (diagonal) # nolint
    filter(var1 %in% determinant_vars) %>%
    filter(var2 %in% outcome_vars)
  cor_long <- cor_long[order(-cor_long$correlation) , ]
  cor_long <- unique(cor_long)
    
  return(cor_long)
}

# Example usage
determinant_vars <- c("015 Population", "Pop density", "Year")
outcome_vars <- var_bins$large_variance

analyze_dependencies(dfw, outcome_vars, determinant_vars)

# REGRESSION ANALYSIS

library(broom)
library(purrr)

# Function to test multiple determinants against each outcome
analyze_all_dependencies <- function(df, outcome_vars, determinant_vars) {
  
  results <- list()
  
  for(outcome in outcome_vars) {
    outcome_results <- list()
    
    for(determinant in determinant_vars) {
      # Simple linear regression
      formula_str <- paste0("`", outcome, "` ~ `", determinant, "`")
      print(formula_str)
      
        model <- lm(as.formula(formula_str), data = df)
        model_summary <- tidy(model)
        
        outcome_results[[determinant]] <- list(
          r_squared = summary(model)$r.squared,
          p_value = model_summary$p.value[2],
          coefficient = model_summary$estimate[2],
          significant = model_summary$p.value[2] < 0.05
        )
    }
    results[[outcome]] <- outcome_results
  }
  
  return(results)
}
lmout <- analyze_all_dependencies(dfw, outcome_vars, determinant_vars)

# Convert results to readable format
summarize_dependencies <- function(results) {
  summary_df <- data.frame()
  
  for(outcome in names(results)) {
    for(determinant in names(results[[outcome]])) {
      summary_df <- rbind(summary_df, data.frame(
        outcome = outcome,
        determinant = determinant,
        r_squared = results[[outcome]][[determinant]]$r_squared,
        p_value = results[[outcome]][[determinant]]$p_value,
        coefficient = results[[outcome]][[determinant]]$coefficient,
        significant = results[[outcome]][[determinant]]$significant
      ))
    }
  }

  summary_df <- summary_df %>%
    group_by(outcome) %>% # nolint
    mutate(max_coef_in_group = max(abs(coefficient), na.rm = TRUE)) %>% # nolint
    ungroup() %>% # nolint
    arrange(desc(max_coef_in_group), # nolint
            outcome,
            desc(abs(coefficient)))
  summary_df <- summary_df %>% select(-max_coef_in_group) # nolint
  
  return(summary_df)
}

lmout <- analyze_all_dependencies(
  dfw, var_bins$large_variance, determinant_vars)
lmlarge <- summarize_dependencies(lmout)
lmout <- analyze_all_dependencies(
  dfw, var_bins$small_variance, determinant_vars)
lmsmall <- summarize_dependencies(lmout)
lmout <- analyze_all_dependencies(dfw, var_bins$negative_vars, determinant_vars)
lmneg <- summarize_dependencies(lmout)

############ LOOK AT THE COMPARISONS

dfc <- readxl::read_xlsx(file, sheet = "42_cities_EM_PH_Eurostat")
colnames(dfc)[colnames(dfc) == "...1"] <- "Var"
dfc$Var[dfc$Var %in% names(name_mapping)] <- unlist(
  name_mapping[dfc$Var[dfc$Var %in% names(name_mapping)]]
)

dfcl <- dfc %>%
  pivot_longer(
    cols = -c("Var"),
    names_to = "column_name",
    values_to = "value"
  ) %>%
  mutate(
    Source = case_when(
      str_detect(column_name, "^PH_") ~ "CCV",
      str_detect(column_name, "^Eurostat_") ~ "Eurostat",
      TRUE ~ "Local"
    ),
    City = case_when(
      str_detect(column_name, "^PH_") ~ str_remove(column_name, "^PH_"),
      str_detect(column_name, "^Eurostat_") ~ str_remove(column_name, "^Eurostat_"),
      TRUE ~ column_name  # Keep the full name, including underscores
    )
  ) %>%
  select(-column_name)

dfcw <- dfcl %>%
  pivot_wider(
              id_cols = c("City", "Var"),
              names_from = "Source",
              values_from = "value")

my_smooth <- function(data, mapping, ...) {
  ggally_smooth_lm(data, mapping, alpha = 0.5, size = 0.7) +
    coord_cartesian(xlim = data_range, ylim = data_range) # nolint
}

# Custom histogram with specified bins
my_hist <- function(data, mapping, ...) {
  ggally_barDiag(data, mapping, bins = 30)  # Specify bins to avoid warning
}

for(i in unique(dfcw$Var)) {
  # Calculate common limits for your data subset
  current_data <- dfcw[dfcw$Var == i, c("Local", "CCV", "Eurostat")]
  data_range <- range(unlist(current_data), na.rm = TRUE)

  g <- ggpairs(dfcw[dfcw$Var == i, ],
               columns = c("Eurostat", "Local", "CCV"),
               diag = list(continuous = my_hist),
               upper = list(continuous = "cor"),
               lower = list(continuous = my_smooth),
          title = i)
  print(g)
}
