dimensions:

- id: emission_sector
  label: Päästösektori
  label_en: Main emission sector
  label_sv: Utsläppsektor
  categories:
  - id: district_heating
    label: Kaukolämpö
    label_en: District heating
    label_sv: Fjärrvärme
  - id: oil_heating
    label: Öljylämmitys
    label_en: Oil heating
    label_sv: Oljevärme
  - id: electric_heating
    label: Sähkölämmitys
    label_en: Electric heating
    label_sv: Elvärme
  - id: non_heating_electricity
    label: Kulutussähkö
    label_en: Consumer electricity
    label_sv: Konsumtionel
  - id: transportation
    label: Liikenne
    label_en: Transportation
    label_sv: Trafik
  - id: industry_and_machinery
    label: Teollisuus ja työkoneet
    label_en: Industry and machinery
    label_sv: Industri och maskiner
  - id: waste_treatment
    label: Jätteiden käsittely
    label_en: Waste treatment
    label_sv: Avfall
  - id: agriculture
    label: Maatalous
    label_en: Agriculture
    label_sv: Jordbruk
  - id: fields
    label_fi: Pellot
  - id: cattle_farming
    label_fi: Kotieläimet
  - id: machinery
    label: Työkoneet
    label_en: Machinery
    label_sv: Maskiner
  - id: industry
    label: Teollisuus
    label_en: Industry
    label_sv: Industri
    aliases: [Prosessit]
  - id: industry_fuels
    label_fi: Teollisuuden polttoaineet
    label_en: Industrial fuels
    label_sv: Industriella bränsle
    aliases: [Polttoaineet]

- id: waste_treatment
  label_fi: Jätteenkäsittely
  label_en: Waste treatment
  categories:
  - id: landfills
    label_fi: Kaatopaikka
    label_en: Landfills
    label_sv: Deponi
  - id: biowaste_composting
    label_fi: Biojätteen kompostointi
    label_en: Biowaste composting
    label_sv: Kompostering av bioavfall
  - id: waste_water_treatment
    label_fi: Jäteveden käsittely
    label_en: Wastewater treatment
    label_sv: Rening av avloppsvatten
  - id: sludge_composting
    label_fi: Jätevesilietteen kompostointi
    label_en: Sewage sludge composting
    label_sv: Kompostering av avloppsslam

nodes:

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name_fi: HSY:n päästöinventaario
  name_en: HSY emission inventory
  name_sv: HRM:s utsläppsinventering
  input_datasets: ['hsy/pks_khk_paastot']

- id: net_emissions
  name_fi: Kokonaispäästöt (scope 1+2)
  name_en: Net emissions (scope 1+2)
  name_sv: Totala utsläpp (scope 1+2)
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt/a
  is_outcome: true

- id: industry_emission_inventory
  name_en: Industry emission inventory
  type: finland.hsy.HsyEmissions
  unit: kt/a
  input_dimensions: [emission_sector, economic_sector]
  output_dimensions: [emission_sector, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: greenhouse_gas_inventory
    from_dimensions:
    - id: emission_sector
      flatten: true
  params:
    sector: Teollisuus ja työkoneet|*|_emission_sector_|_economic_sector_

- id: waste_emission_inventory
  name_en: Waste emission inventory
  type: finland.hsy.HsyEmissions
  unit: kt/a
  input_dimensions: [waste_treatment, economic_sector]
  output_dimensions: [waste_treatment, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: greenhouse_gas_inventory
    from_dimensions:
    - id: waste_treatment
      flatten: true
  params:
    sector: Jätteiden käsittely|*|_waste_treatment_|_economic_sector_

- id: agriculture_emission_inventory
  name_en: Agriculture emission inventory
  type: finland.hsy.HsyEmissions
  unit: kt/a
  input_dimensions: [emission_sector, economic_sector]
  output_dimensions: [emission_sector, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: greenhouse_gas_inventory
    from_dimensions:
    - id: emission_sector
      flatten: true
  params:
    sector: Maatalous|*|_emission_sector_|_economic_sector_

- id: industry_machinery_emissions
  name_fi: Teollisuuden ja työkoneiden päästöt
  name_en: Emissions from industry and machinery
  name_sv: Utsläpp från industri och maskiner
  type: finland.hsy.HsyEmissions
  input_dimensions: [emission_sector, economic_sector]
  output_dimensions: [emission_sector, economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Teollisuus ja työkoneet|*|_emission_sector_|_economic_sector_
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: emission_sector
      flatten: true

- id: agriculture_emissions
  name_fi: Maatalouden päästöt
  name_en: Emissions from agriculture
  name_sv: Utsläpp från jordbruket
  type: finland.hsy.HsyEmissions
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_nodes: [all_hsy_emissions]
  params:
    sector: Maatalous|*|_economic_sector_|*
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true

- id: waste_treatment_emissions
  name_fi: Jätteenkäsittelyn päästöt
  name_en: Waste treatment emissions
  name_sv: Avfallsbehandlingsutsläpp
  type: finland.hsy.HsyEmissions
  unit: kt/a
  input_dimensions: [waste_treatment, economic_sector]
  output_dimensions: [waste_treatment, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: waste_treatment
      flatten: true
  params:
    sector: Jätteiden käsittely|*|_waste_treatment_|_economic_sector_

