dimensions:

- id: emission_sector
  label_fi: Päästösektori
  label_en: Emission sector
  label_sv: Utsläppssektor
  categories:
  - id: district_heating
    label_fi: Kaukolämpö
    label_en: District heating
    label_sv: Fjärrvärme
  - id: oil_heating
    label_fi: Öljylämmitys
    label_en: Oil heating
    label_sv: Oljeuppvärmning
  - id: electric_heating
    label_fi: Sähkölämmitys
    label_en: Electric heating
    label_sv: Eluppvärmning
  - id: non_heating_electricity
    label_fi: Kulutussähkö
    label_en: Consumption electricity
    label_sv: Konsumtionsel
  - id: transportation
    label_fi: Liikenne
    label_en: Transportation
    label_sv: Trafik
  - id: industry_and_machinery
    label_fi: Teollisuus ja työkoneet
    label_en: Industry and machinery
    label_sv: Industri och arbetsmaskiner
  - id: waste_treatment
    label_fi: Jätteiden käsittely
    label_en: Waste treatment
    label_sv: Avfallsbehandling
  - id: agriculture
    label_fi: Maatalous
    label_en: Agriculture
    label_sv: Jordbruk
  - id: fields
    label_fi: Pellot
    label_en: Fields
    label_sv: Åkrar
  - id: cattle_farming
    label_fi: Kotieläimet
    label_en: Livestock
    label_sv: Boskap
  - id: machinery
    label_fi: Työkoneet
    label_en: Machinery
    label_sv: Arbetsmaskiner
  - id: industry
    label_fi: Teollisuus
    label_en: Industry
    label_sv: Industri
    aliases: [Prosessit]
  - id: industry_fuels
    label_fi: Teollisuuden polttoaineet
    label_en: Industrial fuels
    label_sv: Industriella bränslen
    aliases: [Polttoaineet]

- id: waste_treatment
  label_fi: Jätteenkäsittely
  label_en: Waste treatment
  label_sv: Avfallsbehandling
  categories:
  - id: landfills
    label_fi: Kaatopaikka
    label_en: Landfills
    label_sv: Deponier
  - id: biowaste_composting
    label_fi: Biojätteen kompostointi
    label_en: Biowaste composting
    label_sv: Kompostering av bioavfall
  - id: waste_water_treatment
    label_fi: Jäteveden käsittely
    label_en: Wastewater treatment
    label_sv: Avloppsvattenbehandling
  - id: sludge_composting
    label_fi: Jätevesilietteen kompostointi
    label_en: Sewage sludge composting
    label_sv: Kompostering av avloppsslam

nodes:

- id: industry_machinery_emissions
  name_fi: Teollisuuden ja työkoneiden päästöt
  name_en: Emissions from industry and machinery
  name_sv: Utsläpp från industri och arbetsmaskiner
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [emission_sector, economic_sector]
  output_dimensions: [emission_sector, economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    column: Päästöt
    filters:
    - rename_col: Sektori2
      value: emission_sector
    - rename_col: Sektori4
      value: economic_sector
    - rename_col: Vuosi
      value: Year
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Teollisuus ja työkoneet
    - column: Sektori3
      flatten: true
  output_nodes:
  - id: net_emissions

- id: agriculture_emissions
  name_fi: Maatalouden päästöt
  name_en: Emissions from agriculture
  name_sv: Utsläpp från jordbruket
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [emission_sector, economic_sector]
  output_dimensions: [emission_sector, economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    column: Päästöt
    filters:
    - rename_col: Sektori2
      value: emission_sector
    - rename_col: Sektori4
      value: economic_sector
    - rename_col: Vuosi
      value: Year
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Maatalous
    - column: Sektori3
      flatten: true
  output_nodes:
  - id: net_emissions

- id: waste_treatment_emissions
  name_fi: Jätteiden käsittelyn päästöt
  name_en: Waste treatment emissions
  name_sv: Utsläpp från avfallsbehandling
  type: generic.DimensionalSectorEmissions
  unit: kt/a
  input_dimensions: [waste_treatment, economic_sector]
  output_dimensions: [waste_treatment, economic_sector]
  input_nodes: [all_hsy_emissions]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true
    - id: waste_treatment
      flatten: true
  params:
    sector: Jätteiden käsittely|*|_waste_treatment_|_economic_sector_
