dimensions:
- id: diet
  label_en: Diet
  label_el: Διατροφή
  categories:
  - id: current_average
    label_en: Current average
    label_el: Τρέχων μέσος όρος
  - id: flexitarian
    label_en: Flexitarian
    label_el: Ευέλικτη χορτοφαγία
  - id: pescetarian
    label_en: Pescetarian
    label_el: Ψαροφαγία
  - id: vegetarian
    label_en: Vegetarian
    label_el: Χορτοφαγία
  - id: vegan
    label_en: Vegan
    label_el: Αυστηρή χορτοφαγία

- id: material
  label_en: Material
  label_el: Υλικό
  categories:
  - id: concrete
    label_en: Concrete
    label_el: Σκυρόδεμα
  - id: steel
    label_en: Steel
    label_el: Χάλυβας
  - id: plastics
    label_en: Plastics
    label_el: Πλαστικά
  - id: aluminium
    label_en: Aluminium
    label_el: Αλουμίνιο

nodes:

# --------------- Other emissions ----------

- id: emissions_from_other_sectors
  name_en: Emissions from other sectors
  name_el: Εκπομπές από άλλους τομείς
  type: gpc.DatasetNode
  color: '#76B7B2'
  quantity: emissions
  unit: kt/a
  input_dimensions: [scope, cost_type, ghg]
  output_dimensions: [scope, cost_type, ghg]
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: cost_type
      flatten: true
    to_dimensions:
    - id: scope
    - id: ghg
    - id: sector
      categories: [other]
  input_datasets:
  - id: gpc/athens_nzc
  params:
    sector: Emissions from other sectors

# --------------- Scope 3 ------------------

- id: building_material_shares
  name_en: Building material shares
  name_el: Μερίδια δομικών υλικών
  type: gpc.DatasetNode
  quantity: fraction
  unit: dimensionless
  input_dimensions: [material]
  output_dimensions: [material]
  input_datasets: [gpc/athens_nzc]
  params:
    sector: Materials as share of total mass

- id: building_materials_used_in_new_buildings
  name_en: Building material used in new buildings
  name_el: Δομικά υλικά που χρησιμοποιούνται σε νέα κτίρια
  type: gpc.DatasetNode
  quantity: mass
  unit: t/m**2
  input_datasets: [gpc/athens_nzc]
  params:
    sector: Tonnes material used in for new buildings (2010)

- id: building_materials_used_by_material
  name_en: Building materials used by material
  name_el: Δομικά υλικά που χρησιμοποιούνται ανά υλικό
  type: simple.MultiplicativeNode
  quantity: mass
  unit: t/m**2
  input_dimensions: [material]
  output_dimensions: [material]
  input_nodes:
  - id: building_materials_used_in_new_buildings
    tags: [non_additive]
    to_dimensions: []
  - id: building_material_shares
    to_dimensions:
    - id: material

- id: building_construction_material_use
  name_en: Building construction material use
  name_el: Χρήση υλικών κατασκευής κτιρίων
  type: simple.MultiplicativeNode
  quantity: mass
  unit: kt/a
  input_dimensions: [building_energy_class, material]
  output_dimensions: [building_energy_class, material]
  input_nodes:
  - id: new_building_stock
    to_dimensions:
    - id: building_energy_class
  - id: building_materials_used_by_material
    to_dimensions:
    - id: material

- id: tonnes_material_used_for_renovations
  name_en: Tonnes material used for renovations
  name_el: Τόνοι υλικών που χρησιμοποιούνται για ανακαινίσεις
  type: gpc.DatasetNode
  quantity: mass
  unit: t/m**2
  input_dimensions: [building_energy_class]
  output_dimensions: [building_energy_class]
  input_datasets: [gpc/athens_nzc]
  params:
  - id: sector
    value: Tonnes material used for renovations

- id: building_renovation_material_use
  name_en: Building renovation material use
  name_el: Χρήση υλικών ανακαίνισης κτιρίων
  type: simple.MultiplicativeNode
  quantity: mass
  unit: kt/a
  input_dimensions: [building_energy_class, material]
  output_dimensions: [building_energy_class, material]
  input_nodes:
  - id: renovated_building_stock
    from_dimensions:
    - id: building_energy_class
      categories: [minor_renovation, major_renovation]
    to_dimensions:
    - id: building_energy_class
  - id: tonnes_material_used_for_renovations
    to_dimensions:
    - id: building_energy_class
  - id: building_material_shares
    to_dimensions:
    - id: material

- id: building_material_use
  name_en: Building material use
  name_el: Χρήση δομικών υλικών
  type: simple.AdditiveNode
  quantity: mass
  unit: kt/a
  input_dimensions: [building_energy_class, material]
  output_dimensions: [building_energy_class, material]
  input_nodes:
  - id: building_construction_material_use
  - id: building_renovation_material_use

- id: building_material_unit_price
  name_en: Building material unit price
  name_el: Τιμή μονάδας δομικών υλικών
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [material]
  output_dimensions: [material]
  input_datasets: [gpc/athens_nzc]
  params:
    sector: Production costs per tonne

- id: building_material_cost
  name_en: Building material cost
  name_el: Κόστος δομικών υλικών
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [material, stakeholder, cost_type]
  output_dimensions: [material, stakeholder, cost_type]
  input_nodes:
  - id: building_material_use
    from_dimensions:
    - id: building_energy_class
      flatten: true
    to_dimensions:
    - id: material
  - id: building_material_unit_price
    to_dimensions:
    - id: material
  - id: new_building_cost_shares
    to_dimensions:
    - id: stakeholder
    - id: cost_type
  output_nodes:
  - id: building_cost
    from_dimensions:
    - id: material
      flatten: true
    to_dimensions:
    - id: cost_type
    - id: stakeholder
