# Generated by Django 3.2.8 on 2021-10-29 12:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('nodes', '0003_nodeconfig_data_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nodeconfig',
            old_name='body',
            new_name='description',
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='site',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instance', to='wagtailcore.site'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='site_url',
            field=models.URLField(null=True, verbose_name='Site URL'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
