# Generated by Django 3.2.9 on 2022-05-31 12:38

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0008_add_node_order_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'lead_title', 'lead_paragraph'), required_languages=(), virtual_fields=True),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'short_description', 'description'), required_languages=(), virtual_fields=True),
        ),
    ]
