# Generated by Django 3.2.16 on 2022-10-27 11:51

from django.db import migrations
import paths.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0009_update_i18n_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='identifier',
            field=paths.utils.IdentifierField(max_length=200, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
    ]
