# Generated by Django 3.2.16 on 2023-01-21 15:07

from django.db import migrations, models
import paths.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0011_add_instance_protection_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)')], default=paths.utils.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='primary_language',
            field=models.CharField(choices=[('fi', 'Finnish'), ('en', 'English'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)')], default=paths.utils.get_default_language, max_length=8),
        ),
    ]
