# Generated by Django 4.1.10 on 2023-07-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0016_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='uuid',
            field=models.UUIDField(editable=False, null=True, unique=True, verbose_name='UUID'),
        ),
    ]
