# Generated by Django 4.2.7 on 2023-11-16 14:33

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0022_add_more_node_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='body',
            field=wagtail.fields.StreamField([('card_list', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=False)), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('short_description', wagtail.blocks.CharBlock(required=False))]), required=True))])), ('paragraph', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='goal',
            field=wagtail.fields.RichTextField(blank=True, max_length=1000, null=True, verbose_name='Goal'),
        ),
    ]
