# Generated by Django 4.2.7 on 2023-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0023_increase_goal_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
