# Generated by Django 5.0.8 on 2024-09-02 23:08

import django.contrib.postgres.functions
import paths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0025_alter_instanceconfig_other_languages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='identifier',
            field=paths.utils.IdentifierField(max_length=100, unique=True, validators=[paths.utils.InstanceIdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='uuid',
            field=models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
