# Generated by Django 5.1.3 on 2024-11-25 14:32

import paths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nodes", "0027_instanceconfig_viewer_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instanceconfig",
            name="other_languages",
            field=paths.utils.ChoiceArrayField(
                base_field=models.CharField(
                    choices=paths.utils.get_supported_languages,
                    default=paths.utils.get_default_language,
                    max_length=8,
                ),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="instanceconfig",
            name="primary_language",
            field=models.CharField(
                choices=paths.utils.get_supported_languages,
                default=paths.utils.get_default_language,
                max_length=8,
            ),
        ),
    ]
