# Generated by Django 5.2 on 2025-07-21 10:18

import wagtail_color_panel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0030_nodedataset_nodeconfig_datasets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
