# Generated by Django 5.2.4 on 2025-09-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nodes', '0037_instanceconfig_reviewer_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='super_admin_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='super_admin_instances', to='auth.group'),
        ),
    ]
