# Generated by Django 6.0.3 on 2026-05-13 12:58

import django.db.models.deletion
import nodes.models
import typing
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0044_instanceconfig_is_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='owned_by',
            field=models.ForeignKey(blank=True, help_text='The user who owns this instance and has full control over it (e.g. user management).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_instances', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.CreateModel(
            name='InstanceInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=nodes.models._generate_invitation_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=nodes.models._default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_soft_deleted', models.BooleanField(default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('instance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('soft_deleted_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soft_deleted_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance invitation',
                'verbose_name_plural': 'Instance invitations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('accepted_at__isnull', True), ('is_soft_deleted', False)), fields=('instance_config', 'email'), name='unique_active_invitation_per_instance_email')],
            },
            bases=(models.Model, typing.Generic),
        ),
    ]
