# Generated by Django 6.0.3 on 2026-06-03 07:09

import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
import nodes.defs.instance_defs
import nodes.defs.node_defs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0046_instanceconfig_yaml_mtime_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='spec',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=nodes.defs.instance_defs.InstanceSpec),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='spec',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True, schema=nodes.defs.node_defs.NodeSpec),
        ),
    ]
