# Generated by Django 6.0.3 on 2026-06-10 21:39

import json

import modeltrans.fields
from django.db import migrations, models


def _backfill_owner(apps, schema_editor) -> None:
    """
    Move ``owner`` out of the stored spec JSON onto the new ``owner`` column.

    ``owner`` used to live inside ``InstanceConfig.spec`` (now the
    computation-only ``InstanceModelSpec``, which no longer has the field).
    Read the raw JSON so the value survives the schema change. Multilingual
    owners (stored as ``{lang: value}``) are split into the column +
    modeltrans ``owner_<lang>`` keys.
    """
    from django.db import connection

    InstanceConfig = apps.get_model('nodes', 'InstanceConfig')
    with connection.cursor() as cursor:
        cursor.execute('SELECT id, spec, primary_language, i18n FROM nodes_instanceconfig WHERE spec IS NOT NULL')
        rows = cursor.fetchall()

    for pk, spec_raw, primary_language, i18n_raw in rows:
        spec = json.loads(spec_raw) if isinstance(spec_raw, str) else spec_raw
        if not isinstance(spec, dict):
            continue
        owner = spec.get('owner')
        if not owner:
            continue
        i18n = json.loads(i18n_raw) if isinstance(i18n_raw, str) else (i18n_raw or {})
        if isinstance(owner, dict):
            owner_val = owner.get(primary_language) or next(iter(owner.values()), '')
            for lang, val in owner.items():
                if lang != primary_language and val:
                    i18n[f'owner_{lang}'] = val
        else:
            owner_val = str(owner)
        InstanceConfig.objects.filter(pk=pk).update(owner=owner_val, i18n=i18n)


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0047_instanceconfig_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='owner',
            field=models.CharField(blank=True, default='', help_text='Display name of the organization that owns this instance.', max_length=200, verbose_name='Owner name'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'owner', 'lead_title', 'lead_paragraph'), required_languages=(), virtual_fields=True),
        ),
        migrations.RunPython(_backfill_owner, migrations.RunPython.noop),
    ]
