# Generated by Codex on 2026-06-26

from urllib.parse import urlparse

import django.db.models.deletion
from django.db import migrations, models


def _backfill_root_page_and_hostnames(apps, schema_editor) -> None:  # noqa: C901
    InstanceConfig = apps.get_model('nodes', 'InstanceConfig')
    InstanceHostname = apps.get_model('nodes', 'InstanceHostname')
    Site = apps.get_model('wagtailcore', 'Site')

    def ensure_hostname(instance_id: int, hostname: str, base_path: str) -> None:
        hostname = hostname.lower()
        base_path = base_path.rstrip('/')

        existing = InstanceHostname.objects.filter(instance_id=instance_id, hostname=hostname).first()
        if existing is not None:
            if existing.base_path != base_path and not InstanceHostname.objects.filter(
                hostname=hostname,
                base_path=base_path,
            ).exists():
                existing.base_path = base_path
                existing.save(update_fields=['base_path'])
            return

        if InstanceHostname.objects.filter(hostname=hostname, base_path=base_path).exists():
            return

        InstanceHostname.objects.create(instance_id=instance_id, hostname=hostname, base_path=base_path)

    for ic in InstanceConfig.objects.all().iterator():
        if ic.site_id is not None:
            site = Site.objects.filter(pk=ic.site_id).first()
            if site is not None and ic.root_page_id is None:
                ic.root_page_id = site.root_page_id
                ic.save(update_fields=['root_page'])

        route_url = ic.site_url
        if route_url:
            parts = urlparse(route_url)
            if parts.hostname:
                ensure_hostname(ic.pk, parts.hostname, parts.path)
                continue

        if ic.site_id is not None:
            site = Site.objects.filter(pk=ic.site_id).first()
            if site is not None:
                ensure_hostname(ic.pk, site.hostname, '')


def _ensure_single_default_site(apps, schema_editor) -> None:
    Page = apps.get_model('wagtailcore', 'Page')
    Site = apps.get_model('wagtailcore', 'Site')

    root_page = Page.objects.filter(depth=1).order_by('path').first()
    if root_page is None:
        return

    default_site = Site.objects.filter(hostname='localhost', port=80).first()
    if default_site is None:
        default_site = Site.objects.create(
            hostname='localhost',
            port=80,
            site_name='Kausal Paths',
            root_page_id=root_page.pk,
            is_default_site=True,
        )
    else:
        default_site.site_name = default_site.site_name or 'Kausal Paths'
        default_site.root_page_id = root_page.pk
        default_site.is_default_site = True
        default_site.save(update_fields=['site_name', 'root_page', 'is_default_site'])

    Site.objects.exclude(pk=default_site.pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0050_instanceconfig_is_hidden'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='root_page',
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='instance_config_root',
                to='wagtailcore.page',
            ),
        ),
        migrations.RunPython(_backfill_root_page_and_hostnames, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='instanceconfig',
            name='site',
        ),
        migrations.RemoveField(
            model_name='instanceconfig',
            name='site_url',
        ),
        migrations.RunPython(_ensure_single_default_site, migrations.RunPython.noop),
    ]
