# Generated by Django 6.0.3 on 2026-07-31

import json
import re
from typing import Any

import modeltrans.fields
from django.db import migrations, models
from markdown_it import MarkdownIt


_SPEC_METADATA_FIELDS = {
    'uuid',
    'identifier',
    'name',
    'short_name',
    'description',
    'kind',
    'color',
    'order',
    'is_visible',
}

_MARKDOWN = MarkdownIt('commonmark', {'html': True})


def _modeltrans_language(language: str) -> str:
    match = re.fullmatch(r'([a-zA-Z]{2})(?:[-_]([a-zA-Z]{2}))?', language)
    if match is None:
        return language
    base, region = match.groups()
    return f'{base.lower()}_{region.lower()}' if region else base.lower()


def _translated_column(
    value: Any,
    field_name: str,
    primary_language: str,
    i18n: dict[str, Any],
    *,
    render_markdown: bool = False,
) -> str | None:
    if value is None:
        return None
    def prepare(raw: Any) -> str:
        text = str(raw)
        return _MARKDOWN.render(text) if render_markdown else text

    if not isinstance(value, dict):
        return prepare(value)
    primary_value = value.get(primary_language) or next((val for val in value.values() if val), None)
    for language, translated in value.items():
        key = f'{field_name}_{_modeltrans_language(language)}'
        if language != primary_language and translated:
            # The legacy spec won over the ORM column at runtime, so its
            # translations must win during the ownership transfer too.
            i18n[key] = prepare(translated)
    return prepare(primary_value) if primary_value is not None else None


def split_node_metadata_from_spec(apps, schema_editor) -> None:
    """Materialize legacy runtime metadata in columns, then prune it from spec."""
    NodeConfig = apps.get_model('nodes', 'NodeConfig')
    table = NodeConfig._meta.db_table
    instance_table = apps.get_model('nodes', 'InstanceConfig')._meta.db_table
    quote = schema_editor.quote_name

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f'SELECT n.id, n.spec, n.name, n.color, n.order, n.is_visible, '  # noqa: S608
            'n.short_description, n.i18n, i.primary_language '
            f'FROM {quote(table)} n JOIN {quote(instance_table)} i ON n.instance_id = i.id '
            'WHERE n.spec IS NOT NULL'
        )
        rows = cursor.fetchall()

        for (
            pk,
            spec_raw,
            current_name,
            current_color,
            current_order,
            current_is_visible,
            current_short_description,
            i18n_raw,
            primary_language,
        ) in rows:
            spec = json.loads(spec_raw) if isinstance(spec_raw, str) else spec_raw
            if not isinstance(spec, dict):
                continue
            i18n = json.loads(i18n_raw) if isinstance(i18n_raw, str) else dict(i18n_raw or {})

            # Preserve the values the old DB serializer actually exposed:
            # spec metadata took precedence, with ORM columns as fallbacks.
            name = current_name
            if spec.get('name'):
                name = _translated_column(spec['name'], 'name', primary_language, i18n)
            short_name = _translated_column(spec.get('short_name'), 'short_name', primary_language, i18n)
            short_description = current_short_description
            if not current_short_description:
                short_description = _translated_column(
                    spec.get('description'),
                    'short_description',
                    primary_language,
                    i18n,
                    render_markdown=True,
                )
            color = spec.get('color') or current_color
            # NodeConfig.update_node_from_config overrode the parsed spec order
            # when the ORM column was populated, unlike the other display fields.
            order = current_order if current_order is not None else spec.get('order')
            is_visible = bool(current_is_visible and spec.get('is_visible', True))
            computation_spec = {key: value for key, value in spec.items() if key not in _SPEC_METADATA_FIELDS}
            cursor.execute(
                f'UPDATE {quote(table)} SET name = %s, short_name = %s, short_description = %s, '  # noqa: S608
                'color = %s, "order" = %s, is_visible = %s, i18n = %s, spec = %s '
                'WHERE id = %s',
                [
                    name,
                    short_name,
                    short_description,
                    color,
                    order,
                    is_visible,
                    json.dumps(i18n),
                    json.dumps(computation_spec),
                    pk,
                ],
            )


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0054_edge_transformations_vocabulary'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='short_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='i18n',
            field=modeltrans.fields.TranslationField(
                fields=('name', 'short_name', 'short_description', 'description', 'goal'),
                required_languages=(),
                virtual_fields=True,
            ),
        ),
        migrations.RunPython(split_node_metadata_from_spec, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='nodeconfig',
            name='node_type',
        ),
    ]
