# Generated by Django 6.0.3 on 2026-07-31

import json
import re

from django.db import migrations, models


_LANGUAGE_SUFFIX = re.compile(r'_(?P<base>[a-zA-Z]{2})(?:[-_](?P<region>[a-zA-Z]{2}))?$')


def normalize_node_i18n_keys(apps, schema_editor) -> None:
    """Normalize legacy YAML-style locale suffixes to modeltrans format."""
    NodeConfig = apps.get_model('nodes', 'NodeConfig')
    table = schema_editor.quote_name(NodeConfig._meta.db_table)

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f'SELECT id, i18n FROM {table} WHERE i18n IS NOT NULL')  # noqa: S608
        for pk, raw_i18n in cursor.fetchall():
            i18n = json.loads(raw_i18n) if isinstance(raw_i18n, str) else dict(raw_i18n or {})
            normalized: dict[str, str] = {}
            for key, value in i18n.items():
                match = _LANGUAGE_SUFFIX.search(key)
                if match is None:
                    normalized[key] = value
                    continue
                base = match.group('base').lower()
                region = match.group('region')
                language = f'{base}_{region.lower()}' if region else base
                normalized[f'{key[: match.start()]}_{language}'] = value
            if normalized != i18n:
                cursor.execute(
                    f'UPDATE {table} SET i18n = %s WHERE id = %s',  # noqa: S608
                    [json.dumps(normalized), pk],
                )


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0055_nodeconfig_metadata_and_computation_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeconfig',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Order'),
        ),
        migrations.RunPython(normalize_node_i18n_keys, migrations.RunPython.noop),
    ]
