# Generated by Django 6.0.3 on 2026-08-03

import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0056_nodeconfig_signed_order_and_i18n'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                (
                    'source',
                    django_choices_field.fields.TextChoicesField(
                        choices=[('auto', 'Auto'), ('user', 'User')],
                        default='auto',
                        max_length=4,
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
                (
                    'last_modified_by',
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Last modified by',
                    ),
                ),
                (
                    'node',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='layout',
                        to='nodes.nodeconfig',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Node layout',
                'verbose_name_plural': 'Node layouts',
                'ordering': ['node'],
            },
        ),
    ]
