# Generated by Django 6.0.3 on 2026-08-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0061_backfill_input_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this instance is active or soft-deleted.'),
        ),
    ]
