# Generated by Django 6.1 on 2026-08-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0064_nodeconfig_is_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmaterialization',
            name='validation_violations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
