# Generated by Django 6.1 on 2026-08-16

import uuid

from django.db import migrations, models


def backfill_target_uuid(apps, schema_editor):
    InstanceModelLogEntry = apps.get_model('nodes', 'InstanceModelLogEntry')
    pending = []
    for entry in InstanceModelLogEntry.objects.filter(target_uuid__isnull=True).iterator(chunk_size=1000):
        raw_uuid = (entry.data or {}).get('target_uuid')
        if raw_uuid is None:
            continue
        try:
            entry.target_uuid = uuid.UUID(str(raw_uuid))
        except ValueError:
            continue
        pending.append(entry)
        if len(pending) == 1000:
            InstanceModelLogEntry.objects.bulk_update(pending, ['target_uuid'])
            pending.clear()
    if pending:
        InstanceModelLogEntry.objects.bulk_update(pending, ['target_uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0066_instanceconfig_database_source_spec'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancemodellogentry',
            name='target_uuid',
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text='Stable UUID of the affected object; retained after the target row is deleted.',
                null=True,
            ),
        ),
        migrations.RunPython(backfill_target_uuid, migrations.RunPython.noop),
    ]
