# Generated by Django 6.1 on 2026-09-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0073_drop_binding_dataset_spec_and_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='in_customer_use',
            field=models.BooleanField(
                default=False,
                help_text='Whether this instance is in customer use, including startup computation and operational monitoring.',
                verbose_name='in customer use',
            ),
        ),
    ]
