# Generated by Django 6.1 on 2026-09-22 15:42

import django.contrib.postgres.functions
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import nodes.instance_serialization
import nodes.template_settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datasets', '0037_source_reference_targets_exactly_one'),
        ('nodes', '0074_instanceconfig_in_customer_use'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='node_settings',
            field=django_pydantic_field.fields.PydanticSchemaField(
                blank=True,
                config=None,
                default=list,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                schema=django_pydantic_field.compat.django.GenericContainer(
                    list, (nodes.template_settings.InheritedNodeSettings,)
                ),
            ),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='template_revision',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.revision'
            ),
        ),
        migrations.CreateModel(
            name='InputPortBindingSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'uuid',
                    models.UUIDField(
                        db_default=django.contrib.postgres.functions.RandomUUID(),
                        editable=False,
                        unique=True,
                        verbose_name='UUID',
                    ),
                ),
                ('node_uuid', models.UUIDField()),
                ('port_uuid', models.UUIDField()),
                (
                    'bindings',
                    django_pydantic_field.fields.PydanticSchemaField(
                        blank=True,
                        config=None,
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        schema=django_pydantic_field.compat.django.GenericContainer(
                            list, (nodes.instance_serialization.InputBindingSnapshot,)
                        ),
                    ),
                ),
                (
                    'instance',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='binding_overrides', to='nodes.instanceconfig'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='InputPortBindingReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'dataset',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='input_binding_references',
                        to='datasets.dataset',
                    ),
                ),
                (
                    'node',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='input_binding_references',
                        to='nodes.nodeconfig',
                    ),
                ),
                (
                    'override',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='references', to='nodes.inputportbindingset'
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='inputportbindingset',
            constraint=models.UniqueConstraint(
                fields=('instance', 'node_uuid', 'port_uuid'), name='unique_instance_port_override'
            ),
        ),
        migrations.AddConstraint(
            model_name='inputportbindingreference',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('dataset__isnull', False), ('node__isnull', True)),
                    models.Q(('dataset__isnull', True), ('node__isnull', False)),
                    _connector='OR',
                ),
                name='input_binding_reference_one_source',
            ),
        ),
    ]
