# Generated by Django 6.1 on 2026-09-22 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('datasets', '0037_source_reference_targets_exactly_one'),
        ('nodes', '0075_template_revision_and_bindings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='inputportbindingreference',
            name='input_binding_reference_one_source',
        ),
        migrations.AddField(
            model_name='inputportbindingreference',
            name='metric',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasets.datasetmetric'
            ),
        ),
        migrations.AlterField(
            model_name='inputportbindingreference',
            name='dataset',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='datasets.dataset'
            ),
        ),
        migrations.AlterField(
            model_name='inputportbindingreference',
            name='node',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='nodes.nodeconfig'
            ),
        ),
        migrations.AddConstraint(
            model_name='inputportbindingreference',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('dataset__isnull', False), ('metric__isnull', True), ('node__isnull', True)),
                    models.Q(('dataset__isnull', True), ('metric__isnull', True), ('node__isnull', False)),
                    models.Q(('dataset__isnull', True), ('metric__isnull', False), ('node__isnull', True)),
                    _connector='OR',
                ),
                name='input_binding_reference_one_source',
            ),
        ),
    ]
