# Generated by Django 6.1 on 2026-09-27 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nodes', '0077_scope_schema_scoped_placeholder_datasets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='editor_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='editor_instances', to='auth.group'),
        ),
        migrations.AddField(
            model_name='instanceinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], default='admin', max_length=10),
        ),
        migrations.CreateModel(
            name='InstanceMemberAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=10)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('retention_until', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_instance_memberships', to=settings.AUTH_USER_MODEL)),
                ('instance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_assignments', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_instance_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instance_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstanceMemberEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=20)),
                ('old_role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=10, null=True)),
                ('new_role', models.CharField(blank=True, choices=[('admin', 'Admin'), ('editor', 'Editor'), ('reviewer', 'Reviewer'), ('viewer', 'Viewer')], max_length=10, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='nodes.instancememberassignment')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='instancememberassignment',
            constraint=models.UniqueConstraint(fields=('instance_config', 'user'), name='unique_instance_member_assignment'),
        ),
        migrations.AddConstraint(
            model_name='instancememberassignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('retention_until__isnull', True), ('suspended_at__isnull', True)), models.Q(('retention_until__isnull', False), ('suspended_at__isnull', False)), _connector='OR'), name='instance_member_suspension_has_retention'),
        ),
    ]
