# Generated by Django 6.1 on 2026-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0079_backfill_instance_member_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancememberevent',
            name='retention_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instancememberevent',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
