# Generated by Django 6.1 on 2026-09-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0080_instancememberevent_retention_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetmaterialization',
            name='validation_payload_version',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
