# Generated by Django 6.1 on 2026-10-01 17:56

import django.core.serializers.json
import django.db.models.deletion
import nodes.defs.instance_defs
import nodes.fields
from django.db import migrations, models


def migrate_authoring_inputs(apps, schema_editor):  # noqa: C901
    from django.db.models.functions import Cast

    from nodes.defs.instance_defs import InstanceModelSpec

    connection_alias = schema_editor.connection.alias
    InstanceConfig = apps.get_model('nodes', 'InstanceConfig')
    Revision = apps.get_model('wagtailcore', 'Revision')
    TemplatePin = apps.get_model('nodes', 'InstanceRevisionTemplatePin')
    instances = InstanceConfig.objects.using(connection_alias).annotate(
        stored_definition=Cast('spec', output_field=models.JSONField()),
    )
    for instance in instances.iterator():
        data = instance.stored_definition
        if not isinstance(data, dict) or 'overrides' not in data:
            continue
        data = dict(data)
        overrides = data.pop('overrides') or {}
        if instance.template_revision_id is not None:
            for field in ('terms', 'theme_identifier', 'sample_size', 'features', 'dataset_repo'):
                data.pop(field, None)
        for field in ('terms', 'theme_identifier', 'sample_size'):
            if overrides.get(field) is not None:
                data[field] = overrides[field]
        data['features'] = {**data.get('features', {}), **overrides.get('features', {})}
        scenarios = list(data.get('scenarios', []))
        for identifier, values in overrides.get('scenarios', {}).items():
            scenarios.append({'id': identifier, 'name': '', **values})
        data['scenarios'] = scenarios
        if any(
            overrides.get(field) is not None
            for field in ('result_excels', 'pages', 'impact_overviews', 'normalizations', 'action_groups')
        ):
            raise ValueError('Explicit replacement lists require migration to additive declarations')
        spec = InstanceModelSpec.model_validate(data)
        InstanceConfig.objects.using(connection_alias).filter(pk=instance.pk).update(spec=spec)
    # Older publications were flattened, but their template pins are still
    # needed to reconstruct editable local definitions when restoring them.
    valid_revision_ids = set(Revision.objects.using(connection_alias).values_list('pk', flat=True))
    for revision in Revision.objects.using(connection_alias).filter(content__model_snapshot__isnull=False).iterator():
        snapshot = (revision.content.get('model_snapshot') or {}).get('structured') or {}
        template_id = snapshot.get('template_revision_id')
        if template_id in valid_revision_ids:
            TemplatePin.objects.using(connection_alias).get_or_create(
                instance_revision_id=revision.pk,
                defaults={'template_revision_id': template_id},
            )


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0082_sparse_template_specs'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='spec',
            field=nodes.fields.InstanceSpecField(
                blank=True,
                config=None,
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                null=True,
                schema=nodes.defs.instance_defs.InstanceModelSpec,
            ),
        ),
        migrations.CreateModel(
            name='InstanceRevisionTemplatePin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'instance_revision',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='instance_template_pin',
                        to='wagtailcore.revision',
                    ),
                ),
                (
                    'template_revision',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='dependent_instance_pins',
                        to='wagtailcore.revision',
                    ),
                ),
            ],
        ),
        migrations.RunPython(migrate_authoring_inputs),
    ]
