# Generated by Django 5.2 on 2025-06-17 13:32

import django.db.models.deletion
import image_cropping.fields
import kausal_common.people.models
import modeltrans.fields
import uuid
import wagtail.search.index
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='title')),
                ('postal_address', models.TextField(blank=True, max_length=100, null=True, verbose_name='postal address')),
                ('image', models.ImageField(blank=True, height_field='image_height', upload_to=kausal_common.people.models.image_upload_path, verbose_name='image', width_field='image_width')),
                ('image_cropping', image_cropping.fields.ImageRatioField('image', '1280x720', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='image cropping')),
                ('image_height', models.PositiveIntegerField(editable=False, null=True)),
                ('image_width', models.PositiveIntegerField(editable=False, null=True)),
                ('avatar_updated_at', models.DateTimeField(editable=False, null=True)),
                ('i18n', modeltrans.fields.TranslationField(fields=('title',), required_languages=(), virtual_fields=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_persons', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('organization', models.ForeignKey(help_text="What is this person's organization", on_delete=django.db.models.deletion.CASCADE, related_name='people', to='orgs.organization', verbose_name='organization')),
                ('user', models.OneToOneField(blank=True, editable=False, help_text='Set if the person has an user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
