# Generated by Django 5.2 on 2025-07-16 12:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0017_datasetsourcereference_uuid'),
        ('nodes', '0032_alter_instanceconfig_organization'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_groups', to='nodes.instanceconfig')),
            ],
        ),
        migrations.CreateModel(
            name='PersonGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons_edges', to='people.persongroup')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_edges', to='people.person')),
            ],
            options={
                'verbose_name': 'Group member',
                'verbose_name_plural': 'Group members',
            },
        ),
        migrations.AddField(
            model_name='persongroup',
            name='persons',
            field=models.ManyToManyField(related_name='person_groups', through='people.PersonGroupMember', to='people.person'),
        ),
        migrations.CreateModel(
            name='DatasetSchemaPersonPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')])),
                ('object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_permissions', to='datasets.datasetschema')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.person')),
            ],
            options={
                'unique_together': {('person', 'object')},
            },
        ),
        migrations.CreateModel(
            name='DatasetSchemaGroupPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')])),
                ('object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_permissions', to='datasets.datasetschema')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.persongroup')),
            ],
            options={
                'unique_together': {('group', 'object')},
            },
        ),
        migrations.AddConstraint(
            model_name='persongroup',
            constraint=models.UniqueConstraint(fields=('instance', 'name'), name='unique_person_group_name_per_instance'),
        ),
    ]
