# Generated by Django 5.2.4 on 2025-08-17 16:07

from django.db import migrations


def get_user_organization(Organization, user):  # noqa: N803
    if '@kausal' in user.email.lower():
        return Organization.objects.get(name='Kausal')

    extra = getattr(user, 'extra', None)
    framework_roles = getattr(extra, 'framework_roles', [])
    if any(
        getattr(role, 'framework_id', None) == 'nzc' for role in framework_roles
    ):
        return Organization.objects.get(name='NetZeroCities')

    return Organization.objects.get(name='Default Organization')


def create_persons(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Organization = apps.get_model('orgs', 'Organization')
    Person = apps.get_model('people', 'Person')
    for user in User.objects.all():
        org = get_user_organization(Organization, user)
        Person.objects.get_or_create(user=user, defaults={
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'organization': org,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_alter_person_id'),
        ('nodes', '0035_create_instanceconfig_organizations'),
    ]

    operations = [
        migrations.RunPython(create_persons, migrations.RunPython.noop)
    ]
