# Generated by Django 5.2.4 on 2025-10-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_create_persons_for_all_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_hash',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='image_msgraph_etag',
            field=models.CharField(editable=False, max_length=128, null=True),
        ),
    ]
