# Generated by Django 6.0.2 on 2026-04-02 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orgs", "0007_alter_organization_abbreviation_and_more"),
        ("people", "0005_persongroup_persongroupmember_persongroup_persons_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datasetschemagrouppermission",
            options={"ordering": ["object", "group"]},
        ),
        migrations.AlterModelOptions(
            name="datasetschemapersonpermission",
            options={"ordering": ["object", "person"]},
        ),
        migrations.AlterField(
            model_name="person",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people",
                to="orgs.organization",
                verbose_name="organization",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Job title or role of this person",
                max_length=100,
                null=True,
                verbose_name="title",
            ),
        ),
    ]
