# Generated by Django 6.1 on 2026-08-13 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('people', '0006_alter_datasetschemagrouppermission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={
                'ordering': ['last_name', 'first_name', 'id'],
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.AlterModelOptions(
            name='persongroup',
            options={'ordering': ['instance', 'name']},
        ),
        migrations.AlterModelOptions(
            name='persongroupmember',
            options={
                'ordering': ['group', 'person'],
                'verbose_name': 'Group member',
                'verbose_name_plural': 'Group members',
            },
        ),
    ]
