# Generated by Django 6.1 on 2026-08-13 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0007_alter_organization_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='namespace',
            options={'ordering': ['identifier'], 'verbose_name': 'Namespace', 'verbose_name_plural': 'Namespaces'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['path'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationclass',
            options={
                'ordering': ['name'],
                'verbose_name': 'Organization class',
                'verbose_name_plural': 'Organization classes',
            },
        ),
        migrations.AlterModelOptions(
            name='organizationidentifier',
            options={
                'ordering': ['organization', 'namespace'],
                'verbose_name': 'Organization identifier',
                'verbose_name_plural': 'Organization identifiers',
            },
        ),
    ]
