# Generated by Django 6.1 on 2026-09-19 16:37

from django.db import migrations, models


def copy_location_to_coordinates(apps, schema_editor):
    organization = apps.get_model('orgs', 'Organization')
    table = schema_editor.quote_name(organization._meta.db_table)
    schema_editor.execute(
        f'UPDATE {table} SET latitude = ST_Y(location), longitude = ST_X(location) WHERE location IS NOT NULL'  # noqa: S608 -- table is quoted model metadata
    )


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0008_alter_namespace_options_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='longitude'),
        ),
        migrations.RunPython(copy_location_to_coordinates, migrations.RunPython.noop),
    ]
