# Generated by Django 6.1 on 2026-09-19 18:31

import django.contrib.gis.db.models.fields
import django.core.validators
from django.conf import settings
from django.db import migrations, models


def reconcile_location_to_coordinates(apps, schema_editor):
    organization = apps.get_model('orgs', 'Organization')
    table = schema_editor.quote_name(organization._meta.db_table)
    schema_editor.execute(
        f'UPDATE {table} SET latitude = ST_Y(location), longitude = ST_X(location) WHERE location IS NOT NULL'  # noqa: S608 -- table is quoted model metadata
    )


class Migration(migrations.Migration):
    dependencies = [
        ('orgs', '0009_add_organization_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(reconcile_location_to_coordinates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='organization',
            name='latitude',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)],
                verbose_name='latitude',
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, editable=False, null=True, srid=4326, verbose_name='location'
            ),
        ),
        migrations.AlterField(
            model_name='organization',
            name='longitude',
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)],
                verbose_name='longitude',
            ),
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(('latitude__isnull', True), ('longitude__isnull', True)),
                    models.Q(
                        ('latitude__gte', -90),
                        ('latitude__isnull', False),
                        ('latitude__lte', 90),
                        ('longitude__gte', -180),
                        ('longitude__isnull', False),
                        ('longitude__lte', 180),
                    ),
                    _connector='OR',
                ),
                name='orgs_organization_valid_coordinates',
            ),
        ),
    ]
