id: bayreuth-bisko  # defines which instance is updated
default_language: de
supported_languages: [en]
site_url: https://bayreuth-bisko.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 042ea36e00165e5960343bcbf5b7aa14cdc4f549
  dvc_remote: kausal-s3
name_de: Bayreuth Klima-Monitor-BISKO
name_en: Bayreuth Climate Monitor BISKO
owner: Bayreuth Stadt
theme_identifier: de-bayreuth
target_year: 2035
model_end_year: 2050
reference_year: 1990
minimum_historical_year: 1990
maximum_historical_year: 2023
emission_unit: kt_co2e/a
features:
  baseline_visible_in_graphs: true
  use_datasets_from_db: true
  show_explanations: true
  show_category_warnings: true

include:
- file: modules/bisko/model.yaml
  allow_override: true
  dataset_replacements:
  - from: bisko/final_energy
    to: bayreuth/final_energy
  - from: bisko/historical_emissions
    to: bayreuth/historical_emissions
  - from: bisko/passenger_kilometers
    to: bayreuth/passenger_kilometers
  - from: bisko/vehicle_energy
    to: bayreuth/vehicle_energy

#//////  Parameters  ////////////////////////////////////////////////////////////////////////////////////////////////////
params:

- id: weather_correction
  label_de: Wetterkorrektur durchführen?
  label_en: Perform weather correction?
  value: false
  is_customizable: true
  is_visible: true
- id: municipality_name
  label_en: Municipality name
  label_de: Gemeindename
  value: Bayreuth
  is_customizable: true
  is_visible: true
- id: ags_number
  label_en: AGS number
  label_de: AGS-Nummer
  value: '9462000' # Leading zero has dropped from the dataset.
  is_customizable: false
  is_visible: false
- id: use_national_values
  label_en: Use national rather than local electricity emission factors (BISKO)
  label_de: Verwenden Sie nationale statt lokaler Stromemissionsfaktoren 
    (BISKO).
  value: true
  is_visible: true
  is_customizable: true
- id: use_mileage
  label_en: Use BISKO mileage statistics rather than own energy data for 
    transport
  label_de: Nutzen Sie die BISKO-Transportstatistiken anstatt der eigenen 
    Energieverbrauchsdaten für den Transport.
  value: true
  is_visible: true
  is_customizable: true
- id: use_local_values # FIXME Make connection to district heating emission factors dataset.
  label_en: Use local rather than national district heating emission factors 
    (BISKO)
  label_de: Verwenden Sie lokale statt nationale Fernwärmeemissionsfaktoren 
    (BISKO).
  value: true
  is_visible: true
  is_customizable: true


#//////  Result Excels  ///////////////////////////////////////////////////////////////////////////////////////////////////
result_excels:
- base_excel_url: 
    https://docs.google.com/spreadsheets/d/13URk1zrbyu5Dyjw-w7tIiaAlrERNul-L/export?format=xlsx
  name_de: Stadtspezifische Werte aus BISKO-Datensätzen und anderen Quellen
  name_en: City-specific values from BISKO datasets and elsewhere
  node_ids:
  - weather_correction
  - final_energy_use
  - final_energy_use_data_quality
  # - final_municipal_facilities_energy_use_by_type
  # - municipal_fleet_energy
  - historical_emissions
  - end_energy_emission_factors
  - electricity_production_emission_factors
  - emission_factors_without_fuel_data
  - emission_factors_for_district_heating_by_generic_fuel
  - vehicle_kilometers_ifeu
  - other_transport_energy



#//////  Nodes  ///////////////////////////////////////////////////////////////////////////////////////////////////

nodes:
- id: sector_index   # Translates BISKO categories to Wärme/Strom/Verkehr sectors. TRUE for any allowed combi of sector and energy carrier
  name_de: Sektor Index
  name_en: Sector index
  type: generic.GenericNode
  quantity: ratio
  unit: dimensionless
  input_dimensions: [sector, energy_carrier]
  output_dimensions: [sector, energy_carrier]
  input_datasets:
  - id: potsdam/sector_index
    column: sector_index


- id: total_emissions
  name_de: Gesamtemissionen
  name_en: Total Emissions
  type: formula.FormulaNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [sector, energy_carrier]
  output_dimensions: [sector, energy_carrier]
  input_nodes:
  - id: sector_index
  - id: municipal_facilities_emissions
  - id: commerce_trade_services_emissions
  - id: transport_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true    # sums up all vehicle types
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: energy_carrier
  - id: private_household_emissions
  - id: industry_emissions
  params:
  - id: formula
    value: sector_index * sum_dim(municipal_facilities_emissions + commerce_trade_services_emissions + transport_emissions + private_household_emissions + industry_emissions, sector)  # does the same as from_dimensions flatten:true


- id: private_household_emissions
  name_de: Wärme Emissionen
  name_en: Heating Emissions
  type: generic.GenericNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [sector, energy_carrier]
  output_dimensions: [sector, energy_carrier]
  input_nodes:
  - id: total_emissions
    from_dimensions:
    - id: sector
      categories: [heating]
  output_nodes:
  - id: net_emissions


- id: transport_emissions2
  name_de: Verkehr Emissionen
  name_en: Transport Emissions
  type: generic.GenericNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [sector, energy_carrier]
  output_dimensions: [sector, energy_carrier]
  input_nodes:
  - id: total_emissions
    from_dimensions:
    - id: sector
      categories: [transport]
  output_nodes:
  - id: net_emissions


- id: electricity_emissions
  name_de: Strom Emissionen
  name_en: Electricity Emissions
  type: generic.GenericNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [sector, energy_carrier]
  output_dimensions: [sector, energy_carrier]
  input_nodes:
  - id: total_emissions
    from_dimensions:
    - id: sector
      categories: [electricity]
  output_nodes:
  - id: net_emissions

# create copy of bisko sectors, but have to remove output nodes so that they don't double-feed into the net_emissions node (from bisko model file)



pages:
- id: home
  name_de: Bayreuth Treibhausgasbilanz
  name_en: Bayreuth Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Treibhausgasbilanz und -prognosen
  lead_paragraph: Historische Treibhausgasemissionen der Stadt Bayreuth und Prognosen für die Szenarien "Business as Usual" und "Klimschutzmaßnahmen erfolgreich umgesetzt".

scenarios:

- id: baseline
  name_de: Business as Usual
  name_en: Business as Usual

- id: default
  default: true
  all_actions_enabled: true
  name_de: Integriertes Klimaschutzkonzept
  name_en: Integrated Climate Protection Concept


