id: espoo
default_language: fi
supported_languages: [en]
framework: hsy
site_url: https://espoo.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: bf422ab63b0b33090925b2a141d7d275687355a1
name: Hiilineutraali Espoo 2030
name_en: Carbon-neutral Espoo 2030
owner: Espoon kaupunki
owner_en: City of Espoo
theme_identifier: espoo-ilmasto
emission_unit: kt/a
target_year: 2030
reference_year: 1990
minimum_historical_year: 2000
params:
- id: municipality_name
  value: Espoo

emission_sectors:
- id: net_emissions
  name: Kokonaispäästöt (scope 2)
  name_en: Net emissions (scope 2)
  target_year_goal: 245

- id: building_heating_emissions
  color: '#ff4f57'

- id: consumer_electricity_emissions
  color: '#0047b6'

- id: transport_emissions
  color: '#014B30'

nodes:
- id: population
  type: finland.Population
  name: Väestö

- id: all_hsy_emissions
  type: finland.hsy.HsyNode
  name: HSY:n päästöinventaario

- id: waste_treatment_impact_per_person
  name: Jätteenkäsittelyn päästöt per henkilö
  name_en: Waste treatment emissions per person
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/cap/a
  historical_values: [[2000, 0]]

- id: waste_treatment_impact
  name: Jätteenkäsittelyn toimenpiteiden vaikutus
  name_en: Waste treatment action impact
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: kt/a
  input_nodes:
  - population
  - waste_treatment_impact_per_person
  output_nodes:
  - waste_treatment_emissions


#- id: electricity_production_emission_factor
#  type: simple.AdditiveNode
#  name: Kansallisen sähköntuotannon päästökerroin
#  unit: g/kWh
#  quantity: emission_factor
#  input_nodes:
#  - consumer_electricity_residence_emission_factor

pages:
- id: home
  name: Hiilineutraali Espoo -päästöskenaario
  path: /
  type: emission
  node: net_emissions
  lead_title: Espoon päästöskenaariot
  lead_title_en: Espoo emission scenarios
  lead_paragraph: Espoon päästöskenaariot visualisoi Espoon kasvihuonekaasupäästöjen
    kehityksen. Voit tarkastella, mistä Espoon kaupungin alueen päästöt syntyvät ja
    kuinka niiden ennustetaan muuttuvan vuoteen 2030 mennessä. Valittavana on peruskehitys-skenaario,
    Hiilineutraali Espoo -tiekartan mukainen skenaario ja skenaario, jota voit itse
    muokata. Hiilineutraaliksi pääseminen edellyttää vielä lisää toimia, ja niiden
    riittävyyttä arvioidaan jatkossa tämän työkalun avulla.

actions:
- id: city_building_heat_optimization
  name: Kaupungin kiinteistöjen lämmityksen optimointi
  name_en: Optimization of heating systems in city-owned buildings
  type: simple.CumulativeAdditiveAction
  quantity: energy
  output_nodes:
  - district_heating_services_energy
  forecast_values: [[2023, -8], [2025, -16], [2026, -4], [2027, -4], [2028, -7],
    [2029, -14], [2030, -6]]
  unit: GWh/a

- id: agriculture_actions
  name: Maatalouden toimet
  name_en: Agricultural actions
  description: 'Maaralouden päästöjen kehityksen osalta laskennassa on tehty seuraavat oletukset. 
    Pessimistinen skenaario: Päästöjen oletetaan pysyvän muuttumattomana aikavälillä 2021-2035. 
    Suomi2035-skenaario: Päästöjen oletetaan laskevan 11 prosenttia vuoden 2020 tasosta vuoteen 2035 mennessä. 
    HNE2030-skenaario: Päästöjen oletetaan kehittyvän Suomi 2035 –skenaarion oletusten mukaisesti.'
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  output_nodes:
  - agriculture_emissions
  forecast_values: [[2021, 0], [2035, -0.10791]]

- id: waste_treatment_actions_suomi
  name: Jätteenkäsittelytoimenpiteet perus
  name_en: Waste management actions moderate
  description: 'Jätteiden käsittelyn päästöjen kehityksen osalta laskennassa on tehty 
    seuraavat oletukset: 
    Pessimistinen skenaario: Asukaskohtaisten päästöjen oletetaan pysyvän vuoden 2021 tasolla.
    Suomi2035-skenaario: Päästöjen arvioidaan laskevan 4 prosenttia vuoden 2020 tasosta 
    vuoteen 2030 mennessä. Samankaltaisen päästökehityksen arvioidaan toteutuvan myös 
    aikavälillä 2030-2035. 
    HNE2030-skenaario: Päästöjen oletetaan laskevan 68 prosenttia aikavälillä 2021-2030, 
    minkä jälkeen päästöjen oletetaan pysyvän vuoden 2030 tasolla.'
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: t/cap/a
  output_nodes:
  - waste_treatment_impact_per_person
  forecast_values: [[2021, 0], [2035, -0.00495]]

- id: waste_treatment_actions_hne
  name: Jätteenkäsittelytoimenpiteet HNE
  name_en: Waste management actions full
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: t/cap/a
  output_nodes:
  - waste_treatment_impact_per_person
  forecast_values: [[2021, 0], [2030, -0.0541], [2035, -0.0541]]

- id: industry_and_machinery_actions
  name: Teollisuuden ja työkoneiden toimenpiteet
  name_en: Industry and machinery actions
  description: 'Teollisuuden ja työkoneiden päästöjen kehityksen osalta laskennassa 
    on tehty seuraavat oletukset: 
    Pessimistinen skenaario: Asukaskohtaisten päästöjen oletetaan pysyvän vuoden 2021 tasolla.  
    Suomi2035-skenaario: Päästöjen oletetaan laskevan teollisuudessa 53 prosenttia vuoteen 
    2035 mennessä. Työkoneiden päästöjen oletetaan laskevan 20 prosenttia.
    Hiilineutraali Espoo 2035 -skenaario vaatii vielä miettimistä.'
  type: simple.LinearCumulativeAdditiveAction
  quantity: emissions
  unit: kt/a
  forecast_values: [[2020, 0], [2035, -8.1619]]
  output_nodes:
  - industry_machinery_emissions

scenarios:
- id: baseline
  name: Nykykehitys
  name_en: Baseline

- id: moderate
  name: Suomi 2035
  name_en: Finland 2035
  all_actions_enabled: true
  params:
  - id: waste_treatment_actions_hne.enabled
    value: false

- id: default
  default: true
  name: Hiilineutraali Espoo 2030 -tiekartta
  name_en: Carbon-neutral Espoo 2030 roadmap
  all_actions_enabled: true
  params:
  - id: waste_treatment_actions_suomi.enabled
    value: false
