id: forestry-fi
default_language: en
supported_languages: [fi]
site_url: https://forestry-fi.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: e3ed69d53000724775ec6346d2003db1ee6f5ab8
  dvc_remote: kausal-s3
name_en: Multi-stakeholder forestry policy options
name_fi: Metsäpolitiikan monet vaihtoehdot
owner_fi: Kausal Oy
owner_en: Kausal Ltd
theme_identifier: default
emission_unit: kt/a
emission_dimensions: [cost_type]
model_end_year: 2050
target_year: 2035
reference_year: 1990
minimum_historical_year: 2000
maximum_historical_year: 2023
sample_size: 10

action_groups:
- id: forestry
  name_fi: Metsäteollisuus
  name: Forest industry
  color: '#50c878'

impact_overviews:
- graph_type: cost_efficiency
  cost_node: action_costs
  impact_node: total_cost
  invert_cost: false
  invert_impact: false
  indicator_unit: kEUR/Ut
  cost_unit: MEUR
  impact_unit: Ut
  label_fi: Kokonaishyödyn marginaalikustannus
  label: Marginal cost in total utility
- graph_type: cost_benefit
  cost_node: action_costs
  impact_node: total_economic_benefit
  invert_cost: false
  invert_impact: false
  indicator_unit: MEUR
  cost_unit: MEUR
  impact_unit: MEUR
  label_fi: Kustannus-hyötyarvio kokonaisvaikutuksista
  label: Cost-benefit analysis of total impacts
- graph_type: value_of_information
  cost_node: total_economic_benefit
  cost_unit: EUR
  label: Tiedonarvoanalyysi

params:
- id: municipality_name
  value: Tampere
  label: Municipality name
- id: emissions_weight
  label: Weight for emissions impacts in utilities
  is_customizable: true
  value: -0.05
  min_value: -100
  max_value: 0
  unit: Ut/kt
- id: economic_weight
  label: Weight for cost impacts in utilities
  is_customizable: true
  value: 1
  min_value: -100
  max_value: 10
  unit: Ut/MEUR
- id: statistical_correction
  label: Is biofuel climate neutral?
  is_customizable: true
  is_visible: true
  value: false

dimensions:

- id: iteration
  label_en: Iteration
  label_fi: Iteraatio
  categories:
  - id: '0'
    label: '0'
  - id: median
    label: Median

- id: activity
  label_fi: Toiminto
  label: Activity
  categories:
  - id: renewabe_energy_production
    label: Uusiutuva energiantuotanto
  - id: fossil_replacing_industry
    label: Fossiilisia korvaava teollisuus
  - id: hydrogen_production
    label: Ei-fossiilisen vedyn valmistus
  - id: ccs
    label: Hilidioksidin talteenotto ja varastointi
  - id: battery_industry
    label: Akkuteollisuus
  - id: nature_conservation
    label: ympäristönsuojelu
  - id: water_activities
    label: Vesiasiat

- id: cost_type
  label_fi: Kustannuslaji
  label_en: Cost type
  categories:
  - id: economic
    label_fi: Taloudellinen
    label_en: Economic
  - id: fossil_emissions
    label_fi: Fossiilinen päästö
    label_en: Ei-fossiilinen päästö
  - id: non_fossil_emissions
    label_fi: Ei-fossiilinen päästö
    label_en: Non-fossil emissions

- id: stakeholder
  label_fi: Sidosryhmä
  label: Stakeholder
  categories:
  - id: municipality
    label_fi: Kunta
    label: Municipality
  - id: citizen
    label_fi: Kansalainen
    label: Citizen
  - id: ici
    label_fi: Yrityselämä
    label: Industry and commerce
  - id: forest_owner
    label: Forest owner
  - id: mankind
    label_fi: Aktivisti
    label: Activist

- id: hypothesis
  label_fi: Hypoteesi
  label: Hypothesis
  categories:
  - id: hypothesis_0
    label: Null hypothesis
    color: '#22ee22'
  - id: biodiversity_ignored
    label: Biodiversity ignored
  - id: biodiversity_included
    label: Biodiversity included
  - id: hypothesis_1
    label: Hypothesis 1
    color: '#ee2222'
  - id: hypothesis_2
    label: Hypothesis 2
  - id: hypothesis_3
    label: Hypothesis 3
  - id: hypothesis_4
    label: Hypothesis 4
  - id: hypothesis_5
    label: Hypothesis 5
  - id: hypothesis_6
    label: Hypothesis 6
  - id: hypothesis_7
    label: Hypothesis 7
  - id: hypothesis_8
    label: Hypothesis 8
  - id: hypothesis_9
    label: Hypothesis 9
  - id: hypothesis_10
    label: Hypothesis 10
  - id: equal_weight
    label: Equal weight

emission_sectors:
- id: net_emissions
  name_fi: Kokonaispäästöt
  name_en: Net emissions
  is_outcome: true

nodes:
- id: population  # TODO Pois?
  type: finland.population.Population
  name_fi: Väestö
  name_en: Population
  description: Population size of the imaginary city.

# ---------------------------- Suomen metsänielukeskustelu

- id: forestry_production
  name_fi: Metsätaloustuotteiden valmistusmäärä Suomessa
  name_en: Forestry production in Finland
  type: gpc.DatasetNode
  quantity: mass
  unit: Mt/a
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Forestry production in Finland
  output_nodes: [forest_cuts_in_finland]

- id: biofuel_production
  name_fi: Bioenergian valmistusmäärä Suomessa
  name_en: Biofuel production in Finland
  type: gpc.DatasetNode
  quantity: mass
  unit: Mt/a
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Biofuel production in Finland
  output_nodes: [forest_cuts_in_finland]

- id: biofuel_emissions
  name_fi: Bioenergian päästöt
  name_en: Biofuel emissions
  type: simple.FixedMultiplierNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: biofuel_production
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions
  params:
  - id: multiplier
    value: 1
    unit: ton/ton

- id: emission_change_from_peat_reduction
  name_fi: Päästömuutos turpeen korvaamisesta
  name_en: Emission change from peat reduction
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: biofuel_production
    tags: [arithmetic_inverse]
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions

- id: forest_cuts_in_finland
  name_fi: Metsänhakkuut Suomessa
  name_en: Forest cutting in Finland
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a

- id: forestry_product_unit_price
  name_fi: Metsätaloustuotteiden keskihinta
  name_en: Average forestry product unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Average forestry product unit price

- id: forestry_product_sales
  name_fi: Metsätaloustuotteiden myyntivoitto
  name_en: Forestry product sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_nodes:
  - id: forestry_production
    to_dimensions: []
  - id: forestry_product_unit_price
  output_nodes:
  - id: total_economic_benefit

- id: biofuel_unit_price
  name_fi: Bioenergian hinta
  name_en: Biofuel unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Average biofuel unit price

- id: bioenergy_sales
  name_fi: Bioenergian myyntivoitto
  name_en: Biofuel sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_nodes:
  - id: biofuel_production
    to_dimensions: []
  - id: biofuel_unit_price
  output_nodes:
  - id: total_economic_benefit

- id: forest_growth
  name_en: Forest growth
  name_fi: Forest growth
  type: gpc.DatasetNode
  quantity: rate
  unit: '%/a'
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Forest growth

- id: amount_of_wood_in_forests
  name_fi: Suomen metsien koko
  name_en: Forest stock in Finnish forests
  type: gpc.DatasetNode # costs.InternalGrowthNode
  quantity: mass
  unit: Mt
  input_nodes:
  - id: forest_cuts_in_finland
    tags: [cumulative]
  # id: forest_growth
  input_datasets: [sunnydale/forestry_fi]
  params:
  - id: sector
    value: Historical forest stock in Finland
  # - id: annual_change
  #   value: 4.1875  # Year 2021: 134 Mt growth, 3200 Mt Wood storage in forests.
  #   unit: '%'

- id: carbon_sinks_in_forests
  name_en: Carbon sinks in forests
  name_fi: Metsien hiilinelut
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: amount_of_wood_in_forests
    tags: [difference]
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions
  # params:
  #   use_input_node_unit_when_adding: true

- id: forest_industry_emissions
  name_fi: Metsäteollisuuden päästöt
  name_en: Forest industry emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: forestry_production
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes: [net_emissions]

- id: total_economic_benefit
  name_fi: Taloudellinen kokonaishyöty
  name_en: Total economic benefit
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  output_nodes:
  - id: total_cost
    from_dimensions:
    - id: hypothesis
      categories: [biodiversity_ignored]
      flatten: true
    to_dimensions:
    - id: cost_type

- id: co2_market_price
  name_en: CO2 market price
  name_fi: Hiilidioksidin markkinahinta
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: CO2 market price

- id: emission_cost
  name_fi: Päästöjen kustannus
  name_en: Emission cost
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: net_emissions
  - id: co2_market_price
    to_dimensions: []
  output_nodes:
  - id: total_cost
    to_dimensions:
    - id: cost_type
  params:
  - id: multiplier
    ref: emissions_weight

- id: total_cost
  name_fi: Kokonaiskustannus
  name_en: Total cost
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  is_outcome: true

actions:

- id: district_heating_with_biofuels
  name_en: District heating with biofuels
  name_fi: Kaukolämmitys bioenergialla
  type: gpc.DatasetAction
  quantity: mass
  unit: kt/a
  group: forestry
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: District heating with biofuels in Sunnydale
  output_nodes:
  - id: biofuel_production

- id: reduce_forestry_production
  name_en: Reduce forestry production
  name_fi: Vähennä metsäteollisuustuotantoa
  type: gpc.DatasetAction
  quantity: fraction
  unit: '%'
  group: forestry
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Reduce forestry production
  output_nodes:
  - id: forestry_production
    tags: [arithmetic_inverse, complement, non_additive]

pages:
- id: home
  name_fi: Vihreän siirtymän prioriteetit
  name_en: Green transition priotities
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Vihreän siirtymän prioriteetit
  lead_title_en: Green transition priorities
  lead_paragraph: add

scenarios:
- id: baseline
  name_fi: Tätä menoa
  name_en: Business as usual

- id: default
  default: true
  name_fi: Aktiivinen
  name_en: Active
  all_actions_enabled: true

- id: energy_company
  name_fi: Energiayhtiön arvot
  name_en: Values of the energy company
  all_actions_enabled: true
  params:
  - id: economic_weight
    value: 1
    unit: 1/EUR
