id: forestry-fi
default_language: en
supported_languages: [fi]
site_url: https://forestry-fi.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: c9ff1e1361e59a914075d5209ae1ff2f78010e54
  dvc_remote: kausal-s3
name_en: Multi-stakeholder forestry policy options
name_fi: Metsäpolitiikan monet vaihtoehdot
owner_fi: Kausal Oy
owner_en: Kausal Ltd
theme_identifier: default
emission_unit: kt/a
model_end_year: 2050
target_year: 2035
reference_year: 1990
minimum_historical_year: 2000
maximum_historical_year: 2023
sample_size: 10

action_groups:
- id: forestry
  name_fi: Metsäteollisuus
  name: Forest industry
  color: '#50c878'

impact_overviews:
- graph_type: cost_efficiency
  cost_node: action_costs
  impact_node: total_cost
  invert_cost: false
  invert_impact: false
  indicator_unit: kEUR/Ut
  cost_unit: MEUR
  impact_unit: Ut
  label_fi: Kokonaishyödyn marginaalikustannus
  label: Marginal cost in total utility
- graph_type: cost_benefit
  cost_node: action_costs
  impact_node: total_economic_benefit
  invert_cost: false
  invert_impact: false
  indicator_unit: MEUR
  cost_unit: MEUR
  impact_unit: MEUR
  label_fi: Kustannus-hyötyarvio kokonaisvaikutuksista
  label: Cost-benefit analysis of total impacts
- graph_type: value_of_information
  cost_node: total_economic_benefit
  cost_unit: EUR
  label: Tiedonarvoanalyysi

params:
- id: municipality_name
  value: Tampere
  label: Municipality name
- id: emissions_weight
  label: Weight for emissions impacts in utilities
  is_customizable: true
  value: -0.05
  min_value: -100
  max_value: 0
  unit: Ut/kt
- id: economic_weight
  label: Weight for cost impacts in utilities
  is_customizable: true
  value: 1
  min_value: -100
  max_value: 10
  unit: Ut/MEUR
- id: statistical_correction
  label: Is biofuel climate neutral?
  is_customizable: true
  is_visible: true
  value: false

dimensions:

- id: iteration
  label_en: Iteration
  label_fi: Iteraatio
  categories:
  - id: '0'
    label: '0'
  - id: median
    label: Median

- id: activity
  label_fi: Toiminto
  label: Activity
  categories:
  - id: renewabe_energy_production
    label: Uusiutuva energiantuotanto
  - id: fossil_replacing_industry
    label: Fossiilisia korvaava teollisuus
  - id: hydrogen_production
    label: Ei-fossiilisen vedyn valmistus
  - id: ccs
    label: Hilidioksidin talteenotto ja varastointi
  - id: battery_industry
    label: Akkuteollisuus
  - id: nature_conservation
    label: ympäristönsuojelu
  - id: water_activities
    label: Vesiasiat

- id: stakeholder
  label_fi: Sidosryhmä
  label: Stakeholder
  categories:
  - id: municipality
    label_fi: Kunta
    label: Municipality
  - id: citizen
    label_fi: Kansalainen
    label: Citizen
  - id: ici
    label_fi: Yrityselämä
    label: Industry and commerce
  - id: forest_owner
    label: Forest owner
  - id: mankind
    label_fi: Ihmiskunta
    label: Mankind

- id: hypothesis
  label_fi: Hypoteesi
  label: Hypothesis
  categories:
  - id: hypothesis_0
    label: Null hypothesis
    color: '#22ee22'
  - id: hypothesis_1
    label: Hypothesis 1
    color: '#ee2222'
  - id: hypothesis_2
    label: Hypothesis 2
  - id: hypothesis_3
    label: Hypothesis 3
  - id: hypothesis_4
    label: Hypothesis 4
  - id: hypothesis_5
    label: Hypothesis 5
  - id: hypothesis_6
    label: Hypothesis 6
  - id: hypothesis_7
    label: Hypothesis 7
  - id: hypothesis_8
    label: Hypothesis 8
  - id: hypothesis_9
    label: Hypothesis 9
  - id: hypothesis_10
    label: Hypothesis 10
  - id: equal_weight
    label: Equal weight

emission_sectors:
- id: net_emissions
  name_fi: Kokonaispäästöt
  name_en: Net emissions
  description: Suomen kasvihuonekaasujen nettokokonaispäästöt, eli scope 1+2 ja hiilinielut.
    <h3>Hypoteesit</h3> <ul><li>Hakkuiden lisääminen lisää kasvihuonekaasupäästöjä.
    (1)</li> <li>Hakkuiden lisääminen ei vaikuta kasvihuonekaasupäästöihin. (2)</li>
    <li>Löysempi kasvihuonekaasupäästötavoite ei aiheuta haittaa. (3)</li> <li>Suomen
    toimien vaikutukset kasvihuonekaasupäästöihin ovat vähäiset. (4)</li></ul> <h3>Viitteet</h3>
    <ul><li>HS.ymp.2 Krist Savo</li> <li>(1) HS.ymp.1 Vihr Uusimaa</li> <li>HS.ymp.2
    Vihr Uusimaa</li> <li>(2) HS.ymp.1 Perus Uusimaa</li> <li>HS.ymp.2 Perus Uusimaa</li>
    <li>(3) HS.ymp.1 Perus Savo</li> <li>HS.ymp.1 Rkp Uusimaa</li> <li>(4) HS.ymp.2
    Rkp Uusimaa</li> <li>HS.ymp.2 Vihr Savo</li> <li>HS.ymp.2 Kok Savo</li> <li>HS.ymp.2
    Vas Savo</li> <li>(4) HS.ymp.1 Liik Savo</li> <li>HS.ymp.1 Liik Uusimaa</li> <li>HS.ymp.2
    Kok Uusimaa</li> <li>HS.ymp.1 Sdp Savo</li> <li>HS.ymp.1 Sdp Uusimaa</li> <li>HS.ymp.2
    Sdp Uusimaa</li> <li>HS.ymp.1 Kesk Savo</li> <li>HS.ymp.2 Kesk Savo</li></ul>
  is_outcome: true
  input_dataset_processors: [LinearInterpolation]

nodes:
- id: population
  type: finland.population.Population
  name_fi: Väestö
  name_en: Population
  description: Population size of the imaginary city.

- id: action_costs
  name_fi: Toimenpiteiden toteuttamisen suorat kustannukset
  name_en: Direct implementation costs of actions
  type: simple.AdditiveNode
  quantity: currency
  unit: kEUR/a
  historical_values: [[2010, 0]]
  output_nodes: [total_cost]

# ---------------------------- Suomen metsänielukeskustelu

- id: forestry_production
  name_fi: Metsätaloustuotteiden valmistusmäärä Suomessa
  name_en: Forestry production in Finland
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  historical_values: [[2000, 29], [2023, 69.2]]
  input_dataset_processors: [LinearInterpolation]
  output_nodes: [forest_cuts_in_finland]

- id: biofuel_production
  name_fi: Bioenergian valmistusmäärä Suomessa
  name_en: Biofuel production in Finland
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  historical_values: [[2000, 29], [2023, 69.2]]
  input_dataset_processors: [LinearInterpolation]
  output_nodes: [forest_cuts_in_finland]

- id: emission_change_from_peat_reduction
  name_fi: Päästömuutos turpeen korvaamisesta
  name_en: Emission change from peat reduction
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_nodes:
  - id: biofuel_production
    tags: [arithmetic_inverse]
  output_nodes: [net_emissions]

- id: forest_cuts_in_finland
  name_fi: Metsänhakkuut Suomessa
  name_en: Forest cutting in Finland
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a

- id: forestry_product_unit_price
  name_fi: Metsätaloustuotteiden keskihinta
  name_en: Average forestry product unit price
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2000, 1000], [2023, 900]]
  input_dataset_processors: [LinearInterpolation]

- id: forestry_product_sales
  name_fi: Metsätaloustuotteiden myyntivoitto
  name_en: Forestry product sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes: [forestry_production, forestry_product_unit_price]
  output_nodes: [total_economic_benefit]

- id: biofuel_unit_price
  name_fi: Bioenergian hinta
  name_en: Biofuel unit price
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[2000, 1000], [2023, 900]]
  input_dataset_processors: [LinearInterpolation]

- id: bioenergy_sales
  name_fi: Bioenergian myyntivoitto
  name_en: Biofuel sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes: [biofuel_production, biofuel_unit_price]
  output_nodes: [total_economic_benefit]

- id: forest_growth
  name_en: Forest growth
  name_fi: Forest growth
  type: simple.AdditiveNode
  quantity: mass  # FIXME fraction
  unit: Mt/a
  historical_values: [[2000, 0]]

- id: amount_of_wood_in_forests
  name_fi: Suomen metsien koko
  name_en: Forest stock in Finnisih forests
  type: costs.InternalGrowthNode
  quantity: mass
  unit: Mt
  input_nodes: [forest_cuts_in_finland, forest_growth]
  historical_values: [[2000, 3000], [2023, 3200]]
  input_dataset_processors: [LinearInterpolation]
  params:
  - id: annual_change
    value: 4.1875  # Year 2021: 134 Mt growth, 3200 Mt Wood storage in forests.
    unit: '%'

- id: carbon_sinks_in_forests
  name_en: Carbon sinks in forests
  name_fi: Carbon sinks in forests
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a
  input_nodes:
  - id: amount_of_wood_in_forests
    tags: [difference]
  output_nodes:
  - id: net_emissions

- id: forest_industry_emissions
  name_fi: Metsäteollisuuden päästöt
  name_en: Forest industry emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_nodes: [forestry_production]
  output_nodes: [net_emissions]

- id: total_economic_benefit
  name_fi: Taloudellinen kokonaishyöty
  name_en: Total economic benefit
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  output_nodes: [total_cost]

- id: co2_market_price
  name_en: CO2 market price
  name_fi: Hiilidioksidin markkinahinta
  type: simple.AdditiveNode
  quantity: unit_price
  unit: EUR/t
  historical_values: [[1990, 100]]

- id: emission_cost
  name_fi: Päästöjen kustannus
  name_en: Emission cost
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_nodes:
  - id: net_emissions
  - id: co2_market_price
  output_nodes: [total_cost]
  params:
  - id: multiplier
    ref: emissions_weight

- id: total_cost
  name_fi: Kokonaiskustannus
  name_en: Total cost
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  is_outcome: true

actions:

- id: district_heating_with_biofuels
  name_en: District heating with biofuels
  name_fi: Kaukolämmitys bioenergialla
  type: simple.AdditiveAction
  quantity: mass
  unit: kt/a
  group: forestry
  historical_values: [[2010, 0], [2023, 0]]
  input_dataset_processors: [LinearInterpolation]
  forecast_values: [[2024, 100], [2035, 100]]
  output_nodes:
  - id: biofuel_production

- id: reduce_forestry_production
  name_en: Reduce forestry production
  name_fi: Vähennä metsäteollisuustuotantoa
  type: simple.AdditiveAction
  quantity: mass
  unit: kt/a
  group: forestry
  historical_values: [[2010, 0], [2023, 0]]
  input_dataset_processors: [LinearInterpolation]
  forecast_values: [[2024, -100], [2035, -100]]
  output_nodes:
  - id: forestry_production

pages:
- id: home
  name_fi: Vihreän siirtymän prioriteetit
  name_en: Green transition priotities
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Vihreän siirtymän prioriteetit
  lead_title_en: Green transition priorities
  lead_paragraph: add

scenarios:
- id: baseline
  name_fi: Tätä menoa
  name_en: Business as usual

- id: default
  default: true
  name_fi: Aktiivinen
  name_en: Active
  all_actions_enabled: true

- id: energy_company
  name_fi: Energiayhtiön arvot
  name_en: Values of the energy company
  all_actions_enabled: true
  params:
  - id: economic_weight
    value: 1
    unit: 1/EUR
