id: forestry-fi
default_language: en
supported_languages: [fi]
site_url: https://forestry-fi.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 89ae9bd230d1f567f25e05359fee55f6f8ac3cf1
  dvc_remote: kausal-s3
name_en: Multi-stakeholder forestry policy options
name_fi: Metsäpolitiikan monet vaihtoehdot
owner_fi: Kausal Oy
owner_en: Kausal Ltd
theme_identifier: default
emission_unit: kt/a
emission_dimensions: [cost_type]
model_end_year: 2050
target_year: 2035
reference_year: 1990
minimum_historical_year: 2000
maximum_historical_year: 2023
sample_size: 10

action_groups:
- id: forestry
  name_fi: Metsäteollisuus
  name: Forest industry
  color: '#50c878'

impact_overviews:
- graph_type: cost_efficiency
  cost_node: action_costs
  impact_node: total_cost
  invert_cost: false
  invert_impact: false
  indicator_unit: kEUR/Ut
  cost_unit: MEUR
  impact_unit: Ut
  label_fi: Kokonaishyödyn marginaalikustannus
  label: Marginal cost in total utility
- graph_type: cost_benefit
  cost_node: action_costs
  impact_node: total_economic_benefit
  invert_cost: false
  invert_impact: false
  indicator_unit: MEUR
  cost_unit: MEUR
  impact_unit: MEUR
  label_fi: Kustannus-hyötyarvio kokonaisvaikutuksista
  label: Cost-benefit analysis of total impacts
- graph_type: value_of_information
  cost_node: total_economic_benefit
  cost_unit: EUR
  label: Tiedonarvoanalyysi

params:
- id: municipality_name
  value: Tampere
  label: Municipality name
- id: emissions_weight
  label: Weight for emissions impacts in utilities
  is_customizable: true
  value: -0.05
  min_value: -100
  max_value: 0
  unit: Ut/kt
- id: economic_weight
  label: Weight for cost impacts in utilities
  is_customizable: true
  value: 1
  min_value: -100
  max_value: 10
  unit: Ut/MEUR
- id: statistical_correction
  label: Is biofuel climate neutral?
  is_customizable: true
  is_visible: true
  value: false

dimensions:

- id: iteration
  label_en: Iteration
  label_fi: Iteraatio
  categories:
  - id: '0'
    label: '0'
  - id: median
    label: Median

- id: activity
  label_fi: Toiminto
  label: Activity
  categories:
  - id: renewabe_energy_production
    label: Uusiutuva energiantuotanto
  - id: fossil_replacing_industry
    label: Fossiilisia korvaava teollisuus
  - id: hydrogen_production
    label: Ei-fossiilisen vedyn valmistus
  - id: ccs
    label: Hilidioksidin talteenotto ja varastointi
  - id: battery_industry
    label: Akkuteollisuus
  - id: nature_conservation
    label: ympäristönsuojelu
  - id: water_activities
    label: Vesiasiat

- id: cost_type
  label_fi: Kustannuslaji
  label_en: Cost type
  categories:
  - id: economic
    label_fi: Taloudellinen
    label_en: Economic
  - id: fossil_emissions
    label_fi: Fossiilinen päästö
    label_en: Ei-fossiilinen päästö
  - id: non_fossil_emissions
    label_fi: Ei-fossiilinen päästö
    label_en: Non-fossil emissions

- id: stakeholder
  label_fi: Sidosryhmä
  label: Stakeholder
  categories:
  - id: municipality
    label_fi: Kunta
    label: Municipality
  - id: citizen
    label_fi: Kansalainen
    label: Citizen
  - id: ici
    label_fi: Yrityselämä
    label: Industry and commerce
  - id: forest_owner
    label: Forest owner
  - id: mankind
    label_fi: Aktivisti
    label: Activist

- id: hypothesis
  label_fi: Hypoteesi
  label: Hypothesis
  categories:
  - id: hypothesis_0
    label: Null hypothesis
    color: '#22ee22'
  - id: biodiversity_ignored
    label: Biodiversity ignored
  - id: biodiversity_included
    label: Biodiversity included
  - id: hypothesis_1
    label: Hypothesis 1
    color: '#ee2222'
  - id: hypothesis_2
    label: Hypothesis 2
  - id: hypothesis_3
    label: Hypothesis 3
  - id: hypothesis_4
    label: Hypothesis 4
  - id: hypothesis_5
    label: Hypothesis 5
  - id: hypothesis_6
    label: Hypothesis 6
  - id: hypothesis_7
    label: Hypothesis 7
  - id: hypothesis_8
    label: Hypothesis 8
  - id: hypothesis_9
    label: Hypothesis 9
  - id: hypothesis_10
    label: Hypothesis 10
  - id: equal_weight
    label: Equal weight

- id: region
  label: Region
  categories:
  - id: international_aviation
    label: International aviation,
  - id: international_shipping
    label: International shipping,
  - id: oceania
    label: Oceania,
  - id: asia_excl_china_and_india
    label: Asia (excl. China and India),
  - id: china
    label: China,
  - id: india
    label: India,
  - id: africa
    label: Africa,
  - id: south_america
    label: South America,
  - id: north_america_excl_usa
    label: North America (excl. USA),
  - id: united_states
    label: United States,
  - id: european_union_27
    label: European Union (27),
  - id: europe_excl_eu27
    label: Europe (excl. EU-27)

- id: emission_class
  label: Emission class
  categories:
  - id: 1_energiasektori
    label_en: 1 Energy sector
    label_fi: 1 Energiasektori
  - id: 2_teollisuusprosessit_ja_tuotteiden_kaytto
    label_en: 2 Industrial processes and product use (IPPU)
    label_fi: 2 Teollisuusprosessit ja tuotteiden käyttö (IPPU)
  - id: 3_maatalous
    label_en: 3 Agriculture
    label_fi: 3 Maatalous
  - id: 4_maankaytto_maankayton_muutokset_ja_metsatalous_lulucf
    label_en: 4 Land use, land use change and forestry (LULUCF)
    label_fi: '4 Maankäyttö, maankäytön muutokset ja metsätalous (LULUCF)'
  - id: 5_jatteiden_kasittely
    label_en: 5 Waste management
    label_fi: 5 Jätteiden käsittely
  - id: epasuorat_co2_paastot
    label_en: Indirect CO2 emissions
    label_fi: Epäsuorat CO2 päästöt

nodes:

- id: net_emissions
  name_fi: Kokonaispäästöt
  name_en: Net emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt/a
  # is_outcome: true
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  output_nodes:
  - id: historical_emissions_in_finland
    from_dimensions:
    - id: cost_type
      flatten: true
    to_dimensions:
    - id: emission_class
      categories: [1_energiasektori]
  # goals:
  # - label: Total emission goal 2035
  #   default: true
  #   is_main_goal: true
  #   linear_interpolation: true
  #   values:
  #   - year: 2022
  #     value: 37100000000
  #   - year: 2050
  #     value: 0.0

# ---------------------------- Global level nodes -----------

- id: global_emissions
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  input_dimensions: [region]
  output_dimensions: [region]
  is_outcome: true
  goals:
  - label: Total emission goal 2050
    default: true
    is_main_goal: true
    linear_interpolation: true
    values:
    - year: 2022
      value: 37100000000
    - year: 2050
      value: 0.0
  name: Annual CO₂ emissions by world region
  description: Annual total emissions of carbon dioxide (CO₂) from fossil fuels and
    industry, excluding land-use change, measured in tonnes. This data is based on
    territorial emissions, which do not account for emissions embedded in traded goods.
    Emissions from international aviation and shipping are not included in any country
    or region's emissions. They are only included in the global total emissions.<br>
    <h3>Processing</h3>Data on global emissions has been converted from tonnes of
    carbon to tonnes of carbon dioxide (CO₂) using a conversion factor of 3.664. Emissions
    from the Kuwaiti oil fires in 1991 have been included as part of Kuwait's emissions
    for that year. Country's share of the global population is calculated using our
    population dataset, based on <a href="https://ourworldindata.org/population-sources">different
    sources</a>. Each country's share of global CO₂ emissions from flaring has been
    calculated using global CO₂ emissions from flaring provided in the Global Carbon
    Budget dataset. Last Updated 2024-06-20, Citation Global Carbon Budget (2023)
    – with major processing by Our World in Data. “Annual CO₂ emissions – GCB” <a
    href="https://api.ourworldindata.org/v1/indicators/944146.metadata.json">dataset</a>.
    Global Carbon Project, “Global Carbon Budget” [original data].<br> Citation <a
    href="https://ourworldindata.org/grapher/annual-co-emissions-by-region">Global
    Carbon Budget (2023)</a>
  input_datasets:
  - id: ourworldindata/annual-co2-emissions-by-region
    filters:
    - column: Region
      drop_col: false
      values: [International aviation, International shipping, Oceania, Asia (excl.
          China and India), China, India, Africa, South America, North America (excl.
          USA), United States, European Union (27), Europe (excl. EU-27)]
    - column: Code
      drop_col: true
  params:
    sector: CO2 emissions

- id: global_responsibility_ratio
  name: Global responsibility ratio
  description: This is the ratio of emission reductions that we are prepared to implement.
    We also think that all developed countries are morally obliged to reach the same
    reduction; we cannot demand more from others than what we do ourselves.
  type: simple.AdditiveNode
  quantity: ratio
  unit: dimensionless
  input_nodes:
  - id: net_emissions
    tags: [ratio_to_last_historical_value]
    from_dimensions:
    - id: cost_type
      flatten: true

# -------------------------- Generic nodes ----------------

- id: population
  type: finland.population.Population
  name_fi: Väestö
  name_en: Population
  description: Population size of the imaginary city.

- id: historical_emissions_in_finland
  name: Historical emissions in Finland
  description: 'Source: <a href="https://pxdata.stat.fi/PxWeb/pxweb/fi/StatFin/StatFin__khki/statfin_khki_pxt_138v.px/">Tilastokeskus 2024</a>'
  type: gpc.DatasetNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [emission_class]
  output_dimensions: [emission_class]
  input_datasets:
  - id: statfi/ghg_emissions_fi
    filters:
    - column: GHG
      value: Kaasut yhteensä
    - column: Emission class
      values: [
        1 Energiasektori,
        2 Teollisuusprosessit ja tuotteiden käyttö,
        3 Maatalous,
        '4 Maankäyttö, maankäytön muutokset ja metsätalous (LULUCF)',
        5 Jätteiden käsittely,
        Epäsuorat CO2 päästöt]
      drop_col: false
  params:
    sector: Päästö, tuhatta tonnia CO2-ekv. (GWP=AR5)
  output_nodes:
  - id: global_emissions
    from_dimensions:
    - id: emission_class
      flatten: true
    to_dimensions:
    - id: region
      categories: [european_union_27]
  goals:
  - label: Total emission goal 2035
    default: true
    is_main_goal: true
    linear_interpolation: true
    values:
    - year: 2023
      value: 40.6
    - year: 2035
      value: 0.0

# ---------------------------- Suomen metsänielukeskustelu

- id: forestry_production
  name_fi: Metsätaloustuotteiden valmistusmäärä Suomessa
  name_en: Forestry production in Finland
  type: gpc.DatasetNode
  quantity: mass
  unit: Mt/a
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Forestry production in Finland
  output_nodes: [forest_cuts_in_finland]

- id: biofuel_production
  name_fi: Bioenergian valmistusmäärä Suomessa
  name_en: Biofuel production in Finland
  type: gpc.DatasetNode
  quantity: mass
  unit: Mt/a
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Biofuel production in Finland
  output_nodes: [forest_cuts_in_finland]

- id: biofuel_emissions
  name_fi: Bioenergian päästöt
  name_en: Biofuel emissions
  type: simple.FixedMultiplierNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: biofuel_production
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions
  params:
  - id: multiplier
    value: 1
    unit: ton/ton

- id: emission_change_from_peat_reduction
  name_fi: Päästömuutos turpeen korvaamisesta
  name_en: Emission change from peat reduction
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: biofuel_production
    tags: [arithmetic_inverse]
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions

- id: forest_cuts_in_finland
  name_fi: Metsänhakkuut Suomessa
  name_en: Forest cutting in Finland
  type: simple.AdditiveNode
  quantity: mass
  unit: Mt/a

- id: forestry_product_unit_price
  name_fi: Metsätaloustuotteiden keskihinta
  name_en: Average forestry product unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Average forestry product unit price

- id: forestry_product_sales
  name_fi: Metsätaloustuotteiden myyntivoitto
  name_en: Forestry product sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_nodes:
  - id: forestry_production
    to_dimensions: []
  - id: forestry_product_unit_price
  output_nodes:
  - id: total_economic_benefit

- id: biofuel_unit_price
  name_fi: Bioenergian hinta
  name_en: Biofuel unit price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Average biofuel unit price

- id: bioenergy_sales
  name_fi: Bioenergian myyntivoitto
  name_en: Biofuel sales
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  input_nodes:
  - id: biofuel_production
    to_dimensions: []
  - id: biofuel_unit_price
  output_nodes:
  - id: total_economic_benefit

- id: forest_growth
  name_en: Forest growth
  name_fi: Forest growth
  type: gpc.DatasetNode
  quantity: rate
  unit: '%/a'
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Forest growth

- id: historical_amount_of_wood_in_forests
  name_fi: Suomen metsien historiallinen koko
  name_en: Historical forest stock in Finnish forests
  type: gpc.DatasetNode # costs.InternalGrowthNode
  quantity: mass
  unit: Mt
  input_datasets:
  - id: sunnydale/forestry_fi
    filters:
    - column: Year
      value: 2023
      drop_col: false
  params:
    sector: Historical forest stock in Finland

- id: amount_of_wood_in_forests
  name_fi: Suomen metsien koko
  name_en: Forest stock in Finnish forests
  type: costs.IterationNode
  quantity: mass
  unit: Mt
  input_nodes:
  - id: historical_amount_of_wood_in_forests
    tags: [base]
  - id: forest_cuts_in_finland
    tags: [arithmetic_inverse]
  - id: forest_growth_rate
    tags: [rate]

- id: forest_growth_rate
  name_en: Forest growth rate
  type: simple.AdditiveNode
  quantity: rate
  unit: '%'
  historical_values: [[1990, 2.0 ]] # 4.1875]] # Year 2021: 134 Mt growth, 3200 Mt Wood storage in forests.

- id: carbon_sinks_in_forests
  name_en: Carbon sinks in forests
  name_fi: Metsien hiilinelut
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: amount_of_wood_in_forests
    tags: [difference, arithmetic_inverse]
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes:
  - id: net_emissions
  # params:
  #   use_input_node_unit_when_adding: true

- id: forest_industry_emissions
  name_fi: Metsäteollisuuden päästöt
  name_en: Forest industry emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: Mt/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: forestry_production
    to_dimensions:
    - id: cost_type
      categories: [non_fossil_emissions]
  output_nodes: [net_emissions]

- id: total_economic_benefit
  name_fi: Taloudellinen kokonaishyöty
  name_en: Total economic benefit
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type, hypothesis]
  output_dimensions: [cost_type, hypothesis]
  output_nodes:
  - id: total_cost
    from_dimensions:
    - id: hypothesis
      categories: [biodiversity_ignored]
      flatten: true
    to_dimensions:
    - id: cost_type

- id: co2_market_price
  name_en: CO2 market price
  name_fi: Hiilidioksidin markkinahinta
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/t
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: CO2 market price

- id: emission_cost
  name_fi: Päästöjen kustannus
  name_en: Emission cost
  type: simple.MultiplicativeNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: net_emissions
  - id: co2_market_price
    to_dimensions: []
  output_nodes:
  - id: total_cost
    to_dimensions:
    - id: cost_type
  params:
  - id: multiplier
    ref: emissions_weight

- id: total_cost
  name_fi: Kokonaiskustannus
  name_en: Total cost
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  is_outcome: true

# ------------------ Nodes for impact overviews ---------------

- id: total_cost_costs
  name: Total cost costs
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  is_visible: false
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: total_cost
    tags: [make_nonnegative]

- id: total_cost_benefits
  name: Total cost benefits
  type: simple.AdditiveNode
  quantity: currency
  unit: MEUR/a
  is_visible: false
  input_dimensions: [cost_type]
  output_dimensions: [cost_type]
  input_nodes:
  - id: total_cost
    tags: [make_nonpositive]

actions:

- id: district_heating_with_biofuels
  name_en: District heating with biofuels
  name_fi: Kaukolämmitys bioenergialla
  type: gpc.DatasetAction
  quantity: mass
  unit: kt/a
  group: forestry
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: District heating with biofuels in Sunnydale
  output_nodes:
  - id: biofuel_production

- id: reduce_forestry_production
  name_en: Reduce forestry production
  name_fi: Vähennä metsäteollisuustuotantoa
  type: gpc.DatasetAction
  quantity: fraction
  unit: '%'
  group: forestry
  input_datasets: [sunnydale/forestry_fi]
  params:
    sector: Reduce forestry production
  output_nodes:
  - id: forestry_production
    tags: [complement, non_additive]

pages:
- id: home
  name_fi: Vihreän siirtymän prioriteetit
  name_en: Green transition priotities
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Vihreän siirtymän prioriteetit
  lead_title_en: Green transition priorities
  lead_paragraph: add

scenarios:
- id: baseline
  name_fi: Tätä menoa
  name_en: Business as usual

- id: default
  default: true
  name_fi: Aktiivinen
  name_en: Active
  all_actions_enabled: true

- id: energy_company
  name_fi: Energiayhtiön arvot
  name_en: Values of the energy company
  all_actions_enabled: true
  params:
  - id: economic_weight
    value: 1
    unit: 1/EUR
