id: hsy-multidim
default_language: fi
site_url: https://hsy-multidim.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 428b6c0879a556b5659117c27bdeb53b408799fd
  dvc_remote: kausal-s3
name_fi: HSY-päästöt
name_en: HSY emissions
name_sv: HSY emissioner
owner: Kausal Oy
owner_en: Kausal Ltd
owner_sv: Kausal Oy
theme_identifier: default
emission_unit: kt/a
model_end_year: 2030
target_year: 2030
reference_year: 1990
minimum_historical_year: 1990
maximum_historical_year: 2024
features:
  baseline_visible_in_graphs: true
  show_accumulated_effects: true
  use_datasets_from_db: true
  show_significant_digits: 3
  show_explanations: true

params:
- id: municipality_name
  value: Espoo
- id: scenario_name
  value: default

dimensions:

- id: building_heating
  label_en: Building heating
  label_fi: Rakennuksen lämmitystapa
  categories:
  - id: direct_electricity
    label_fi: Suora sähkölämmitys
  - id: oven_heating
    label_fi: Uuni- tai kaminalämmitys
  - id: central_heating
    label_fi: Keskuslämmitys
  - id: other_or_unknown
    label_fi: Muu tai tuntematon
  - id: total
    label_fi: Yhteensä
  - id: district_heating
    label_fi: Kaukolämpö
  - id: oil_heating
    label_fi: Öljylämmitys
  - id: direct_electric_heating
    label_fi: Sähkölämmitys
  - id: geothermal_heating
    label_fi: Maalämpö

- id: economic_sector
  label_fi: Taloussektori
  label_en: Economic sector
  label_sv: Ekonomisk sektor
  categories:
  - id: services
    label_en: Services
    label_fi: Palvelut
    label_sv: Tjänster
  - id: industry
    label_en: Industry
    label_fi: Teollisuus
    label_sv: Industri
  - id: residential
    label_en: Residential
    label_fi: Asuminen
    label_sv: Bostäder
  - id: agriculture
    label_en: Agriculture
    label_fi: Maatalous
    label_sv: Jordbruk
  - id: field_farming
    label_fi: Peltoviljely
    aliases: [Pellot]
    label_en: Field farming
    label_sv: Åkerbruk
  - id: cattle_farming
    label_fi: Kotieläintalous
    aliases: [Kotieläimet]
    label_en: Cattle farming
    label_sv: Boskapsskötsel
  - id: road_transport
    label_fi: Tieliikenne
  - id: rail_transport
    label_fi: Raideliikenne
  - id: shipping
    label_fi: Laivaliikenne
  - id: machinery
    label_fi: Työkoneet
  - id: industrial_fuels
    label_fi: Teollisuuden polttonaineet
    aliases: [Polttoaineet]
  - id: industrial_processes
    label_fi: Teollisuuden prosessit
    aliases: [Prosessit]

- id: waste_treatment
  label_fi: Jätteenkäsittely
  label_en: Waste treatment
  label_sv: Avfallsbehandling
  categories:
  - id: landfills
    label_fi: Kaatopaikka
    label_en: Landfills
    label_sv: Deponier
  - id: biowaste_composting
    label_fi: Biojätteen kompostointi
    label_en: Biowaste composting
    label_sv: Kompostering av bioavfall
  - id: waste_water_treatment
    label_fi: Jäteveden käsittely
    label_en: Wastewater treatment
    label_sv: Avloppsvattenbehandling
  - id: sludge_composting
    label_fi: Jätevesilietteen kompostointi
    label_en: Sewage sludge composting
    label_sv: Kompostering av avloppsslam

- id: vehicle_type
  label_fi: Ajoneuvotyyppi
  label_en: Vehicle type
  label_sv: Fordonstyp
  categories:
  - id: cars
    aliases: [passenger_cars]
    label_fi: Henkilöautot
    label_en: Cars
    label_sv: Personbilar
  - id: electric_vehicles
    label_fi: Sähköautot
    label_en: Electric vehicles
    label_sv: Elbilar
  - id: hybrid_vehicles
    label_fi: Hybridit
    label_en: Hybrid vehicles
    label_sv: Hybridbilar
  - id: buses
    label_fi: Bussit
    label_en: Buses
    label_sv: Bussar
    aliases: [Linja-autot]
  - id: buses_hsl
    label_fi: Bussit, HSL
    label_en: Buses, HSL
    label_sv: Bussar, HRT
  - id: buses_other
    label_fi: Bussit, muu
    label_en: Buses, other
    label_sv: Bussar, övriga
  - id: local_trains
    label_fi: Lähijunat
    aliases: [Paikallisjunat]
    label_en: Commuter trains
    label_sv: Pendeltåg
  - id: motorcycles
    label_fi: Moottoripyörät
    label_en: Motorcycles
    label_sv: Motorcyklar
  - id: trams
    label_fi: Raitiovaunut
    aliases: [Ratikat]
    label_en: Trams
    label_sv: Spårvagnar
  - id: metros
    label_fi: Metrot
    aliases: [Metro, metro]
    label_en: Metro
    label_sv: Tunnelbana
  - id: trucks
    label_fi: Kuorma-autot
    label_en: Trucks
    label_sv: Lastbilar
    aliases: [Lorries]
  - id: vans
    label_fi: Pakettiautot
    label_en: Vans
    label_sv: Paketbilar
  - id: undefined
    label_fi: Ei määritelty
    label_en: Undefined
    label_sv: Odefinierad
  - id: leasure_boats
    label_fi: Huviveneet
    label_en: Leisure boats
    label_sv: Fritidsbåtar
  - id: professional_boats
    label_fi: Ammattiveneet
    label_en: Professional boats
    label_sv: Yrkesfartyg
  - id: passenger_ships
    label_fi: Matkustajalaivat
    label_en: Passenger ships
    label_sv: Passagerarfartyg
  - id: cargo_ships
    label_fi: Rahtilaivat
    label_en: Cargo ships
    label_sv: Lastfartyg

nodes:

- id: net_emissions
  name_fi: Net emissions
  type: simple.SectorEmissions
  quantity: emissions
  unit: kt/a
  is_outcome: true

- id: building_heating_emissions
  name: Rakennusten lämmityksen päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [building_heating, economic_sector]
  output_dimensions: [building_heating, economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori4
      value: economic_sector
    - rename_col: Sektori3
      value: building_heating
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Lämmitys
    - column: Sektori2
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: building_heating
      flatten: true
    - id: economic_sector
      flatten: true

- id: electricity_emissions
  name: Kulutussähkön päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori4
      value: economic_sector
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Sähkö
    - column: Sektori2
    - column: Sektori3
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true

- id: transport_emissions
  name: Liikenteen päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [vehicle_type, economic_sector]
  output_dimensions: [vehicle_type, economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori2
      value: economic_sector
    - rename_col: Sektori3
      value: vehicle_type
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Liikenne
    - column: Sektori4
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true
    - id: economic_sector
      flatten: true

- id: industry_machinery_emissions
  name: Teollisuuden ja työkoneiden päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori2
      value: economic_sector
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Teollisuus ja työkoneet
    - column: Sektori3
    - column: Sektori4
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true

- id: waste_management_emissions
  name: Jätteiden käsittelyn päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [waste_treatment, economic_sector]
  output_dimensions: [waste_treatment, economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori4
      value: economic_sector
    - rename_col: Sektori3
      value: waste_treatment
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Jätteiden käsittely
    - column: Sektori2
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: waste_treatment
      flatten: true
    - id: economic_sector
      flatten: true

- id: agriculture_emissions
  name: Maatalouden päästöt
  type: generic.GenericNode
  quantity: emissions
  unit: kt/a
  input_dimensions: [economic_sector]
  output_dimensions: [economic_sector]
  input_datasets:
  - id: hsy/pks_khk_paastot
    tags: [baseline]
    forecast_from: 2025
    column: Päästöt
    filters:
    - rename_col: Vuosi
      value: Year
    - rename_col: Sektori2
      value: economic_sector
    - column: Kaupunki
      ref: municipality_name
    - column: Sektori1
      value: Maatalous
    - column: Sektori3
    - column: Sektori4
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: economic_sector
      flatten: true

pages:

- id: home
  name_fi: HSY-päästöt
  name_en: HSY emissions
  name_sv: HSY-emissioner
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: HSY-päästöt
  lead_title_en: HSY emissions
  lead_title_sv: HSY-emissioner

scenarios:

- id: baseline
  name_fi: Helsingin päästöt
  params:
  - id: municipality_name
    value: Helsinki

- id: default
  default: true
  name_fi: Espoon päästöt
  all_actions_enabled: true
  params:
  - id: municipality_name
    value: Espoo

- id: vantaa
  name_fi: Vantaan päästöt
  params:
  - id: municipality_name
    value: Vantaa

- id: kauniainen
  name_fi: Kauniaisten päästöt
  params:
  - id: municipality_name
    value: Kauniainen
