id: krakow-c4c
default_language: en
supported_languages: []
site_url: https://krakow-c4c.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: e99c727bcf999073d1b16f0e2d6c806d123c9de3
  dvc_remote: kausal-s3
name: Kraków Greenhouse Gas Inventory
owner: City of Kraków
theme_identifier: eu-climate-4-cast
target_year: 2030
model_end_year: 2030
minimum_historical_year: 2018
maximum_historical_year: 2023
emission_unit: kt_co2e/a
emission_forecast_from: 2024
emission_dimensions: [scope, sector]
features:
  baseline_visible_in_graphs: true

dimensions:
- id: scope
  label: Scope
  categories:
  - id: scope1
    label: Scope 1
  - id: scope2
    label: Scope 2
  - id: scope3
    label: Scope 3

- id: vehicle_type
  label: Vehicle Type
  categories:
  - id: buses
    label: Buses
  - id: local_trains
    label: Local Trains
  - id: passenger_cars
    label: Passenger Cars
  - id: trams
    label: Trams
  - id: trucks
    label: Trucks

- id: sector
  label: GPC Sector
  categories:
  - id: i
    label: I Stationary
  - id: i1
    label: I.1 Residential
  - id: i11
    label: I.1.1 Residential Fuel
  - id: i12
    label: I.1.2 Residential Grid Energy
  - id: i13
    label: I.1.3 Residential T & D Loss
  - id: i2
    label: I.2 Commercial & Institutional
  - id: i21
    label: I.2.1 Commercial & Institutional Fuel
  - id: i22
    label: I.2.2 Commercial & Institutional Grid Energy
  - id: i23
    label: I.2.3 Commercial & Institutional T & D Loss
  - id: i3
    label: I.3 Manufacturing
  - id: i31
    label: I.3.1 Manufacturing Fuel
  - id: i32
    label: I.3.2 Manufacturing Grid Energy
  - id: i33
    label: I.3.3 Manufacturing T & D Loss
  - id: i4
    label: I.4 Energy
  - id: i41
    label: I.4.1 Energy Fuel
  - id: i42
    label: I.4.2 Energy Grid Energy
  - id: i43
    label: I.4.3 Energy T & D Loss
  - id: i5
    label: I.5 Ag, Forestry, & Fishing
  - id: i51
    label: I.5.1 Ag, Forestry, & Fishing Fuel
  - id: i52
    label: I.5.2 Ag, Forestry, & Fishing Grid Energy
  - id: i53
    label: I.5.3 Ag, Forestry, & Fishing T & D Loss
  - id: i6
    label: I.6 Non-Specified
  - id: i61
    label: I.6.1 Non-Specified Fuel
  - id: i62
    label: I.6.2 Non-Specified Grid Energy
  - id: i63
    label: I.6.3 Non-Specified T & D Loss
  - id: i7
    label: I.7 Fugitive Coal
  - id: i71
    label: I.7.1 Fugitive Coal
  - id: i8
    label: I.8 Fugitive Oil & Natural Gas
  - id: i81
    label: I.8.1 Fugitive Oil & Natural Gas
  - id: ii
    label: II Transportation
  - id: ii1
    label: II.1 On-Road Transport
  - id: ii11
    label: II.1.1 On-Road Transport Fuel
  - id: ii12
    label: II.1.2 On-Road Transport Grid Energy
  - id: ii13
    label: II.1.3 On-Road Transport Outside City, T & D Loss
  - id: ii2
    label: II.2 Railway
  - id: ii21
    label: II.2.1 Railway Fuel
  - id: ii22
    label: II.2.2 Railway Grid Energy
  - id: ii23
    label: II.2.3 Railway Outside City, T & D Loss
  - id: ii3
    label: II.3 Waterborne
  - id: ii31
    label: II.3.1 Waterborne Fuel
  - id: ii32
    label: II.3.2 Waterborne Grid Energy
  - id: ii33
    label: II.3.3 Waterborne Outside City, T & D Loss
  - id: ii4
    label: II.4 Aviation
  - id: ii41
    label: II.4.1 Aviation Fuel
  - id: ii42
    label: II.4.2 Aviation Grid Energy
  - id: ii43
    label: II.4.3 Aviation Outside City, T & D Loss
  - id: ii5
    label: II.5 Off-Road Transport
  - id: ii51
    label: II.5.1 Off-Road Transport Fuel
  - id: ii52
    label: II.5.2 Off-Road Transport Grid Energy
  - id: ii53
    label: II.5.3 Off-Road Transport Outside City, T & D Loss
  - id: iii
    label: III Waste
  - id: iii1
    label: III.1 Solid Waste
  - id: iii11
    label: III.1.1 Solid Waste Disposed in City
  - id: iii12
    label: III.1.2 Solid Waste Disposed Outside City
  - id: iii2
    label: III.2 Biological Waste
  - id: iii21
    label: III.2.1 Biological Waste Treated in City
  - id: iii22
    label: III.2.2 Biological Waste Treated Outside City
  - id: iii3
    label: III.3 Incineration
  - id: iii31
    label: III.3.1 Incineration in City
  - id: iii32
    label: III.3.2 Incineration Outside City
  - id: iii4
    label: III.4 Wastewater
  - id: iii41
    label: III.4.1 Wastewater Treated in City
  - id: iii42
    label: III.4.2 Wastewater Treated Outside City
  - id: iv
    label: IV IPPU
  - id: iv1
    label: IV.1 Industrial Processes
  - id: iv2
    label: IV.2 Product Use
  - id: v
    label: V AFOLU
  - id: v1
    label: V.1 Livestock
  - id: v2
    label: V.2 Land
  - id: v3
    label: V.3 Aggregate Sources

emission_sectors:
- id: net_emissions
  name: Net Emissions
  is_outcome: true

nodes:
# ----- Stationary

- id: i1_residential_emissions
  name: I.1 Residential Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/stationary
    column: emissions
    filters:
    - dimension: sector
      categories: [i11, i12, i13]
  output_nodes:
  - id: i_stationary_emissions

- id: i2_commercial_and_institutional_emissions
  name: I.2 Commercial & Institutional Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/stationary
    column: emissions
    filters:
    - dimension: sector
      categories: [i21, i22, i23]
  output_nodes:
  - id: i_stationary_emissions

- id: i4_energy_emissions
  name: I.4 Energy Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/stationary
    column: emissions
    filters:
    - dimension: sector
      categories: [i41]
  output_nodes:
  - id: i_stationary_emissions

- id: i_stationary_emissions
  name: I Stationary Emissions
  color: '#4E79A7'
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  output_nodes:
  - id: net_emissions

# ----- Transportation

- id: ii11_onroad_transport_fuel_emissions
  name: II.1.1 On-Road Transport Fuel Emissions
  short_name: II.1.1 Fuel Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii11]
  output_nodes:
  - id: ii1_onroad_transport_emissions

- id: ii12_onroad_transport_grid_energy_emissions
  name: II.1.2 On-Road Transport Grid Energy Emissions
  short_name: II.1.2 Grid Energy Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii12]
  output_nodes:
  - id: ii1_onroad_transport_emissions

- id: ii13_onroad_transport_outboundary_td_loss_emissions
  name: II.1.3 On-Road Transport Out-Boundary & Transmission Loss Emissions
  short_name: II.1.3 Out-Boundary & Transmission Loss Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii13]
  output_nodes:
  - id: ii1_onroad_transport_emissions

- id: ii1_onroad_transport_emissions
  name: II.1 On-Road Transport Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  output_nodes:
  - id: ii_transportation_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true

- id: ii21_railway_fuel_emissions
  name: II.2.1 Railway Fuel Emissions
  short_name: II.2.1 Fuel Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii21]
  output_nodes:
  - id: ii2_railway_emissions

- id: ii22_railway_grid_energy_emissions
  name: II.2.2 Railway Grid Energy Emissions
  short_name: II.2.2 Grid Energy Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii22]
  output_nodes:
  - id: ii2_railway_emissions

- id: ii23_railway_outboundary_td_loss_emissions
  name: II.2.3 Railway Out-Boundary & Transmission Loss Emissions
  short_name: II.2.3 Out-Boundary & Transmission Loss Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii23]
  output_nodes:
  - id: ii2_railway_emissions

- id: ii2_railway_emissions
  name: II.2 Railway Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [vehicle_type, scope, sector]
  output_dimensions: [vehicle_type, scope, sector]
  output_nodes:
  - id: ii_transportation_emissions
    from_dimensions:
    - id: vehicle_type
      flatten: true

- id: ii3_waterborne_transport_emissions
  name: II.3 Waterborne Transport Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii31]
  output_nodes:
  - id: ii_transportation_emissions

- id: ii4_aviation_emissions
  name: II.4 Aviation Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii41]
  output_nodes:
  - id: ii_transportation_emissions

- id: ii5_offroad_transport_emissions
  name: II.5 Off-Road Transport Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/transportation
    column: emissions
    filters:
    - dimension: sector
      categories: [ii51]
  output_nodes:
  - id: ii_transportation_emissions

- id: ii_transportation_emissions
  name: II Transportation Emissions
  color: '#E15759'
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  output_nodes:
  - id: net_emissions

# ----- Waste

- id: iii2_biological_waste_emissions
  name: III.2 Biological Waste Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/waste
    column: emissions
    filters:
    - dimension: sector
      categories: [iii21, iii22]
  output_nodes:
  - id: iii_waste_emissions

- id: iii4_wastewater_emissions
  name: III.4 Wastewater Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  input_datasets:
  - id: krakow/waste
    column: emissions
    filters:
    - dimension: sector
      categories: [iii41]
  output_nodes:
  - id: iii_waste_emissions

- id: iii_waste_emissions
  name: III Waste Emissions
  color: '#59A14F'
  type: simple.AdditiveNode
  quantity: emissions
  unit: kt_co2e/a
  input_dimensions: [scope, sector]
  output_dimensions: [scope, sector]
  output_nodes:
  - id: net_emissions

pages:
- id: home
  name: Kraków Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Kraków Climate-4-CAST Decision Support Tool
  lead_paragraph: Greenhouse gas inventory (2018-2023) and forecast (2024-2030) for the City of Kraków.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Plan
  all_actions_enabled: true