id: norderstedt-c4c
default_language: en
supported_languages: []
site_url: https://norderstedt-c4c.paths.kausal.tech
dataset_repo:
  url: https://github.com/kausaltech/dvctest.git
  commit: 913722f2a68c46a4425ec4c9832d34d9f3e4026c
  dvc_remote: kausal-s3
name: Norderstedt Greenhouse Gas Inventory
owner: City of Norderstedt
theme_identifier: eu-climate-4-cast
target_year: 2040
model_end_year: 2040
minimum_historical_year: 2020
maximum_historical_year: 2023
emission_unit: t/a
emission_forecast_from: 2024
emission_dimensions: [] # ['scope', 'ghg']
features:
  baseline_visible_in_graphs: true

action_groups:
- id: i_stationary
  name: Stationary
- id: v_afolu
  name: AFOLU

# impact_overviews:
# - graph_type: cost_effectiveness
#   cost_node: net_price
#   impact_node: net_emissions
#   invert_cost: false
#   invert_impact: true
#   indicator_unit: EUR/t
#   cost_unit: EUR
#   impact_unit: t
#   plot_limit_for_indicator: 1000
#   label: Marginal Abatement Cost

dimensions:
- id: scope
  label: Scope
  categories:
  - id: scope1
    label: 'Scope 1'
  - id: scope2
    label: 'Scope 2'

- id: ghg
  label: GHG
  categories:
  - id: co2
    label: 'CO2'

- id: energy_carrier
  label: Energy Carrier
  categories:
  - id: electricity
    label: 'Electricity'

- id: cost_type
  label: Cost Type
  categories:
  - id: operations
    label: 'Operations'
  - id: capex_infrastructure
    label: 'Capex, Infrastructure'

- id: sector
  label: GPC Sector
  categories:
  - id: i
    label: 'I Stationary'
  - id: i1
    label: 'I.1 Residential'
  - id: i11
    label: 'I.1.1 Residential Fuel'
  - id: i12
    label: 'I.1.2 Residential Grid Energy'
  - id: i13
    label: 'I.1.3 Residential T & D Loss'
  - id: i2
    label: 'I.2 Commercial & Institutional'
  - id: i21
    label: 'I.2.1 Commercial & Institutional Fuel'
  - id: i22
    label: 'I.2.2 Commercial & Institutional Grid Energy'
  - id: i23
    label: 'I.2.3 Commercial & Institutional T & D Loss'
  - id: i3
    label: 'I.3 Manufacturing'
  - id: i31
    label: 'I.3.1 Manufacturing Fuel'
  - id: i32
    label: 'I.3.2 Manufacturing Grid Energy'
  - id: i33
    label: 'I.3.3 Manufacturing T & D Loss'
  - id: i4
    label: 'I.4 Energy'
  - id: i41
    label: 'I.4.1 Energy Fuel'
  - id: i42
    label: 'I.4.2 Energy Grid Energy'
  - id: i43
    label: 'I.4.3 Energy T & D Loss'
  - id: i5
    label: 'I.5 Ag, Forestry, & Fishing'
  - id: i51
    label: 'I.5.1 Ag, Forestry, & Fishing Fuel'
  - id: i52
    label: 'I.5.2 Ag, Forestry, & Fishing Grid Energy'
  - id: i53
    label: 'I.5.3 Ag, Forestry, & Fishing T & D Loss'
  - id: i6
    label: 'I.6 Non-Specified'
  - id: i61
    label: 'I.6.1 Non-Specified Fuel'
  - id: i62
    label: 'I.6.2 Non-Specified Grid Energy'
  - id: i63
    label: 'I.6.3 Non-Specified T & D Loss'
  - id: i7
    label: 'I.7 Fugitive Coal'
  - id: i71
    label: 'I.7.1 Fugitive Coal'
  - id: i8
    label: 'I.8 Fugitive Oil & Natural Gas'
  - id: i81
    label: 'I.8.1 Fugitive Oil & Natural Gas'
  - id: ii
    label: 'II Transportation'
  - id: ii1
    label: 'II.1 On-Road Transport'
  - id: ii11
    label: 'II.1.1 On-Road Transport Fuel'
  - id: ii12
    label: 'II.1.2 On-Road Transport Grid Energy'
  - id: ii13
    label: 'II.1.3 On-Road Transport Outside City, T & D Loss'
  - id: ii2
    label: 'II.2 Railway'
  - id: ii21
    label: 'II.2.1 Railway Fuel'
  - id: ii22
    label: 'II.2.2 Railway Grid Energy'
  - id: ii23
    label: 'II.2.3 Railway Outside City, T & D Loss'
  - id: ii3
    label: 'II.3 Waterborne'
  - id: ii31
    label: 'II.3.1 Waterborne Fuel'
  - id: ii32
    label: 'II.3.2 Waterborne Grid Energy'
  - id: ii33
    label: 'II.3.3 Waterborne Outside City, T & D Loss'
  - id: ii4
    label: 'II.4 Aviation'
  - id: ii41
    label: 'II.4.1 Aviation Fuel'
  - id: ii42
    label: 'II.4.2 Aviation Grid Energy'
  - id: ii43
    label: 'II.4.3 Aviation Outside City, T & D Loss'
  - id: ii5
    label: 'II.5 Off-Road Transport'
  - id: ii51
    label: 'II.5.1 Off-Road Transport Fuel'
  - id: ii52
    label: 'II.5.2 Off-Road Transport Grid Energy'
  - id: ii53
    label: 'II.5.3 Off-Road Transport Outside City, T & D Loss'
  - id: iii
    label: 'III Waste'
  - id: iii1
    label: 'III.1 Solid Waste'
  - id: iii11
    label: 'III.1.1 Solid Waste Disposed in City'
  - id: iii12
    label: 'III.1.2 Solid Waste Disposed Outside City'
  - id: iii2
    label: 'III.2 Biological Waste'
  - id: iii21
    label: 'III.2.1 Biological Waste Treated in City'
  - id: iii22
    label: 'III.2.2 Biological Waste Treated Outside City'
  - id: iii3
    label: 'III.3 Incineration'
  - id: iii31
    label: 'III.3.1 Incineration in City'
  - id: iii32
    label: 'III.3.2 Incineration Outside City'
  - id: iii4
    label: 'III.4 Wastewater'
  - id: iii41
    label: 'III.4.1 Wastewater Treated in City'
  - id: iii42
    label: 'III.4.2 Wastewater Treated Outside City'
  - id: iv
    label: 'IV IPPU'
  - id: iv1
    label: 'IV.1 Industrial Processes'
  - id: iv2
    label: 'IV.2 Product Use'
  - id: v
    label: 'V AFOLU'
  - id: v1
    label: 'V.1 Livestock'
  - id: v2
    label: 'V.2 Land'
  - id: v3
    label: 'V.3 Aggregate Sources'

- id: action
  label: Action
  categories:
  - id: change_streetlights_to_led
    label: 'Change Streetlights to LED'
  - id: tree_donation
    label: 'Tree Donation'
  - id: reforestation
    label: 'Reforestation'
  - id: energy_refurbishment_for_private_households
    label: 'Energy Refurbishment for Private Households'
  - id: energy_refurbishment_for_school_building
    label: 'Energy Refurbishment for School Building'
  - id: new_school_building
    label: 'New School Building'

emission_sectors:
- id: net_emissions
  name: Net Emissions
  is_outcome: true

nodes:
- id: net_price
  name: Net Price
  type: simple.AdditiveNode
  quantity: currency
  unit: EUR/a
  input_dimensions: [] # ['scope']
  output_dimensions: [] # ['scope']
  is_outcome: true

- id: i22_commercial_and_institutional_grid_energy_consumption
  name: I.2.2 Commercial & Institutional Grid Energy Consumption
  type: gpc.DatasetNode
  quantity: energy
  unit: kWh/a
  input_dimensions: ['scope', 'energy_carrier']
  output_dimensions: ['scope', 'energy_carrier']
  params:
    gpc_sector: I.2.2
  input_datasets:
  - id: gpc/norderstedt
    forecast_from: 2024
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_consumption_emissions
    to_dimensions:
    - id: scope
    - id: energy_carrier
  - id: i22_commercial_and_institutional_grid_energy_consumption_price
    to_dimensions:
    - id: scope
    - id: energy_carrier

- id: i22_commercial_and_institutional_grid_energy_consumption_emissions
  name: I.2.2 Commercial & Institutional Grid Energy Consumption Emissions
  type: simple.MultiplicativeNode
  quantity: emissions
  unit: t/a
  input_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_nodes:
  - id: i2_commercial_and_institutional_total_emissions
    to_dimensions:
    - id: scope
    - id: ghg
    - id: energy_carrier

- id: i22_commercial_and_institutional_grid_energy_consumption_price
  name: I.2.2 Commercial & Institutional Grid Energy Consumption Price
  type: simple.MultiplicativeNode
  quantity: currency
  unit: EUR/a
  input_dimensions: ['cost_type', 'scope', 'energy_carrier']
  output_dimensions: ['cost_type', 'scope', 'energy_carrier']
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_total_price
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: scope
    - id: cost_type

- id: i22_commercial_and_institutional_grid_energy_price
  name: I.2.2 Commercial & Institutional Grid Energy Price
  type: simple.AdditiveNode
  quantity: currency
  unit: EUR/a
  input_dimensions: ['cost_type', 'scope']
  output_dimensions: ['cost_type', 'scope']
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_total_price
    to_dimensions:
    - id: scope
    - id: cost_type

- id: i22_commercial_and_institutional_grid_energy_total_price
  name: I.2.2 Commercial & Institutional Grid Energy Total Price
  type: simple.AdditiveNode
  quantity: currency
  unit: EUR/a
  input_dimensions: ['cost_type', 'scope']
  output_dimensions: ['cost_type', 'scope']
  output_nodes:
  - id: i2_commercial_and_institutional_total_price
    to_dimensions:
    - id: scope
    - id: cost_type

- id: i22_commercial_and_institutional_grid_energy_emission_factor
  name: I.2.2 Commercial & Institutional Grid Energy Emission Factor
  type: gpc.DatasetNode
  quantity: emission_factor
  unit: g/kWh
  input_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_dimensions: ['scope', 'ghg', 'energy_carrier']
  params:
    gpc_sector: I.2.2
  input_datasets:
  - id: gpc/norderstedt
    forecast_from: 2024
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_consumption_emissions
    to_dimensions:
    - id: scope
    - id: ghg
    - id: energy_carrier

- id: i22_commercial_and_institutional_grid_energy_unit_price
  name: I.2.2 Commercial & Institutional Grid Energy Unit Price
  type: gpc.DatasetNode
  quantity: unit_price
  unit: EUR/kWh
  input_dimensions: ['cost_type', 'scope', 'energy_carrier']
  output_dimensions: ['cost_type', 'scope', 'energy_carrier']
  params:
    gpc_sector: I.2.2
  input_datasets:
  - id: gpc/norderstedt
    forecast_from: 2024
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_consumption_price
    to_dimensions:
    - id: scope
    - id: energy_carrier
    - id: cost_type

- id: v2_land_emissions
  name: V.2 Land Emissions
  type: gpc.DatasetNode
  quantity: emissions
  unit: t/a
  input_dimensions: ['scope', 'ghg']
  output_dimensions: ['scope', 'ghg']
  params:
    gpc_sector: V.2
  input_datasets:
  - id: gpc/norderstedt
    forecast_from: 2024
  output_nodes:
  - id: v_afolu_total_emissions
    to_dimensions:
    - id: scope
    - id: ghg

- id: v2_land_price
  name: V.2 Land Price
  type: simple.AdditiveNode
  quantity: currency
  unit: EUR/a
  input_dimensions: ['scope']
  output_dimensions: ['scope']
  output_nodes:
  - id: v_afolu_total_price
    to_dimensions:
    - id: scope

- id: i2_commercial_and_institutional_total_emissions
  name: I.2 Commercial & Institutional Total Emissions
  type: simple.AdditiveNode
  quantity: emissions
  unit: t/a
  input_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_nodes:
  - id: i_stationary_total_emissions
    to_dimensions:
    - id: scope
    - id: ghg
    - id: energy_carrier

- id: i_stationary_total_emissions
  name: I Stationary Total Emissions
  type: simple.AdditiveNode
  color: '#4e79a7'
  quantity: emissions
  unit: t/a
  input_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_dimensions: ['scope', 'ghg', 'energy_carrier']
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: scope
      flatten: true
    - id: ghg
      flatten: true
    - id: energy_carrier
      flatten: true

- id: v_afolu_total_emissions
  name: V AFOLU Total Emissions
  type: simple.AdditiveNode
  color: '#b07aa1'
  quantity: emissions
  unit: t/a
  input_dimensions: ['scope', 'ghg']
  output_dimensions: ['scope', 'ghg']
  output_nodes:
  - id: net_emissions
    from_dimensions:
    - id: scope
      flatten: true
    - id: ghg
      flatten: true

- id: v_afolu_total_price
  name: V AFOLU Total Price
  type: simple.AdditiveNode
  color: '#b07aa1'
  quantity: currency
  unit: EUR/a
  input_dimensions: ['scope']
  output_dimensions: ['scope']
  output_nodes:
  - id: net_price
    from_dimensions:
    - id: scope
      flatten: true

- id: i2_commercial_and_institutional_total_price
  name: I.2 Commercial & Institutional Total Price
  type: simple.AdditiveNode
  quantity: currency
  unit: EUR/a
  input_dimensions: ['cost_type', 'scope']
  output_dimensions: ['cost_type', 'scope']
  output_nodes:
  - id: i_stationary_total_price
    to_dimensions:
    - id: scope
    - id: cost_type

- id: i_stationary_total_price
  name: I Stationary Total Price
  type: simple.AdditiveNode
  color: '#4e79a7'
  quantity: currency
  unit: EUR/a
  input_dimensions: ['cost_type', 'scope']
  output_dimensions: ['cost_type', 'scope']
  output_nodes:
  - id: net_price
    from_dimensions:
    - id: cost_type
      flatten: true
    - id: scope
      flatten: true

actions:
- id: change_streetlights_to_led
  name: Change Streetlights to LED
  type: gpc.DatasetActionMFM
  group: i_stationary
  color: '#4e79a7'
  input_dimensions: ['cost_type', 'scope', 'energy_carrier']
  output_dimensions: ['cost_type', 'scope', 'energy_carrier']
  params:
    action: Change Streetlights to LED
  input_datasets:
  - id: gpc/norderstedt_simple_actions
  output_metrics:
  - id: i22_energy
    unit: kWh/a
    quantity: energy
  - id: i22_currency
    unit: EUR/a
    quantity: currency
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_consumption
    metrics: [i22_energy]
    from_dimensions:
    - id: cost_type
      flatten: true
    to_dimensions:
    - id: scope
    - id: energy_carrier
  - id: i22_commercial_and_institutional_grid_energy_price
    metrics: [i22_currency]
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: scope
    - id: cost_type

- id: change_streetlights_to_led_by_2029
  name: Change Streetlights to LED (by 2029)
  type: gpc.DatasetActionMFM
  group: i_stationary
  color: '#4e79a7'
  input_dimensions: ['cost_type', 'scope', 'energy_carrier']
  output_dimensions: ['cost_type', 'scope', 'energy_carrier']
  params:
    action: Change Streetlights to LED (by 2029)
  input_datasets:
  - id: gpc/norderstedt_simple_actions
  output_metrics:
  - id: i22_energy
    unit: kWh/a
    quantity: energy
  - id: i22_currency
    unit: EUR/a
    quantity: currency
  output_nodes:
  - id: i22_commercial_and_institutional_grid_energy_consumption
    metrics: [i22_energy]
    from_dimensions:
    - id: cost_type
      flatten: true
    to_dimensions:
    - id: scope
    - id: energy_carrier
  - id: i22_commercial_and_institutional_grid_energy_price
    metrics: [i22_currency]
    from_dimensions:
    - id: energy_carrier
      flatten: true
    to_dimensions:
    - id: scope
    - id: cost_type

- id: tree_donation
  name: Tree Donation
  type: gpc.DatasetActionMFM
  group: v_afolu
  color: '#b07aa1'
  input_dimensions: ['scope', 'ghg']
  output_dimensions: ['scope', 'ghg']
  params:
    action: Tree Donation
  input_datasets:
  - id: gpc/norderstedt_simple_actions
  output_metrics:
  - id: v2_emissions
    unit: kg/a
    quantity: emissions
  - id: v2_currency
    unit: EUR/a
    quantity: currency
  output_nodes:
  - id: v2_land_emissions
    metrics: [v2_emissions]
    to_dimensions:
    - id: scope
    - id: ghg
  - id: v2_land_price
    metrics: [v2_currency]
    from_dimensions:
    - id: ghg
      flatten: true
    to_dimensions:
    - id: scope

pages:
- id: home
  name: Norderstedt Greenhouse Gas Inventory
  path: /
  type: emission
  outcome_node: net_emissions
  lead_title: Norderstedt Climate-4-CAST Decision Support Tool
  lead_paragraph: Greenhouse gas inventory (2020-2023) and forecast (2024-2040) for the City of Norderstedt.

scenarios:
- id: baseline
  name: Business as Usual

- id: default
  default: true
  name: Climate Action Plan
  params:
  - id: change_streetlights_to_led.enabled
    value: true
  - id: change_streetlights_to_led_by_2029.enabled
    value: false
  - id: tree_donation.enabled
    value: true
