# Generated by Django 3.2.4 on 2021-10-14 10:04

from django.db import migrations, models
import django.db.models.deletion
import paths.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', paths.utils.IdentifierField(max_length=50, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
            ],
            options={
                'verbose_name': 'Instance',
                'verbose_name_plural': 'Instances',
            },
        ),
        migrations.CreateModel(
            name='NodeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', paths.utils.IdentifierField(max_length=50, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('forecast_values', models.JSONField(null=True)),
                ('historical_values', models.JSONField(null=True)),
                ('params', models.JSONField(null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='nodes.instanceconfig')),
            ],
            options={
                'verbose_name': 'Node',
                'verbose_name_plural': 'Nodes',
                'unique_together': {('instance', 'identifier')},
            },
        ),
        migrations.CreateModel(
            name='NodeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('is_forecast', models.BooleanField()),
                ('value', models.FloatField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='nodes.nodeconfig')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceHostname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=100, unique=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostnames', to='nodes.instanceconfig')),
            ],
            options={
                'verbose_name': 'Instance hostname',
                'verbose_name_plural': 'Instance hostnames',
            },
        ),
    ]
