# Generated by Django 3.2.4 on 2021-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancehostname',
            name='base_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
