# Generated by Django 3.2.8 on 2021-10-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_add_fields_from_pages_app'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeconfig',
            name='forecast_values',
        ),
        migrations.RemoveField(
            model_name='nodeconfig',
            name='historical_values',
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='input_data',
            field=models.JSONField(editable=False, null=True),
        ),
    ]
