# Generated by Django 3.2.16 on 2022-10-28 06:52

from django.db import migrations, models
import django.db.models.deletion
import paths.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0010_increase_node_identifier_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='protection_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='identifier',
            field=paths.utils.IdentifierField(max_length=100, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='instancehostname',
            name='base_path',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='instancehostname',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='instancehostname',
            unique_together={('hostname', 'base_path'), ('instance', 'hostname')},
        ),
        migrations.CreateModel(
            name='InstanceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='nodes.instanceconfig')),
            ],
            options={
                'verbose_name': 'Instance token',
                'verbose_name_plural': 'Instance tokens',
            },
        ),
    ]
