# Generated by Django 3.2.16 on 2023-03-03 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0014_datasource_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='url',
            field=models.URLField(null=True, blank=True, verbose_name='URL to source'),
        ),
    ]
