# Generated by Django 3.2.18 on 2023-03-20 09:41

from django.db import migrations, models
import django.db.models.deletion
import paths.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0015_datasource_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasource',
            options={'verbose_name': 'Data source', 'verbose_name_plural': 'Data sources'},
        ),
        migrations.AlterField(
            model_name='datasource',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='edition'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='nodes.instanceconfig', verbose_name='instance'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)')], default=paths.utils.get_default_language, max_length=8), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='primary_language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)')], default=paths.utils.get_default_language, max_length=8),
        ),
    ]
