# Generated by Django 4.1.12 on 2023-10-17 12:29

from django.db import migrations, models
import django.db.models.deletion
import paths.utils
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nodes', '0018_add_wagtail_mixins_to_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='admin_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_instances', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='identifier',
            field=paths.utils.IdentifierField(max_length=100, unique=True, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=20, null=True),
        ),
    ]
