# Generated by Django 4.1.12 on 2023-10-18 09:30

import django.contrib.postgres.fields
from django.db import migrations, models
import paths.utils


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0019_add_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancehostname',
            name='extra_script_urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=300), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)')], default=paths.utils.get_default_language, max_length=8), default=list, size=None),
        ),
    ]
