# Generated by Django 4.1.12 on 2023-11-06 16:57

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0021_cache_invalidated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='goal',
            field=wagtail.fields.RichTextField(blank=True, max_length=200, null=True, verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='indicator_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicates_nodes', to='nodes.nodeconfig'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='i18n',
            field=modeltrans.fields.TranslationField(fields=('name', 'short_description', 'description', 'goal'), required_languages=(), virtual_fields=True),
        ),
    ]
