# Generated by Django 5.0.6 on 2024-07-05 09:11

import paths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0024_add_node_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('cs', 'Czech'), ('da', 'Danish'), ('pl', 'Polish'), ('lv', 'Latvian')], default=paths.utils.get_default_language, max_length=8), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='primary_language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('cs', 'Czech'), ('da', 'Danish'), ('pl', 'Polish'), ('lv', 'Latvian')], default=paths.utils.get_default_language, max_length=8),
        ),
    ]
