# Generated by Django 5.1.2 on 2024-10-30 10:30

import django.db.models.deletion
import paths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nodes', '0026_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='viewer_group',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viewer_instances', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('cs', 'Czech'), ('da', 'Danish'), ('pl', 'Polish'), ('lv', 'Latvian'), ('es-US', 'Spanish (United States)')], default=paths.utils.get_default_language, max_length=8), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='instanceconfig',
            name='primary_language',
            field=models.CharField(choices=[('en', 'English'), ('fi', 'Finnish'), ('sv', 'Swedish'), ('de', 'German'), ('de-CH', 'German (Switzerland)'), ('cs', 'Czech'), ('da', 'Danish'), ('pl', 'Polish'), ('lv', 'Latvian'), ('es-US', 'Spanish (United States)')], default=paths.utils.get_default_language, max_length=8),
        ),
    ]
