# Generated by Django 5.1.4 on 2025-03-10 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0028_alter_instanceconfig_other_languages_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSource',
        ),
    ]
