# Generated by Django 5.2.4 on 2025-08-06 13:58

from collections import Counter

from django.db import migrations


def ensure_unique_names(apps, schema_editor):
    InstanceConfig = apps.get_model('nodes', 'InstanceConfig')
    name_counter = Counter(InstanceConfig.objects.values_list('name', flat=True))
    for duplicate in (name for name, count in name_counter.items() if count > 1):
        for index, instance_config in enumerate(InstanceConfig.objects.filter(name=duplicate)):
            if index < 1:
                continue
            instance_config.name += f' ({index + 1})'
            instance_config.save(update_fields=['name'])


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0031_alter_nodeconfig_color'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_names, migrations.RunPython.noop),
    ]
