# Generated by Django 5.2.4 on 2025-08-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0032_ensure_unique_instanceconfig_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='name'),
        ),
    ]
