# Generated by Django 6.0.3 on 2026-03-22 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0023_alter_target_metric_onetoone'),
        ('nodes', '0038_instanceconfig_super_admin_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instanceconfig',
            options={'ordering': ['id'], 'verbose_name': 'Instance', 'verbose_name_plural': 'Instances'},
        ),
        migrations.AlterModelOptions(
            name='instancehostname',
            options={'ordering': ['instance', 'hostname'], 'verbose_name': 'Instance hostname', 'verbose_name_plural': 'Instance hostnames'},
        ),
        migrations.AlterModelOptions(
            name='instancetoken',
            options={'ordering': ['instance', '-created_at'], 'verbose_name': 'Instance token', 'verbose_name_plural': 'Instance tokens'},
        ),
        migrations.AlterModelOptions(
            name='nodeconfig',
            options={'ordering': ['instance', 'id'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AlterModelOptions(
            name='nodedataset',
            options={'ordering': ['node', 'dataset'], 'verbose_name': 'Node dataset', 'verbose_name_plural': 'Node datasets'},
        ),
        migrations.AlterUniqueTogether(
            name='nodedataset',
            unique_together={('node', 'dataset')},
        ),
    ]
