# Generated by Django 6.0.3 on 2026-03-12 20:03

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.db.models.deletion
import modeltrans.fields
import paths.utils
import wagtail_color_panel.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0022_alter_datasetmetric_options_and_more'),
        ('nodes', '0038_instanceconfig_super_admin_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='config_source',
            field=models.CharField(choices=[('yaml', 'YAML'), ('database', 'Database')], default='yaml', max_length=20),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='dataset_repo_commit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='dataset_repo_dvc_remote',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='dataset_repo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='emission_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='features',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='maximum_historical_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='minimum_historical_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='model_end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='reference_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='target_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='decision_level',
            field=models.CharField(blank=True, choices=[('nation', 'Nation'), ('region', 'Region'), ('local', 'Local')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='extra',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='formula',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='input_ports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='is_outcome',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='node_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='node_type',
            field=models.CharField(blank=True, choices=[('formula', 'Formula'), ('action', 'Action')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='output_ports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='pipeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ActionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('identifier', paths.utils.IdentifierField(max_length=100, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=200)),
                ('color', wagtail_color_panel.fields.ColorField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name',), required_languages=(), virtual_fields=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_groups', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Action group',
                'verbose_name_plural': 'Action groups',
                'ordering': ['order'],
                'unique_together': {('instance', 'identifier')},
            },
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='action_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='nodes.actiongroup'),
        ),
        migrations.CreateModel(
            name='DatasetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('port_id', models.CharField(help_text='Input port ID on the node (must match a port in node.input_ports)', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_ports', to='datasets.dataset')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ports', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_ports', to='datasets.datasetmetric')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ports', to='nodes.nodeconfig')),
            ],
            options={
                'verbose_name': 'Dataset port',
                'verbose_name_plural': 'Dataset ports',
                'constraints': [models.UniqueConstraint(fields=('node', 'port_id'), name='unique_dataset_port_per_input_port')],
            },
        ),
        migrations.CreateModel(
            name='NodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('from_port', models.CharField(default='output', help_text='Output port ID on the source node', max_length=100)),
                ('to_port', models.CharField(help_text='Input port ID on the target node', max_length=100)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='nodes.nodeconfig')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='nodes.nodeconfig')),
            ],
            options={
                'verbose_name': 'Node edge',
                'verbose_name_plural': 'Node edges',
                'constraints': [models.UniqueConstraint(fields=('to_node', 'to_port'), name='unique_edge_per_input_port')],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('identifier', paths.utils.IdentifierField(max_length=100, validators=[paths.utils.IdentifierValidator()], verbose_name='identifier')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(blank=True, choices=[('default', 'Default'), ('baseline', 'Baseline'), ('progress_tracking', 'Progress tracking')], max_length=30)),
                ('all_actions_enabled', models.BooleanField(default=False)),
                ('parameter_overrides', models.JSONField(blank=True, default=list)),
                ('i18n', modeltrans.fields.TranslationField(fields=('name', 'description'), required_languages=(), virtual_fields=True)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
            ],
            options={
                'verbose_name': 'Scenario',
                'verbose_name_plural': 'Scenarios',
                'unique_together': {('instance', 'identifier')},
            },
        ),
    ]
