# Generated by Django 6.0.3 on 2026-03-25 10:56

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.core.serializers.json
import django.db.models.deletion
import django_pydantic_field.fields
import nodes.defs.instance_defs
import nodes.defs.node_defs
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0024_alter_dataset_options_alter_datasetmetric_options_and_more'),
        ('nodes', '0039_alter_instanceconfig_options_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instancehostname',
            options={'ordering': ['instance', 'hostname', 'base_path'], 'verbose_name': 'Instance hostname', 'verbose_name_plural': 'Instance hostnames'},
        ),
        migrations.AlterModelOptions(
            name='nodeconfig',
            options={'ordering': ['instance', 'order'], 'verbose_name': 'Node', 'verbose_name_plural': 'Nodes'},
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='config_source',
            field=models.CharField(choices=[('yaml', 'YAML'), ('database', 'Database')], default='yaml', max_length=20),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiry date/time'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='expired',
            field=models.BooleanField(default=False, editable=False, verbose_name='expired'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='first_published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='first published at'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='go_live_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='go live date/time'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='has_unpublished_changes',
            field=models.BooleanField(default=False, editable=False, verbose_name='has unpublished changes'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='last_published_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last published at'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='live',
            field=models.BooleanField(default=True, editable=False, verbose_name='live'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='live_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='live revision'),
        ),
        migrations.AddField(
            model_name='instanceconfig',
            name='spec',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=nodes.defs.instance_defs.InstanceSpec, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=nodes.defs.instance_defs.InstanceSpec),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='node_type',
            field=models.CharField(blank=True, choices=[('formula', 'Formula'), ('action', 'Action')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='spec',
            field=django_pydantic_field.fields.PydanticSchemaField(config=None, default=nodes.defs.node_defs.NodeSpec, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=nodes.defs.node_defs.NodeSpec),
        ),
        migrations.CreateModel(
            name='DatasetPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('port_id', models.CharField(help_text='Input port ID on the node (must match a port in node.input_ports)', max_length=100)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_ports', to='datasets.dataset')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ports', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='node_ports', to='datasets.datasetmetric')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_ports', to='nodes.nodeconfig')),
            ],
            options={
                'verbose_name': 'Dataset port',
                'verbose_name_plural': 'Dataset ports',
                'ordering': ['node', 'metric__order'],
                'constraints': [models.UniqueConstraint(fields=('node', 'port_id'), name='unique_dataset_port_per_input_port')],
            },
        ),
        migrations.CreateModel(
            name='NodeEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('from_port', models.CharField(default='output', help_text='Output port ID on the source node', max_length=100)),
                ('to_port', models.CharField(help_text='Input port ID on the target node', max_length=100)),
                ('transformations', models.JSONField(blank=True, default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='nodes.nodeconfig')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='nodes.nodeconfig')),
            ],
            options={
                'verbose_name': 'Node edge',
                'verbose_name_plural': 'Node edges',
                'ordering': ['instance', 'from_node', 'to_node', 'to_port'],
                'constraints': [models.UniqueConstraint(fields=('to_node', 'to_port'), name='unique_edge_per_input_port')],
            },
        ),
    ]
