# Generated by Django 6.0.3 on 2026-04-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0040_trailhead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetport',
            name='port_id',
            field=models.UUIDField(help_text='Input port ID on the node (must match a port in node.input_ports)'),
        ),
        migrations.AlterField(
            model_name='nodeedge',
            name='from_port',
            field=models.UUIDField(default='output', help_text='Output port ID on the source node'),
        ),
        migrations.AlterField(
            model_name='nodeedge',
            name='to_port',
            field=models.UUIDField(help_text='Input port ID on the target node'),
        ),
    ]
