# Generated by Django 6.0.3 on 2026-04-19 09:11

import django.contrib.postgres.functions
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nodes', '0040_trailhead'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodeconfig',
            name='modified_at',
        ),
        migrations.AddField(
            model_name='datasetport',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='created_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='last_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified at'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='last_modified_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by'),
        ),
        migrations.AddField(
            model_name='nodeedge',
            name='latest_revision',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision'),
        ),
        migrations.AlterField(
            model_name='nodeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.CreateModel(
            name='InstanceChangeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('action', models.CharField(help_text="Top-level action that triggered the operation, e.g. 'node.delete'.", max_length=100)),
                ('source', models.CharField(choices=[('graphql', 'GraphQL'), ('rest', 'REST'), ('admin', 'Wagtail admin'), ('cli', 'CLI'), ('migration', 'Data migration')], default='graphql', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instance_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_operations', to='nodes.instanceconfig')),
                ('superseded_by', models.ForeignKey(blank=True, help_text='Set when this operation has been undone by another operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='nodes.instancechangeoperation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instance change operation',
                'verbose_name_plural': 'Instance change operations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceModelLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(help_text="Dotted action id, e.g. 'node.update'.", max_length=100)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of the affected row; GFK with object_id.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='nodes.instancechangeoperation')),
            ],
            options={
                'verbose_name': 'Instance model log entry',
                'verbose_name_plural': 'Instance model log entries',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='instancechangeoperation',
            index=models.Index(fields=['instance_config', '-created_at'], name='nodes_insta_instanc_27d57b_idx'),
        ),
        migrations.AddIndex(
            model_name='instancemodellogentry',
            index=models.Index(fields=['operation'], name='nodes_insta_operati_df914a_idx'),
        ),
        migrations.AddIndex(
            model_name='instancemodellogentry',
            index=models.Index(fields=['content_type', 'object_id'], name='nodes_insta_content_f2d2ec_idx'),
        ),
    ]
