# Generated by Django 6.0.3 on 2026-04-06 21:53

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import nodes.defs.edge_def
import typing
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0041_alter_datasetport_port_id_alter_nodeedge_from_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeedge',
            name='transformations',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(typing.Union, (nodes.defs.edge_def.SelectCategoriesTransformation, nodes.defs.edge_def.AssignCategoryTransformation, nodes.defs.edge_def.FlattenTransformation)),))),
        ),
    ]
