# Generated by Codex on 2026-05-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0045_instanceconfig_owned_by_instanceinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='yaml_mtime_hash',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True),
        ),
    ]
