# Generated by Django 6.0.3 on 2026-06-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0048_instance_owner_and_modelspec'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='copy_of',
            field=models.ForeignKey(blank=True, editable=False, help_text='The instance this one was copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='nodes.instanceconfig'),
        ),
        migrations.AddField(
            model_name='nodeconfig',
            name='copy_of',
            field=models.ForeignKey(blank=True, editable=False, help_text='The node this one was copied from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='nodes.nodeconfig'),
        ),
    ]
