# Generated by Django 6.0.3 on 2026-06-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0049_instanceconfig_copy_of_nodeconfig_copy_of'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hide this instance from the admin instance chooser. It remains reachable directly and via permissions.'),
        ),
    ]
