# Generated by Django 6.0.3 on 2026-07-11 04:40

import paths.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0051_instanceconfig_root_page_remove_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceconfig',
            name='other_languages',
            field=paths.utils.ChoiceArrayField(base_field=models.CharField(choices=paths.utils.get_supported_languages, default=paths.utils.get_default_language, max_length=8), blank=True, default=list),
        ),
    ]
