# Generated by Django 6.0.3 on 2026-07-29 09:54

import django.core.serializers.json
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import nodes.defs.transform_def
import typing
from django.db import migrations

# Stored edge transformations converge on the unified PortTransformOp
# vocabulary: `select_categories` and `assign_category` are `filter_dimension`
# and `assign_dimension` under other names. `flatten` is left alone — it is a
# port shape declaration with no operation equivalent, and it leaves the edge
# vocabulary for InputPortDef, not through renaming.

_FORWARD = {
    'select_categories': 'filter_dimension',
    'assign_category': 'assign_dimension',
}
_BACKWARD = {v: k for k, v in _FORWARD.items()}


def _rewrite(apps, schema_editor, kinds: dict[str, str], *, forward: bool):
    import json

    NodeEdge = apps.get_model('nodes', 'NodeEdge')
    table = NodeEdge._meta.db_table
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(f"SELECT id, uuid, transformations FROM {table} WHERE transformations::text != '[]'")  # noqa: S608
        rows = cursor.fetchall()
        for pk, edge_uuid, ops in rows:
            if isinstance(ops, str):
                ops = json.loads(ops)
            dirty = False
            for op in ops:
                new_kind = kinds.get(op.get('kind'))
                if new_kind is None:
                    continue
                if not forward and op.get('groups'):
                    raise RuntimeError(
                        f'Edge {edge_uuid} uses filter_dimension groups, which the legacy vocabulary cannot express',
                    )
                op['kind'] = new_kind
                if not forward:
                    op.pop('groups', None)
                dirty = True
            if dirty:
                cursor.execute(
                    f'UPDATE {table} SET transformations = %s WHERE id = %s',  # noqa: S608
                    [json.dumps(ops), pk],
                )


def modernize_edge_transformations(apps, schema_editor):
    _rewrite(apps, schema_editor, _FORWARD, forward=True)


def legacy_edge_transformations(apps, schema_editor):
    _rewrite(apps, schema_editor, _BACKWARD, forward=False)


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0053_dataset_port_spec_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeedge',
            name='transformations',
            field=django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(typing.Union, (nodes.defs.transform_def.FilterDimensionOp, nodes.defs.transform_def.AssignDimensionOp, nodes.defs.transform_def.DropNullsOp, nodes.defs.transform_def.FilterTemporalOp, nodes.defs.transform_def.EnsureUnitOp, nodes.defs.transform_def.SelectCategoriesTransformation, nodes.defs.transform_def.AssignCategoryTransformation, nodes.defs.transform_def.FlattenTransformation)),))),
        ),
        migrations.RunPython(modernize_edge_transformations, legacy_edge_transformations),
    ]
