# Generated by Django 6.0.3 on 2026-08-12 14:44

import django.contrib.postgres.fields
import django.contrib.postgres.functions
import django.core.serializers.json
import django.db.models.constraints
import django.db.models.deletion
import django_pydantic_field.compat.django
import django_pydantic_field.fields
import nodes.defs.transform_def
import typing
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0032_alter_datasource_url'),
        ('nodes', '0059_dataset_shape_profiles'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeInputPortBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_default=django.contrib.postgres.functions.RandomUUID(), editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='Last modified at')),
                ('port_id', models.UUIDField(help_text='Input port ID on the node (must match a port in node.input_ports)')),
                ('position', models.PositiveIntegerField(default=0, help_text='Stable order among values delivered to the input port, shared across source kinds.')),
                ('source_port_id', models.UUIDField(blank=True, help_text='Output port ID on the source node', null=True)),
                ('transformations', django_pydantic_field.fields.PydanticSchemaField(blank=True, config=None, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, schema=django_pydantic_field.compat.django.GenericContainer(list, (django_pydantic_field.compat.django.GenericContainer(typing.Union, (nodes.defs.transform_def.FilterDimensionOp, nodes.defs.transform_def.AssignDimensionOp, nodes.defs.transform_def.DropNullsOp, nodes.defs.transform_def.FilterTemporalOp, nodes.defs.transform_def.FilterColumnOp, nodes.defs.transform_def.RenameColumnOp, nodes.defs.transform_def.RenameItemOp, nodes.defs.transform_def.SetForecastFromOp, nodes.defs.transform_def.EnsureUnitOp, nodes.defs.transform_def.SelectMetricOp, nodes.defs.transform_def.IndexTemporalOp, nodes.defs.transform_def.RemapLegacyYearsOp, nodes.defs.transform_def.TagOperationOp, nodes.defs.transform_def.SelectCategoriesTransformation, nodes.defs.transform_def.AssignCategoryTransformation, nodes.defs.transform_def.FlattenTransformation)),)))),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list)),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node_input_bindings', to='datasets.dataset')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bindings', to='nodes.instanceconfig')),
                ('last_modified_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Last modified by')),
                ('latest_revision', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.revision', verbose_name='latest revision')),
                ('metric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='node_input_bindings', to='datasets.datasetmetric')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_bindings', to='nodes.nodeconfig')),
                ('source_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_bindings', to='nodes.nodeconfig')),
            ],
            options={
                'verbose_name': 'Node input binding',
                'verbose_name_plural': 'Node input bindings',
                'ordering': ['node', 'port_id', 'position'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('dataset__isnull', True), ('metric__isnull', True), ('source_node__isnull', False), ('source_port_id__isnull', False)), models.Q(('dataset__isnull', False), ('metric__isnull', False), ('source_node__isnull', True), ('source_port_id__isnull', True)), _connector='OR'), name='node_input_binding_has_one_source'), models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('node', 'port_id', 'position'), name='node_input_binding_position_is_unique')],
            },
        ),
    ]
