# Generated by Django 6.1 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0062_instanceconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceconfig',
            name='yaml_spec_version',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
