# Generated by Django 6.1 on 2026-08-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0063_instanceconfig_yaml_spec_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeconfig',
            name='is_editable',
            field=models.BooleanField(default=True, help_text='Whether non-superusers may modify this node and its inputs'),
        ),
    ]
