# Generated by Django 6.1 on 2026-08-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('nodes', '0065_datasetmaterialization_validation_violations'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='instanceconfig',
            constraint=models.CheckConstraint(
                condition=models.Q(('config_source', 'yaml'), ('spec__isnull', False), _connector='OR'),
                name='instance_database_source_has_spec',
            ),
        ),
    ]
