name: Lint
on:
  pull_request:
  push:

jobs:
  reviewdog:
    uses: kausaltech/github-actions/.github/workflows/reviewdog-backend.yaml@main
    secrets:
      PRIVATE_SUBMODULE_DEPLOY_KEY: ${{ secrets.PRIVATE_SUBMODULE_DEPLOY_KEY }}
