dimensions:

- id: transport_mode
  label_en: Transport mode
  label_de: Verkehrsmittel
  categories:
  - id: cars
    label_en: Cars
    label_de: Autos
  - id: bicycles
    label_en: Bicycles
    label_de: Fahrräder

actions:

# Levers

- id: lever_on_cars_and_bikes
  name_en: Lever affecting cars and bikes directly
  name_de: Hebel mit direkter Wirkung auf Autos und Fahrräder
  type: simple.GenericAction
  quantity: ratio
  unit: dimensionless
  color: '#2ca25f' # FIXME Does not change color
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Lever affecting cars and bikes directly
    - column: Action
      value: Lever affecting cars and bikes directly
  params:
  - id: multiplier
    is_visible: true
    is_customizable: true
    label_en: Fraction of car traffic shifting to bikes
    label_de: Anteil des Autoverkehrs, der auf Fahrräder verlagert wird
    unit: dimensionless
    value: 0.05
    min_value: 0.0
    max_value: 1.0
    step: 0.01
  output_nodes:
  - id: shift_from_cars_to_bikes
    tags: [other_node]
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

# Actions

- id: municipal_package_delivery_by_bicycle
  name_de: Paketzustellung der Kommune mit dem Rad
  name_en: Municipal Package Delivery by Bicycle
  type: gpc.DatasetActionMFM
  quantity: number
  unit: pcs/cap/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Municipal Package Delivery by Bicycle
  params:
    action: Municipal Package Delivery by Bicycle
  output_nodes:
  - id: shift_from_cars_to_bikes
    tags: [additive, ignore_content]
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    - id: causal_step
      flatten: true 
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      categories: [activity_shift]

- id: amendment_of_parking_space_ordinance
  name_de: Änderung Stellplatzsatzung
  name_en: Amendment of Parking Space Ordinance
  type: gpc.DatasetActionMFM
  quantity: number
  unit: pcs/cap
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Amendment of Parking Space Ordinance
  params:
    action: Amendment of Parking Space Ordinance
  output_nodes:
  - id: number_of_bicycle_parking_spaces
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: expansion_and_improvement_of_bicycle_infrastructure
  name_de: Ausbau und Verbesserung Nutzbarkeit der Rad-Infrastruktur
  name_en: Expansion and Improvement of Bicycle Infrastructure
  type: gpc.DatasetActionMFM
  quantity: length
  unit: km
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Expansion and Improvement of Bicycle Infrastructure
  params:
    action: Expansion and Improvement of Bicycle Infrastructure
  output_nodes:
  - id: number_of_safe_cycling_kilometers
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: visitor_parking_pricing
  name_de: Parkraumbepreisung Besucher*innen
  name_en: Visitor Parking Pricing
  type: gpc.DatasetActionMFM
  quantity: unit_price
  unit: EUR/pcs/d
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Visitor Parking Pricing
  params:
    action: Visitor Parking Pricing
  output_nodes:
  - id: parking_space_prices
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: reduce_user_costs_for_environmentally_friendly_transport
  name_de: Nutzerkosten Umweltverbund reduzieren
  name_en: Reduce User Costs for Environmentally Friendly Transport
  type: gpc.DatasetActionMFM
  quantity: unit_price
  unit: EUR/pcs
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduce User Costs for Environmentally Friendly Transport
  params:
    action: Reduce User Costs for Environmentally Friendly Transport
  output_nodes:
  - id: public_transport_prices
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

nodes:

# Characteristic

- id: number_of_bicycle_parking_spaces
  name_de: Anzahl Fahrrad-Parkplätze
  name_en: Number of Bicycle Parking Spaces
  type: simple.GenericNode
  quantity: number
  unit: pcs/inh
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Number of Bicycle Parking Spaces
  output_nodes:
  - id: comfort
    tags: [additive, ignore_content]

- id: number_of_safe_cycling_kilometers
  name_de: Anzahl sichere Radkilometer
  name_en: Number of Safe Cycling Kilometers
  type: simple.GenericNode
  quantity: length
  unit: km
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Number of Safe Cycling Kilometers
  output_nodes:
  - id: safety
    tags: [additive, ignore_content]
  - id: comfort
    tags: [additive, ignore_content]
  - id: status
    tags: [additive, ignore_content]
  - id: fairness
    tags: [additive, ignore_content]
  - id: health
    tags: [additive, ignore_content]

- id: parking_space_prices
  name_de: Parkplatzpreise
  name_en: Parking Space Prices
  type: simple.GenericNode
  quantity: unit_price
  unit: EUR/pcs/h
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Parking Space Prices
  output_nodes:
  - id: fairness
    tags: [additive, ignore_content]
  - id: affordability
    tags: [additive, ignore_content]

- id: public_transport_prices
  name_de: ÖPNV-Preise
  name_en: Public Transport Prices
  type: simple.GenericNode
  quantity: unit_price
  unit: EUR/pcs
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Public Transport Prices
  output_nodes:
  - id: affordability
    tags: [additive, ignore_content]

# Behavioral change

- id: safety
  name_de: Sicherheit
  name_en: Safety
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Safety
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

- id: comfort
  name_de: Komfort
  name_en: Comfort
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Comfort
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

- id: status
  name_de: Status
  name_en: Status
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Status
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

- id: fairness
  name_de: Gereichtigkeit
  name_en: Fairness
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Fairness
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

- id: health
  name_de: Gesundheit
  name_en: Health
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Health
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

- id: affordability
  name_de: Erschwinglichkeit
  name_en: Affordability
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Affordability
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [activity_shift]

# Activity shift

- id: shift_from_cars_to_bikes
  name_de: Verlagerung von Autos auf Fahrräder
  name_en: Shift from cars to bikes
  type: simple.LeverNode
  quantity: fraction
  unit: dimensionless
  color: '#ccebc5'
  input_dimensions: [sector, causal_step]
  output_dimensions: [sector, causal_step]

# Effect

- id: ghg_emissions
  name_de: THG emissionen
  name_en: GHG emissions
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduced GHG
  output_nodes:
  - id: net_emissions

- id: nox_emissions
  name_de: NOx-Emissionen
  name_en: NOx emissions
  type: simple.GenericNode
  quantity: emissions
  unit: t/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduced NOx

- id: road_maintenance_cost
  name_de: Straßeninstandhaltungskosten
  name_en: Road maintenance cost
  type: simple.GenericNode
  quantity: currency
  unit: MEUR/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Road Maintenance Savings

- id: air_pollution_emissions
  name_de: Luftschadstoffemissionen
  name_en: Air pollution emissions
  type: simple.GenericNode
  quantity: emissions
  unit: t/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduced Air Pollution

- id: reduced_noise
  name_de: Lärmbelastung
  name_en: Noise pollution
  type: simple.GenericNode
  quantity: exposure
  unit: Lden
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduced Noise

# Utility # TODO Utilities are needed for further development, not for demonstration

# - id: utility
#   name_en: Utility
#   type: simple.GenericNode
#   quantity: ratio
#   unit: dimensionless
#   color: '#fed9a6'
#   input_dimensions: [causal_step, sector]
#   output_dimensions: [causal_step, sector]
#   input_nodes:
#   - id: safety
#   - id: comfort
#   - id: status
#   - id: fairness
#   - id: health
#   - id: affordability
#   # - id: net_emissions
#   # - id: road_maintenance_savings
#   # # - id: net_cost
#   # - id: reduced_nox
#   # - id: reduced_air_pollution
#   # - id: reduced_noise
