dimensions:

- id: transport_mode
  label_en: Transport mode
  categories:
  - id: cars
    label_en: Cars
  - id: bicycles
    label_en: Bicycles

actions:

# Levers

- id: lever_on_cars_and_bikes
  name_en: Lever affecting cars and bikes directly
  type: simple.GenericAction
  quantity: ratio
  unit: dimensionless
  color: '#2ca25f' # FIXME Does not change color
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Lever affecting cars and bikes directly
    - column: Action
      value: Lever affecting cars and bikes directly
  params:
  - id: multiplier
    is_visible: true
    is_customizable: true
    label_en: Fraction of car traffic shifting to bikes
    unit: a/kt
    value: 0.05
    min_value: 0.0
    max_value: 1.0
    step: 0.01
  output_nodes:
  - id: shift_from_cars_to_bikes
    tags: [other_node]
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

# Actions

- id: municipal_package_delivery_by_bicycle
  name_de: Paketzustellung der Kommune mit dem Rad
  name_en: Municipal Package Delivery by Bicycle
  type: gpc.DatasetActionMFM
  quantity: emissions
  unit: kt/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Municipal Package Delivery by Bicycle
  params:
    action: Municipal Package Delivery by Bicycle
  # output_nodes:
  # - id: shift_from_cars_to_bikes
  #   from_dimensions:
  #   - id: action_type
  #     flatten: true
  #   - id: instrument_category
  #     flatten: true
  #   - id: action_level
  #     flatten: true
  #   - id: impact_duration
  #     flatten: true
  #   to_dimensions:
  #   - id: sector
  #     categories: [transport]
  #   - id: causal_step

- id: amendment_of_parking_space_ordinance
  name_de: Änderung Stellplatzsatzung
  name_en: Amendment of Parking Space Ordinance
  type: gpc.DatasetActionMFM
  quantity: emissions
  unit: kt/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Amendment of Parking Space Ordinance
  params:
    action: Amendment of Parking Space Ordinance
  output_nodes:
  - id: number_of_bicycle_parking_spaces
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: expansion_and_improvement_of_bicycle_infrastructure
  name_de: Ausbau und Verbesserung Nutzbarkeit der Rad-Infrastruktur
  name_en: Expansion and Improvement of Bicycle Infrastructure
  type: gpc.DatasetActionMFM
  quantity: emissions
  unit: kt/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Expansion and Improvement of Bicycle Infrastructure
  params:
    action: Expansion and Improvement of Bicycle Infrastructure
  output_nodes:
  - id: number_of_safe_cycling_kilometers
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: visitor_parking_pricing
  name_de: Parkraumbepreisung Besucher*innen
  name_en: Visitor Parking Pricing
  type: gpc.DatasetActionMFM
  quantity: emissions
  unit: kt/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Visitor Parking Pricing
  params:
    action: Visitor Parking Pricing
  output_nodes:
  - id: parking_space_prices
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

- id: reduce_user_costs_for_environmentally_friendly_transport
  name_de: Nutzerkosten Umweltverbund reduzieren
  name_en: Reduce User Costs for Environmentally Friendly Transport
  type: gpc.DatasetActionMFM
  quantity: emissions
  unit: kt/a
  input_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  output_dimensions: [causal_step, action_type, instrument_category, action_level, impact_duration]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Reduce User Costs for Environmentally Friendly Transport
  params:
    action: Reduce User Costs for Environmentally Friendly Transport
  output_nodes:
  - id: public_transport_prices
    from_dimensions:
    - id: action_type
      flatten: true
    - id: instrument_category
      flatten: true
    - id: action_level
      flatten: true
    - id: impact_duration
      flatten: true
    to_dimensions:
    - id: sector
      categories: [transport]
    - id: causal_step

nodes:

# Characteristic

- id: number_of_bicycle_parking_spaces
  name_de: Anzahl Fahrrad-Parkplätze
  name_en: Number of Bicycle Parking Spaces
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Number of Bicycle Parking Spaces
  output_nodes:
  - id: comfort
    tags: [additive]

- id: number_of_safe_cycling_kilometers
  name_de: Anzahl sichere Radkilometer
  name_en: Number of Safe Cycling Kilometers
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Number of Safe Cycling Kilometers
  output_nodes:
  - id: safety
    tags: [additive]
  - id: comfort
    tags: [additive]
  - id: status
    tags: [additive]
  - id: fairness
    tags: [additive]
  - id: health
    tags: [additive]

- id: parking_space_prices
  name_de: Parkplatzpreise
  name_en: Parking Space Prices
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Parking Space Prices
  output_nodes:
  - id: fairness
    tags: [additive]
  - id: affordability
    tags: [additive]

- id: public_transport_prices
  name_de: ÖPNV-Preise
  name_en: Public Transport Prices
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#fbb4ae'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_datasets:
  - id: gpc/dinspec
    filters:
    - column: Slice
      value: Public Transport Prices
  output_nodes:
  - id: affordability
    tags: [additive]

# Behavioral change

- id: safety
  name_de: Sicherheit
  name_en: Safety
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Safety
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

- id: comfort
  name_de: Komfort
  name_en: Comfort
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Comfort
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

- id: status
  name_de: Status
  name_en: Status
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Status
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

- id: fairness
  name_de: Gereichtigkeit
  name_en: Fairness
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Fairness
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

- id: health
  name_de: Gesundheit
  name_en: Health
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Health
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

- id: affordability
  name_de: Erschwinglichkeit
  name_en: Affordability
  type: simple.GenericNode
  quantity: ratio
  unit: dimensionless
  color: '#b3cde3'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Affordability
  params:
  - id: multiplier
    value: 1
    unit: a/kt
  output_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: causal_step
      flatten: true
    to_dimensions:
    - id: sector

# Activity shift

- id: shift_from_cars_to_bikes
  name_de: Verlagerung von Autos auf Fahrräder
  name_en: Shift from cars to bikes
  type: simple.LeverNode
  quantity: emissions
  unit: dimensionless
  color: '#ccebc5'
  input_dimensions: [sector]
  output_dimensions: [sector]
  # params:
  #   new_category: sector:buildings
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Shift from cars to bikes

# Effect

- id: reduced_ghg
  name_de: Weniger THG
  name_en: Reduced GHG
  type: simple.GenericNode
  quantity: emissions
  unit: kt/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Reduced GHG
  params:
  - id: multiplier
    value: 1
    unit: kt/a
  output_nodes:
  - id: net_emissions

- id: reduced_nox
  name_de: Weniger NOx
  name_en: Reduced NOx
  type: simple.GenericNode
  quantity: emissions
  unit: ug/m**3
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Reduced NOx
  params:
  - id: multiplier
    value: 1
    unit: ug/m**3

- id: road_maintenance_savings
  name_de: Einsparung Strasseninstandhaltung
  name_en: Road Maintenance Savings
  type: simple.GenericNode
  quantity: emissions
  unit: MEUR/a
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Road Maintenance Savings
  params:
  - id: multiplier
    value: 1
    unit: MEUR/a

- id: reduced_air_pollution
  name_de: Weniger Luftverschmutzung
  name_en: Reduced Air Pollution
  type: simple.GenericNode
  quantity: emissions
  unit: ug/m**3
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Reduced Air Pollution
  params:
  - id: multiplier
    value: 1
    unit: ug/m**3

- id: reduced_noise
  name_de: Weniger Lärm
  name_en: Reduced Noise
  type: simple.GenericNode
  quantity: emissions
  unit: Lden
  color: '#decbe4'
  input_dimensions: [causal_step, sector]
  output_dimensions: [causal_step, sector]
  input_nodes:
  - id: shift_from_cars_to_bikes
    from_dimensions:
    - id: sector
      categories: [transport]
    to_dimensions:
    - id: sector
    - id: causal_step
      categories: [effect]
  # input_datasets:
  # - id: gpc/dinspec
  #   filters:
  #   - column: Slice
  #     value: Reduced Noise
  params:
  - id: multiplier
    value: 1
    unit: Lden

# Utility # TODO Utilities are needed for further development, not for demonstration

# - id: utility
#   name_en: Utility
#   type: simple.GenericNode
#   quantity: ratio
#   unit: dimensionless
#   color: '#fed9a6'
#   input_dimensions: [causal_step, sector]
#   output_dimensions: [causal_step, sector]
#   input_nodes:
#   - id: safety
#   - id: comfort
#   - id: status
#   - id: fairness
#   - id: health
#   - id: affordability
#   # - id: net_emissions
#   # - id: road_maintenance_savings
#   # # - id: net_cost
#   # - id: reduced_nox
#   # - id: reduced_air_pollution
#   # - id: reduced_noise
